--- 
title: "Quantitative Research Methods & Analysis"
author:
- "Adapted for use at EUC by Thomas Hulst"
- "Lead Author: Matthew J. C. Crump"
- "Chapters 2 and 4 adapted from Navarro, D."
- "Videos: Jeffrey Suzuki"
date: "Last Compiled `r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    css: tufte.css
    fontsettings:
      theme: white
      family: sans
      size: 1
documentclass: book
bibliography: [book.bib, packages.bib, MyLibrary.bib,refs.bib]
biblio-style: apalike
link-citations: yes
always_allow_html: yes
description: "An introductory textbook for quantitative research methods and data analysis at EUC. This text was adapted from \"Answering questions with data\" by Matthew J.C. Crump (https://crumplab.github.io/statistics/)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE, cache=TRUE)
library(dplyr)
```

# Preface {-}

----

## Important notes
This is a free textbook for the course "Quantitative Research Methods and Analysis" at EUC. This textbook was adapted from "Answering questions with data" by Mattew J.C. Crump. The original text is part of a larger OER (Open Educational Resource) course package for teaching undergraduate statistics in Psychology. The main OSF (Open Science Framework) project link is [https://osf.io/3s68c/](https://osf.io/3s68c/).

All resources are released under a creative commons licence [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Click the link to read more about the license, or read more below in the license section.

### Attributions

Two of the chapters were adapted from Danielle Navarro's wonderful (and bigger) free textbook, also licensed under the same creative commons license. The citation for that textbook is: Navarro, D. (2018). Learning statistics with R: A tutorial for psychology students and other beginners (version 0.6). The website is [https://compcogscisydney.org/learning-statistics-with-r/](https://compcogscisydney.org/learning-statistics-with-r/)

Chapter notes within the book are provided to indicate sections where material from Navarro was included. A short summary is here:

**Chapter 1: Why statistics**, Adapted nearly verbatim with some editorial changes from Chapters 1 and 2, Navarro, D.

**Chapter 4: Probability, Sampling, and Estimation**, Adapted and expanded from Chapters 9 and 10, Navarro D.

### CC BY-SA 4.0 license

This license means that you are free to:

- Share: copy and redistribute the material in any medium or format
- Adapt: remix, transform, and build upon the material for any purpose, even commercially.

The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:

- Attribution: You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- ShareAlike: If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
- No additional restrictions: You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

