<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 4 Week 4: Chance and Probability Theory13 | Quantitative Research Methods &amp; Analysis</title>
  <meta name="description" content="An introductory textbook for quantitative research methods and analysis at EUC. This text was adapted from “Answering questions with data” by Matthew J.C. Crump (https://crumplab.github.io/statistics/) and “Learning statistics with R” by Danielle Navarro (https://learningstatisticswithr.com) and extended with our own materials." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content=" 4 Week 4: Chance and Probability Theory13 | Quantitative Research Methods &amp; Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An introductory textbook for quantitative research methods and analysis at EUC. This text was adapted from “Answering questions with data” by Matthew J.C. Crump (https://crumplab.github.io/statistics/) and “Learning statistics with R” by Danielle Navarro (https://learningstatisticswithr.com) and extended with our own materials." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 4 Week 4: Chance and Probability Theory13 | Quantitative Research Methods &amp; Analysis" />
  
  <meta name="twitter:description" content="An introductory textbook for quantitative research methods and analysis at EUC. This text was adapted from “Answering questions with data” by Matthew J.C. Crump (https://crumplab.github.io/statistics/) and “Learning statistics with R” by Danielle Navarro (https://learningstatisticswithr.com) and extended with our own materials." />
  

<meta name="author" content="Original Author: Matthew J. C. Crump" />
<meta name="author" content="Adapted materials for chapter 1 and chapters 4-6 from Danielle Navarro" />
<meta name="author" content="Edited for EUC by Thomas Hulst and Thanos Kostopoulos" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chcorrelationandcaus.html"/>
<link rel="next" href="week-5-estimation-and-sampling-theory.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">QuantRMA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#important-notes"><i class="fa fa-check"></i>Important notes</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#attributions"><i class="fa fa-check"></i>Attributions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#cc-by-sa-4.0-license"><i class="fa fa-check"></i>CC BY-SA 4.0 license</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html"><i class="fa fa-check"></i><b>1</b> Week 1: Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#the-curse-of-belief-bias"><i class="fa fa-check"></i><b>1.1</b> The curse of belief bias</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#the-cautionary-tale-of-simpsons-paradox"><i class="fa fa-check"></i><b>1.2</b> The cautionary tale of Simpson’s paradox</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#statistics-in-psychology-psych"><i class="fa fa-check"></i><b>1.3</b> Statistics in psychology</a></li>
<li class="chapter" data-level="1.4" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#statistics-in-everyday-life"><i class="fa fa-check"></i><b>1.4</b> Statistics in everyday life</a></li>
<li class="chapter" data-level="1.5" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#theres-more-to-research-methods-than-statistics"><i class="fa fa-check"></i><b>1.5</b> There’s more to research methods than statistics</a></li>
<li class="chapter" data-level="1.6" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#a-brief-introduction-to-research-methods"><i class="fa fa-check"></i><b>1.6</b> A brief introduction to research methods</a></li>
<li class="chapter" data-level="1.7" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#thoughts-measurement"><i class="fa fa-check"></i><b>1.7</b> Some thoughts about measurement</a></li>
<li class="chapter" data-level="1.8" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#operationalize"><i class="fa fa-check"></i><b>1.8</b> Operationalization: defining your measurement</a></li>
<li class="chapter" data-level="1.9" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#reliab-valid-measurement"><i class="fa fa-check"></i><b>1.9</b> Assessing the reliability and validity of a measurement</a></li>
<li class="chapter" data-level="1.10" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#forms-of-measurement-error"><i class="fa fa-check"></i><b>1.10</b> Forms of measurement error</a></li>
<li class="chapter" data-level="1.11" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#variables"><i class="fa fa-check"></i><b>1.11</b> The role of variables: predictors and outcomes</a></li>
<li class="chapter" data-level="1.12" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#thats-it-for-this-week"><i class="fa fa-check"></i><b>1.12</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html"><i class="fa fa-check"></i><b>2</b> Week 2: Describing Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#scales-of-measurement"><i class="fa fa-check"></i><b>2.1</b> Scales of measurement</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#nominal-scale"><i class="fa fa-check"></i><b>2.1.1</b> Nominal scale</a></li>
<li class="chapter" data-level="2.1.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#ordinal-scale"><i class="fa fa-check"></i><b>2.1.2</b> Ordinal scale</a></li>
<li class="chapter" data-level="2.1.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#interval-scale"><i class="fa fa-check"></i><b>2.1.3</b> Interval scale</a></li>
<li class="chapter" data-level="2.1.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#ratio-scale"><i class="fa fa-check"></i><b>2.1.4</b> Ratio scale</a></li>
<li class="chapter" data-level="2.1.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#continuous-versus-discrete-variables"><i class="fa fa-check"></i><b>2.1.5</b> Continuous versus discrete variables</a></li>
<li class="chapter" data-level="2.1.6" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#some-complexities"><i class="fa fa-check"></i><b>2.1.6</b> Some complexities</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#toomanynumbers"><i class="fa fa-check"></i><b>2.2</b> This is what too many numbers looks like</a></li>
<li class="chapter" data-level="2.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#describing-data-using-graphs"><i class="fa fa-check"></i><b>2.3</b> Describing data using graphs</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#scatterplot"><i class="fa fa-check"></i><b>2.3.1</b> Scatterplot</a></li>
<li class="chapter" data-level="2.3.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#histogram"><i class="fa fa-check"></i><b>2.3.2</b> Histogram</a></li>
<li class="chapter" data-level="2.3.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#other-graphs"><i class="fa fa-check"></i><b>2.3.3</b> Other graphs</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#describing-data-using-numbers"><i class="fa fa-check"></i><b>2.4</b> Describing data using numbers</a></li>
<li class="chapter" data-level="2.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#measures-of-central-tendency-sameness"><i class="fa fa-check"></i><b>2.5</b> Measures of central tendency (sameness)</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#mode"><i class="fa fa-check"></i><b>2.5.1</b> Mode</a></li>
<li class="chapter" data-level="2.5.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#median"><i class="fa fa-check"></i><b>2.5.2</b> Median</a></li>
<li class="chapter" data-level="2.5.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#mean"><i class="fa fa-check"></i><b>2.5.3</b> Mean</a></li>
<li class="chapter" data-level="2.5.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#whatmeanmean"><i class="fa fa-check"></i><b>2.5.4</b> What does the mean mean?</a></li>
<li class="chapter" data-level="2.5.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#all-together-now"><i class="fa fa-check"></i><b>2.5.5</b> All together now</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#measures-of-variation-differentness"><i class="fa fa-check"></i><b>2.6</b> Measures of variation (differentness)</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#the-range"><i class="fa fa-check"></i><b>2.6.1</b> The range</a></li>
<li class="chapter" data-level="2.6.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#difference-scores"><i class="fa fa-check"></i><b>2.6.2</b> Difference scores</a></li>
<li class="chapter" data-level="2.6.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#var-form"><i class="fa fa-check"></i><b>2.6.3</b> The variance</a></li>
<li class="chapter" data-level="2.6.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#the-standard-deviation"><i class="fa fa-check"></i><b>2.6.4</b> The standard deviation</a></li>
<li class="chapter" data-level="2.6.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#closing-thoughts-on-measures-of-variation"><i class="fa fa-check"></i><b>2.6.5</b> Closing thoughts on measures of variation</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#remember-to-look-at-your-data"><i class="fa fa-check"></i><b>2.7</b> Remember to look at your data</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#anscombes-quartet"><i class="fa fa-check"></i><b>2.7.1</b> Anscombe’s Quartet</a></li>
<li class="chapter" data-level="2.7.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#datasaurus-dozen"><i class="fa fa-check"></i><b>2.7.2</b> Datasaurus Dozen</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#thats-it-for-this-week-1"><i class="fa fa-check"></i><b>2.8</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html"><i class="fa fa-check"></i><b>3</b> Week 3: Correlation and Causation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#if-something-caused-something-else-to-change-what-would-that-look-like"><i class="fa fa-check"></i><b>3.1</b> If something caused something else to change, what would that look like?</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#charlie-and-the-chocolate-factory"><i class="fa fa-check"></i><b>3.1.1</b> Charlie and the chocolate factory</a></li>
<li class="chapter" data-level="3.1.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#positive-negative-or-no-correlation"><i class="fa fa-check"></i><b>3.1.2</b> Positive, negative or no correlation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#pears-r"><i class="fa fa-check"></i><b>3.2</b> Pearson’s <span class="math inline">\(r\)</span></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#the-idea-of-covariance"><i class="fa fa-check"></i><b>3.2.1</b> The idea of covariance</a></li>
<li class="chapter" data-level="3.2.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#a-measure-of-covariance"><i class="fa fa-check"></i><b>3.2.2</b> A measure of covariance</a></li>
<li class="chapter" data-level="3.2.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#covariance-formalized"><i class="fa fa-check"></i><b>3.2.3</b> Covariance formalized</a></li>
<li class="chapter" data-level="3.2.4" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#corrform"><i class="fa fa-check"></i><b>3.2.4</b> <span class="math inline">\(r\)</span> we there yet?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#examples-of-r-with-data"><i class="fa fa-check"></i><b>3.3</b> Examples of <span class="math inline">\(r\)</span> with data</a></li>
<li class="chapter" data-level="3.4" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#interpreting-correlations"><i class="fa fa-check"></i><b>3.4</b> Interpreting correlations</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#caus-without-corr"><i class="fa fa-check"></i><b>3.4.1</b> Causation without correlation</a></li>
<li class="chapter" data-level="3.4.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#third-var"><i class="fa fa-check"></i><b>3.4.2</b> Third variables</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#relationships-between-variables"><i class="fa fa-check"></i><b>3.5</b> Relationships between variables</a></li>
<li class="chapter" data-level="3.6" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#establishing-causal-relationships"><i class="fa fa-check"></i><b>3.6</b> Establishing causal relationships</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#a-frame-of-reference"><i class="fa fa-check"></i><b>3.6.1</b> A frame of reference</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#meaningful-comparisons"><i class="fa fa-check"></i><b>3.7</b> Meaningful comparisons</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#random"><i class="fa fa-check"></i><b>3.7.1</b> Randomization</a></li>
<li class="chapter" data-level="3.7.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#matching"><i class="fa fa-check"></i><b>3.7.2</b> Matching</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#taxonomy-of-research-design"><i class="fa fa-check"></i><b>3.8</b> Taxonomy of research design</a></li>
<li class="chapter" data-level="3.9" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#range-of-research-design"><i class="fa fa-check"></i><b>3.9</b> Range of research design</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#experimental-designs"><i class="fa fa-check"></i><b>3.9.1</b> Experimental designs</a></li>
<li class="chapter" data-level="3.9.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#longitudinal-designs"><i class="fa fa-check"></i><b>3.9.2</b> Longitudinal designs</a></li>
<li class="chapter" data-level="3.9.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#cross-sectional-designs"><i class="fa fa-check"></i><b>3.9.3</b> Cross-sectional designs</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#the-validity-of-your-study"><i class="fa fa-check"></i><b>3.10</b> The validity of your study</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#internal-validity"><i class="fa fa-check"></i><b>3.10.1</b> Internal validity</a></li>
<li class="chapter" data-level="3.10.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#external-validity"><i class="fa fa-check"></i><b>3.10.2</b> External validity</a></li>
<li class="chapter" data-level="3.10.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#construct-validity"><i class="fa fa-check"></i><b>3.10.3</b> Construct validity</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#threats-to-experimental-validity"><i class="fa fa-check"></i><b>3.11</b> Threats to experimental validity</a>
<ul>
<li class="chapter" data-level="3.11.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#history-effects"><i class="fa fa-check"></i><b>3.11.1</b> History effects</a></li>
<li class="chapter" data-level="3.11.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#maturation-effects"><i class="fa fa-check"></i><b>3.11.2</b> Maturation effects</a></li>
<li class="chapter" data-level="3.11.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#repeated-testing-effects"><i class="fa fa-check"></i><b>3.11.3</b> Repeated testing effects</a></li>
<li class="chapter" data-level="3.11.4" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#selection-bias"><i class="fa fa-check"></i><b>3.11.4</b> Selection bias</a></li>
<li class="chapter" data-level="3.11.5" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#diffatt"><i class="fa fa-check"></i><b>3.11.5</b> Differential attrition</a></li>
<li class="chapter" data-level="3.11.6" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#non-response-bias"><i class="fa fa-check"></i><b>3.11.6</b> Non-response bias</a></li>
<li class="chapter" data-level="3.11.7" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#regression-to-the-mean"><i class="fa fa-check"></i><b>3.11.7</b> Regression to the mean</a></li>
<li class="chapter" data-level="3.11.8" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#experimenter-bias"><i class="fa fa-check"></i><b>3.11.8</b> Experimenter bias</a></li>
<li class="chapter" data-level="3.11.9" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#demand-effects-and-reactivity"><i class="fa fa-check"></i><b>3.11.9</b> Demand effects and reactivity</a></li>
<li class="chapter" data-level="3.11.10" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#placebo-effects"><i class="fa fa-check"></i><b>3.11.10</b> Placebo effects</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#thats-it-for-this-week-2"><i class="fa fa-check"></i><b>3.12</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chance.html"><a href="chance.html"><i class="fa fa-check"></i><b>4</b> Week 4: Chance and Probability Theory</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chance.html"><a href="chance.html#correlation-and-random-chance"><i class="fa fa-check"></i><b>4.1</b> Correlation and random chance</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="chance.html"><a href="chance.html#monte-carlo-simulation-of-random-correlations"><i class="fa fa-check"></i><b>4.1.1</b> Monte-carlo simulation of random correlations</a></li>
<li class="chapter" data-level="4.1.2" data-path="chance.html"><a href="chance.html#increasing-sample-size-decreases-the-opportunity-for-spurious-correlations"><i class="fa fa-check"></i><b>4.1.2</b> Increasing sample-size decreases the opportunity for spurious correlations</a></li>
<li class="chapter" data-level="4.1.3" data-path="chance.html"><a href="chance.html#animation-of-no-relationship-between-variables"><i class="fa fa-check"></i><b>4.1.3</b> Animation of no relationship between variables</a></li>
<li class="chapter" data-level="4.1.4" data-path="chance.html"><a href="chance.html#animation-with-a-relationship-between-variables"><i class="fa fa-check"></i><b>4.1.4</b> Animation with a relationship between variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="chance.html"><a href="chance.html#how-are-probability-and-statistics-different"><i class="fa fa-check"></i><b>4.2</b> How are probability and statistics different?</a></li>
<li class="chapter" data-level="4.3" data-path="chance.html"><a href="chance.html#mean-prob"><i class="fa fa-check"></i><b>4.3</b> What does probability mean?</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="chance.html"><a href="chance.html#the-frequentist-view"><i class="fa fa-check"></i><b>4.3.1</b> The frequentist view</a></li>
<li class="chapter" data-level="4.3.2" data-path="chance.html"><a href="chance.html#the-bayesian-view"><i class="fa fa-check"></i><b>4.3.2</b> The Bayesian view</a></li>
<li class="chapter" data-level="4.3.3" data-path="chance.html"><a href="chance.html#whats-the-difference-and-who-is-right"><i class="fa fa-check"></i><b>4.3.3</b> What’s the difference? And who is right?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chance.html"><a href="chance.html#basic-probability-theory"><i class="fa fa-check"></i><b>4.4</b> Basic probability theory</a></li>
<li class="chapter" data-level="4.5" data-path="chance.html"><a href="chance.html#prob-dist"><i class="fa fa-check"></i><b>4.5</b> Probability distributions</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="chance.html"><a href="chance.html#binomdist"><i class="fa fa-check"></i><b>4.5.1</b> The binomial distribution</a></li>
<li class="chapter" data-level="4.5.2" data-path="chance.html"><a href="chance.html#working-with-the-binomial-distribution-in-r"><i class="fa fa-check"></i><b>4.5.2</b> Working with the binomial distribution in R</a></li>
<li class="chapter" data-level="4.5.3" data-path="chance.html"><a href="chance.html#norm-dist"><i class="fa fa-check"></i><b>4.5.3</b> The normal distribution</a></li>
<li class="chapter" data-level="4.5.4" data-path="chance.html"><a href="chance.html#probability-density"><i class="fa fa-check"></i><b>4.5.4</b> Probability density</a></li>
<li class="chapter" data-level="4.5.5" data-path="chance.html"><a href="chance.html#other-dist"><i class="fa fa-check"></i><b>4.5.5</b> Other useful distributions</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="chance.html"><a href="chance.html#zscore"><i class="fa fa-check"></i><b>4.6</b> z-scores</a></li>
<li class="chapter" data-level="4.7" data-path="chance.html"><a href="chance.html#thats-it-for-this-week-3"><i class="fa fa-check"></i><b>4.7</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html"><i class="fa fa-check"></i><b>5</b> Week 5: Estimation and Sampling Theory</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#def-pop"><i class="fa fa-check"></i><b>5.1</b> Defining a population</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#simple-random-samples"><i class="fa fa-check"></i><b>5.1.1</b> Simple random samples</a></li>
<li class="chapter" data-level="5.1.2" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#most-samples-are-not-simple-random-samples"><i class="fa fa-check"></i><b>5.1.2</b> Most samples are not simple random samples</a></li>
<li class="chapter" data-level="5.1.3" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><i class="fa fa-check"></i><b>5.1.3</b> How much does it matter if you don’t have a simple random sample?</a></li>
<li class="chapter" data-level="5.1.4" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#population-parameters-and-sample-statistics"><i class="fa fa-check"></i><b>5.1.4</b> Population parameters and sample statistics</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>5.2</b> The law of large numbers</a></li>
<li class="chapter" data-level="5.3" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#sampdistmain"><i class="fa fa-check"></i><b>5.3</b> Sampling distributions</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#samplingdists"><i class="fa fa-check"></i><b>5.3.1</b> Sampling distribution of the sample mean</a></li>
<li class="chapter" data-level="5.3.2" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#sampling-distributions-exist-for-any-sample-statistic"><i class="fa fa-check"></i><b>5.3.2</b> Sampling distributions exist for any sample statistic</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#clt"><i class="fa fa-check"></i><b>5.4</b> The central limit theorem</a></li>
<li class="chapter" data-level="5.5" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#pointestimates"><i class="fa fa-check"></i><b>5.5</b> Estimating population parameters</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#estimating-the-population-mean"><i class="fa fa-check"></i><b>5.5.1</b> Estimating the population mean</a></li>
<li class="chapter" data-level="5.5.2" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#estimating-the-population-standard-deviation"><i class="fa fa-check"></i><b>5.5.2</b> Estimating the population standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#ci"><i class="fa fa-check"></i><b>5.6</b> Estimating a confidence interval</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#degrees-of-freedom"><i class="fa fa-check"></i><b>5.6.1</b> Degrees of freedom</a></li>
<li class="chapter" data-level="5.6.2" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>5.6.2</b> Interpreting a confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="week-5-estimation-and-sampling-theory.html"><a href="week-5-estimation-and-sampling-theory.html#thats-it-for-this-week-4"><i class="fa fa-check"></i><b>5.7</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><i class="fa fa-check"></i><b>6</b> Week 6: Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#hypotheses"><i class="fa fa-check"></i><b>6.1</b> A menagerie of hypotheses</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#research-hypotheses-versus-statistical-hypotheses"><i class="fa fa-check"></i><b>6.1.1</b> Research hypotheses versus statistical hypotheses</a></li>
<li class="chapter" data-level="6.1.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#null-hypotheses-and-alternative-hypotheses"><i class="fa fa-check"></i><b>6.1.2</b> Null hypotheses and alternative hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#errortypes"><i class="fa fa-check"></i><b>6.2</b> Two types of errors</a></li>
<li class="chapter" data-level="6.3" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#teststatistics"><i class="fa fa-check"></i><b>6.3</b> Test statistics and sampling distributions</a></li>
<li class="chapter" data-level="6.4" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#decisionmaking"><i class="fa fa-check"></i><b>6.4</b> Making decisions</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#critical-regions-and-critical-values"><i class="fa fa-check"></i><b>6.4.1</b> Critical regions and critical values</a></li>
<li class="chapter" data-level="6.4.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#a-note-on-statistical-significance"><i class="fa fa-check"></i><b>6.4.2</b> A note on statistical “significance”</a></li>
<li class="chapter" data-level="6.4.3" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#onesidedtests"><i class="fa fa-check"></i><b>6.4.3</b> The difference between one sided and two sided tests</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#pvalue"><i class="fa fa-check"></i><b>6.5</b> The <span class="math inline">\(p\)</span> value of a test</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#the-probability-of-extreme-data"><i class="fa fa-check"></i><b>6.5.1</b> The probability of extreme data</a></li>
<li class="chapter" data-level="6.5.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#a-common-mistake"><i class="fa fa-check"></i><b>6.5.2</b> A common mistake</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#running-the-hypothesis-test-in-practice"><i class="fa fa-check"></i><b>6.6</b> Running the hypothesis test in practice</a></li>
<li class="chapter" data-level="6.7" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#using-hypothesis-tests-to-compare-means"><i class="fa fa-check"></i><b>6.7</b> Using hypothesis tests to compare means</a></li>
<li class="chapter" data-level="6.8" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#the-one-sample-z-test"><i class="fa fa-check"></i><b>6.8</b> The one-sample <span class="math inline">\(z\)</span>-test</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#the-inference-problem-that-the-test-addresses"><i class="fa fa-check"></i><b>6.8.1</b> The inference problem that the test addresses</a></li>
<li class="chapter" data-level="6.8.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#constructing-the-hypothesis-test"><i class="fa fa-check"></i><b>6.8.2</b> Constructing the hypothesis test</a></li>
<li class="chapter" data-level="6.8.3" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#a-worked-example-using-r"><i class="fa fa-check"></i><b>6.8.3</b> A worked example using R</a></li>
<li class="chapter" data-level="6.8.4" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#zassumptions"><i class="fa fa-check"></i><b>6.8.4</b> Assumptions of the <span class="math inline">\(z\)</span>-test</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#onesamplettest"><i class="fa fa-check"></i><b>6.9</b> The one-sample <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#introducing-the-t-test"><i class="fa fa-check"></i><b>6.9.1</b> Introducing the <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="6.9.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#doing-the-test-in-r"><i class="fa fa-check"></i><b>6.9.2</b> Doing the test in R</a></li>
<li class="chapter" data-level="6.9.3" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#ttestoneassumptions"><i class="fa fa-check"></i><b>6.9.3</b> Assumptions of the one sample <span class="math inline">\(t\)</span>-test</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#the-independent-samples-t-test"><i class="fa fa-check"></i><b>6.10</b> The independent samples <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="6.10.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#the-data"><i class="fa fa-check"></i><b>6.10.1</b> The data</a></li>
<li class="chapter" data-level="6.10.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#welchttest"><i class="fa fa-check"></i><b>6.10.2</b> Introducing the test</a></li>
<li class="chapter" data-level="6.10.3" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#doing-the-test-in-r-1"><i class="fa fa-check"></i><b>6.10.3</b> Doing the test in R</a></li>
<li class="chapter" data-level="6.10.4" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#positive-and-negative-t-values"><i class="fa fa-check"></i><b>6.10.4</b> Positive and negative <span class="math inline">\(t\)</span> values</a></li>
<li class="chapter" data-level="6.10.5" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#assumptions"><i class="fa fa-check"></i><b>6.10.5</b> Assumptions of the test</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#pairedsamplesttest"><i class="fa fa-check"></i><b>6.11</b> The paired-samples <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="6.11.1" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#the-data-1"><i class="fa fa-check"></i><b>6.11.1</b> The data</a></li>
<li class="chapter" data-level="6.11.2" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#what-is-the-paired-samples-t-test"><i class="fa fa-check"></i><b>6.11.2</b> What is the paired samples <span class="math inline">\(t\)</span>-test?</a></li>
<li class="chapter" data-level="6.11.3" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#doing-the-test-in-r-2"><i class="fa fa-check"></i><b>6.11.3</b> Doing the test in R</a></li>
</ul></li>
<li class="chapter" data-level="6.12" data-path="week-6-hypothesis-testingweek6-hypothesistesting-1.html"><a href="week-6-hypothesis-testingweek6-hypothesistesting-1.html#thats-it-for-this-week-5"><i class="fa fa-check"></i><b>6.12</b> That’s it for this week…</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>7</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative Research Methods &amp; Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chance" class="section level1" number="4">
<h1><span class="header-section-number"> 4</span> Week 4: Chance and Probability Theory<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a></h1>
<blockquote>
<p>I have studied many languages-French, Spanish and a little Italian, but no one told me that statistics was a foreign language.
—Charmaine J. Forde</p>
</blockquote>
<p>Up to this point in the book, we’ve discussed some of the key ideas in research design, and we’ve talked a little about how you can summarize a data set. To a lot of people, this is all there is to statistics: it’s about calculating averages, collecting all the numbers, drawing graphs, and putting them all in a report somewhere. Kind of like stamp collecting, but with numbers. However, statistics covers much more than that. In fact, descriptive statistics is only a small part of statistics. Another, very useful, part of statistics is that it provides tools <strong>that let you make inferences about data</strong>.</p>
<p>Once you start thinking about statistics in these terms – that statistics is there to help us draw inferences from data – you start seeing examples of it everywhere. For instance, here’s a tiny extract from a newspaper article in the Sydney Morning Herald (30 Oct 2010):</p>
<blockquote>
<p>“I have a tough job” the Premier said in response to a poll which found her government is now the most unpopular Labor administration in polling history, with a primary vote of just 23 per cent.</p>
</blockquote>
<p>This kind of remark is entirely unremarkable in the papers or in everyday life, but let’s have a think about what it entails. A polling company has conducted a survey, usually a pretty big one because they can afford it. I’m too lazy to track down the original survey, so let’s just imagine that they called 1000 voters at random, and 230 (23%) of those claimed that they intended to vote for the party. For the 2010 Federal election, the Australian Electoral Commission reported 4,610,795 enrolled voters in New South Whales; so the opinions of the remaining 4,609,795 voters (about 99.98% of voters) remain unknown to us. Even assuming that no-one lied to the polling company the only thing we can say with confidence is that the true primary vote is somewhere between 230/4610795 (about 0.005%) and 4610025/4610795 (about 99.83%). So, on what basis is it legitimate for the polling company, the newspaper, and the readership to conclude that the Australian Labor Party (ALP) primary vote is about 23%?</p>
<p>The answer to the question is pretty obvious: if I call 1000 people <strong>at random</strong>, and 230 of them say they intend to vote for the ALP, then it seems very unlikely that these are the <strong>only</strong> 230 people out of the entire voting public who actually intend to do so. In other words, we assume that the data collected by the polling company is representative of the population at large. But how representative? Would we be surprised to discover that the true ALP primary vote is actually 24%? 29%? 37%? At this point everyday intuition starts to break down a bit. No-one would be surprised by 24%, and everybody would be surprised by 37%, but it’s a bit hard to say whether 29% is plausible. We need some more powerful tools than just looking at the numbers and guessing. <strong>Inferential statistics</strong> provide the tools that we need to answer these sorts of questions and will be the topic of the remainder of this course.</p>
<p>This week, we start with our journey into inferential statistics by looking at how correlations are affected by random chance to build some intuitions about inference. Then, we will look more formally at an important building block of inferential statistics: probability theory. Next week will focus on another building block of inferential statistics: estimation and sampling theory.</p>
<div id="correlation-and-random-chance" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Correlation and random chance</h2>
<p>Last week, we discussed several ways in which correlation did not mean causation. For example, we looked at <a href="chcorrelationandcaus.html#caus-without-corr">causation without correlation</a> and the <a href="chcorrelationandcaus.html#third-var">third variable problem</a>. However, there is another important important aspect of correlations and that is the fact that they can be produced by random chance. This means that you can find a positive or negative correlation between two measures, when they have absolutely nothing to do with one another. You might have hoped to find zero correlation when two measures are totally unrelated to each other. Although this certainly happens, unrelated measures can produce spurious correlations, just by chance alone.</p>
<p>Let’s demonstrate how correlations can occur by chance when there is no causal connection between two measures. Imagine two participants. One is at the North pole with a lottery machine full of balls with numbers from 1 to 10. The other is at the South pole with a different lottery machine full of balls with numbers from 1 to 10. There are an endless supply of balls in the machine, so every number could be picked for any ball. Each participant randomly chooses 10 balls, then records the number on the ball. In this situation we will assume that there is no possible way that balls chosen by the first participant could causally influence the balls chosen by the second participant. They are on the other side of the world.</p>
<p>Here is what the numbers on each ball could look like for each participant:</p>
<table>
<thead>
<tr class="header">
<th align="right">ball</th>
<th align="right">north_pole</th>
<th align="right">south_pole</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">2</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">3</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">8</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">9</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">8</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">4</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">2</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">4</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">3</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">4</td>
<td align="right">4</td>
</tr>
</tbody>
</table>
<p>In this one case, if we computed Pearson’s <span class="math inline">\(r\)</span>, we would find that <span class="math inline">\(r =\)</span> 0.36. But, we already know that this value does not tell us anything about the relationship between the balls chosen on the North and South pole. We know that the relationship is completely random, because that is how we set up the game.</p>
<p>The better question here is to ask what can random chance do? For example, if we ran our game over and over again thousands of times, each time choosing new balls, and each time computing the correlation, what would we find? The <span class="math inline">\(r\)</span> value will sometimes be positive, sometimes be negative, sometimes be big and sometimes be small. Let’s look at what this random fluctuations would look like. This will give us a window into the kinds of correlations that chance alone can produce.</p>
<div id="monte-carlo-simulation-of-random-correlations" class="section level3" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Monte-carlo simulation of random correlations</h3>
<p>It is possible to use a computer to simulate our game as many times as we want. This process is termed a <a href="https://en.wikipedia.org/wiki/Monte_Carlo_method"><strong>monte-carlo simulation</strong></a>, after the code name for the procedure developped during the <a href="https://www.degruyter.com/view/journals/mcma/22/1/article-p73.xml">Manhattan project</a>.</p>
<p>Below is a script written for R<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a>. We won’t go into the details of the code here, you will do more of this during the labs, but let’s briefly explain what is going on. Notice, the part that says <code>for(sim in 1:1000)</code>. This creates a loop that repeats our game 1000 times. Inside the loop there are variables named <code>north_pole</code> and <code>south_pole</code>. During each simulation, we sample 10 random numbers (between 1 to 10) using <code>runif(10,1,10)</code> into each variable. These random numbers stand for the numbers that would have been on the balls from the lottery machine. Once we have 10 random numbers for each, we compute the correlation using <code>cor(north_pole,south_pole)</code>. Then, we save the correlation value and move on to the next simulation. At the end, we will have 1000 individual Pearson <span class="math inline">\(r\)</span> values.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="chance.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="chance.html#cb12-2" aria-hidden="true" tabindex="-1"></a>simulated_correlations <span class="ot">&lt;-</span> <span class="fu">c</span>() <span class="co"># create empty vector </span></span>
<span id="cb12-3"><a href="chance.html#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb12-4"><a href="chance.html#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(sim <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb12-5"><a href="chance.html#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># pick 10 random numbers between 1 and 10 and round the result to the nearest integer</span></span>
<span id="cb12-6"><a href="chance.html#cb12-6" aria-hidden="true" tabindex="-1"></a>  north_pole <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">10</span>,<span class="dv">1</span>,<span class="dv">10</span>)) </span>
<span id="cb12-7"><a href="chance.html#cb12-7" aria-hidden="true" tabindex="-1"></a>  south_pole <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(<span class="dv">10</span>,<span class="dv">1</span>,<span class="dv">10</span>))</span>
<span id="cb12-8"><a href="chance.html#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># save each calculated correlation in the vector</span></span>
<span id="cb12-9"><a href="chance.html#cb12-9" aria-hidden="true" tabindex="-1"></a>  simulated_correlations[sim] <span class="ot">&lt;-</span> <span class="fu">cor</span>(north_pole,south_pole) </span>
<span id="cb12-10"><a href="chance.html#cb12-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-11"><a href="chance.html#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="chance.html#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a scatterplot with the simulated correlations</span></span>
<span id="cb12-13"><a href="chance.html#cb12-13" aria-hidden="true" tabindex="-1"></a>sim_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sims=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>,simulated_correlations)</span>
<span id="cb12-14"><a href="chance.html#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sim_df, <span class="fu">aes</span>(<span class="at">x =</span> sims, <span class="at">y =</span> simulated_correlations))<span class="sc">+</span></span>
<span id="cb12-15"><a href="chance.html#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb12-16"><a href="chance.html#cb12-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb12-17"><a href="chance.html#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb12-18"><a href="chance.html#cb12-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb12-19"><a href="chance.html#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Simulation of 1000 r values&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:3anotherthousand"></span>
<img src="quantrma_files/figure-html/3anotherthousand-1.png" alt="Figure showing a range of r-values that can be obtained by chance" width="672" />
<p class="caption">
Figure 4.1: Figure showing a range of r-values that can be obtained by chance
</p>
</div>
<p>Each dot in the scatter plot shows the Pearson <span class="math inline">\(r\)</span> for each simulation from 1 to 1000. As you can see the dots are all over of the place, in between the range -1 to 1. The important lesson here is that random chance produced all of these correlations. This means we can find “correlations” in the data that are completely meaningless, and do not reflect any causal relationship between one measure and another.</p>
<p>Let’s illustrate the idea of finding “random” correlations one more time, with an animation. This time, we will show you a scatter plot of the random values sampled for the balls chosen from the North and South pole. If there is no relationship we should see dots going everywhere. If there happens to be a positive relationship (purely by chance), we should see the dots going from the bottom left to the top right. If there happens to be a negative relationship (purely by chance), we should see the dots going from the top left down to the bottom right.</p>
<p>On more thing to prepare you for the animation. There are three scatter plots below, showing negative, positive, and zero correlations between two variables. You’ve already seen these types of graphs before. We are just reminding you that the blue lines are helpful for seeing the correlation. Negative correlations occur when a line goes down from the top left to bottom right. Positive correlations occur when a line goes up from the bottom left to the top right. Zero correlations occur when the line is flat (doesn’t go up or down).</p>
<div class="figure"><span id="fig:3reminder"></span>
<img src="quantrma_files/figure-html/3reminder-1.png" alt="A reminder of what positive, negative, and zero correlation looks like" width="672" />
<p class="caption">
Figure 4.2: A reminder of what positive, negative, and zero correlation looks like
</p>
</div>
<p>OK, now we are ready for the animation. You are looking at the process of sampling two sets of numbers randomly, one for the X variable (north_pole), and one for the Y variable (south_pole). Each time we sample 10 numbers for each, plot them, then draw a line through them. Remember, these numbers are all completely random, so we should expect, on average that there should be no correlation between the numbers. However, this is not what happens. You can the line going all over the place. Sometimes we find a negative correlation (line goes down), sometimes we see a positive correlation (line goes up), and sometimes it looks like zero correlation (line is more flat).</p>
<div class="figure"><span id="fig:3randcor10gif"></span>
<img src="figures/gifs/corUnifn10-1.gif" alt="Completely random data points drawn from a uniform distribution with a small sample-size of 10. The blue line twirls around sometimes showing large correlations that are produced by chance"  />
<p class="caption">
Figure 4.3: Completely random data points drawn from a uniform distribution with a small sample-size of 10. The blue line twirls around sometimes showing large correlations that are produced by chance
</p>
</div>
<p>You might be thinking this is kind of disturbing. If we know that there should be no correlation between two random variables, how come we are finding correlations? This is a big problem right? I mean, if someone showed me a correlation between two things, and then claimed one thing was related to another, how could know I if it was true? After all, it could be chance!</p>
<p>Fortunately, all is not lost. We can look at our simulated data in another way, using a histogram. Remember, just before the animation, we simulated 1000 different correlations using random numbers. By, putting all of those <span class="math inline">\(r\)</span> values into a histogram, we can get a better sense of how chance behaves. We can see what kind of correlations chance is likely or unlikely to produce. Here is a histogram of the simulated <span class="math inline">\(r\)</span> values.</p>
<div class="figure"><span id="fig:3histrandcor"></span>
<img src="quantrma_files/figure-html/3histrandcor-1.png" alt="A histogram showing the frequency distribution of r-values for completely random values between an X and Y variable (sample-size=10). A full range of r-values can be obtained by chance alone. Larger r-values are less common than smaller r-values" width="672" />
<p class="caption">
Figure 4.4: A histogram showing the frequency distribution of r-values for completely random values between an X and Y variable (sample-size=10). A full range of r-values can be obtained by chance alone. Larger r-values are less common than smaller r-values
</p>
</div>
<p>Notice that this histogram is not flat. Most of the simulated <span class="math inline">\(r\)</span> values are close to zero. Notice, also that the bars get smaller as you move away from zero in the positive or negative direction. The general take home here is that chance can produce a wide range of correlations. However, not all correlations happen very often. For example, the bars for -1 and 1 are very small. Chance does not produce nearly perfect correlations very often. The bars around -.5 and .5 are smaller than the bars around zero, as medium correlations do not occur as often as small correlations by chance alone.</p>
<p>You can think of this histogram as the window of chance. It shows what chance often does, and what it often does not do. If you found a correlation under these very same circumstances (e.g., measured the correlation between two sets of 10 random numbers), then you could consult this window. What should you ask the window? How about, could my observed correlation (the one that you found in your data) have come from this window?</p>
<p>Let’s say you found a correlation of <span class="math inline">\(r = .1\)</span>. Could a .1 have come from the histogram? Well, look at the histogram around where the .1 mark on the x-axis is. Is there a big bar there? If so, this means that chance produces this value fairly often. You might be comfortable with the inference: Yes, this .1 could have been produced by chance, because it is well inside the window of chance.
How about <span class="math inline">\(r = .5\)</span>? The bar is much smaller here, you might think, “well, I can see that chance does produce .5 some times, so chance could have produced my .5. Did it? Maybe, maybe not, not sure.” Here, your confidence in a strong inference about the role of chance might start getting a bit shakier.</p>
<p>How about an <span class="math inline">\(r = .95\)</span>?. You might see that the bar for .95 is very very small, perhaps too small to see. What does this tell you? It tells you that chance does not produce .95 very often, hardly if at all, pretty much never. So, if you found a .95 in your data, what would you infer? Perhaps you would be comfortable inferring that chance did not produce your .95, after all, .95 is mostly outside the window of chance.</p>
</div>
<div id="increasing-sample-size-decreases-the-opportunity-for-spurious-correlations" class="section level3" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Increasing sample-size decreases the opportunity for spurious correlations</h3>
<p>Before moving on, let’s do one more thing with correlations. In our pretend lottery game, each participant only sampled 10 balls each. We found that this could lead to a range of correlations between the numbers randomly drawn from either sides of the pole. Indeed, we even found some correlations that were medium to large in size. If you were a researcher who found such correlations, you might be tempted to believe there was a relationship between your measurements. However, we know in our little game, that those correlations would be spurious, just a product of random sampling<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a>.</p>
<p>The good news is that, as a researcher, you get to make the rules of the game. You get to determine how chance can play. This is all still a little bit metaphorical, so let’s make it concrete.</p>
<p>Let’s see what happens in four different scenarios. First, we will repeat what we already did. Each participant will draw 10 balls, then we compute the correlation, and do this over 1000 times and look at a histogram. Second, we will change the game so each participant draws 50 balls each, and then repeat our simulation. Third, and fourth, we will change the game so each participant draws 100 balls each, and then 1000 balls each, and repeat etc.</p>
<p>The graph below shows four different histograms of the Pearson <span class="math inline">\(r\)</span> values in each of the different scenarios. Each scenario involves a different sample-size, from, 10, 50, 100 to 1000.</p>
<div class="figure"><span id="fig:3corrandN"></span>
<img src="quantrma_files/figure-html/3corrandN-1.png" alt="Four histograms showing the frequency distributions of r-values between completely random X and Y variables as a function of sample-size. The width of the distributions shrink as sample-size increases. Smaller sample-sizes are more likely to produce a wider range of r-values by chance. Larger sample-sizes always produce a narrower range of small r-values" width="672" />
<p class="caption">
Figure 4.5: Four histograms showing the frequency distributions of r-values between completely random X and Y variables as a function of sample-size. The width of the distributions shrink as sample-size increases. Smaller sample-sizes are more likely to produce a wider range of r-values by chance. Larger sample-sizes always produce a narrower range of small r-values
</p>
</div>
<pre><code>## List of 93
##  $ line                      :List of 6
##   ..$ colour       : chr &quot;black&quot;
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ lineend      : chr &quot;butt&quot;
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ rect                      :List of 5
##   ..$ fill         : chr &quot;white&quot;
##   ..$ colour       : chr &quot;black&quot;
##   ..$ size         : num 0.5
##   ..$ linetype     : num 1
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ text                      :List of 11
##   ..$ family       : chr &quot;&quot;
##   ..$ face         : chr &quot;plain&quot;
##   ..$ colour       : chr &quot;black&quot;
##   ..$ size         : num 11
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : num 0
##   ..$ lineheight   : num 0.9
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ title                     : NULL
##  $ aspect.ratio              : NULL
##  $ axis.title                : NULL
##  $ axis.title.x              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 2.75points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.title.x.top          :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 2.75points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.title.x.bottom       : NULL
##  $ axis.title.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 2.75points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.title.y.left         : NULL
##  $ axis.title.y.right        :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 0points 2.75points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text                 :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr &quot;grey30&quot;
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.x               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 2.2points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.x.top           :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : num 0
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 2.2points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.x.bottom        : NULL
##  $ axis.text.y               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 1
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 2.2points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.y.left          : NULL
##  $ axis.text.y.right         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 0points 2.2points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.ticks                :List of 6
##   ..$ colour       : chr &quot;grey20&quot;
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ axis.ticks.x              : NULL
##  $ axis.ticks.x.top          : NULL
##  $ axis.ticks.x.bottom       : NULL
##  $ axis.ticks.y              : NULL
##  $ axis.ticks.y.left         : NULL
##  $ axis.ticks.y.right        : NULL
##  $ axis.ticks.length         : &#39;simpleUnit&#39; num 2.75points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ axis.ticks.length.x       : NULL
##  $ axis.ticks.length.x.top   : NULL
##  $ axis.ticks.length.x.bottom: NULL
##  $ axis.ticks.length.y       : NULL
##  $ axis.ticks.length.y.left  : NULL
##  $ axis.ticks.length.y.right : NULL
##  $ axis.line                 :List of 6
##   ..$ colour       : chr &quot;black&quot;
##   ..$ size         : &#39;rel&#39; num 1
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ axis.line.x               : NULL
##  $ axis.line.x.top           : NULL
##  $ axis.line.x.bottom        : NULL
##  $ axis.line.y               : NULL
##  $ axis.line.y.left          : NULL
##  $ axis.line.y.right         : NULL
##  $ legend.background         :List of 5
##   ..$ fill         : NULL
##   ..$ colour       : logi NA
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ legend.margin             : &#39;margin&#39; num [1:4] 5.5points 5.5points 5.5points 5.5points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ legend.spacing            : &#39;simpleUnit&#39; num 11points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ legend.spacing.x          : NULL
##  $ legend.spacing.y          : NULL
##  $ legend.key                : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ legend.key.size           : &#39;simpleUnit&#39; num 1.2lines
##   ..- attr(*, &quot;unit&quot;)= int 3
##  $ legend.key.height         : NULL
##  $ legend.key.width          : NULL
##  $ legend.text               :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ legend.text.align         : NULL
##  $ legend.title              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ legend.title.align        : NULL
##  $ legend.position           : chr &quot;right&quot;
##  $ legend.direction          : NULL
##  $ legend.justification      : chr &quot;center&quot;
##  $ legend.box                : NULL
##  $ legend.box.just           : NULL
##  $ legend.box.margin         : &#39;margin&#39; num [1:4] 0cm 0cm 0cm 0cm
##   ..- attr(*, &quot;unit&quot;)= int 1
##  $ legend.box.background     : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ legend.box.spacing        : &#39;simpleUnit&#39; num 11points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ panel.background          :List of 5
##   ..$ fill         : chr &quot;white&quot;
##   ..$ colour       : logi NA
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ panel.border              : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ panel.spacing             : &#39;simpleUnit&#39; num 5.5points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ panel.spacing.x           : NULL
##  $ panel.spacing.y           : NULL
##  $ panel.grid                :List of 6
##   ..$ colour       : chr &quot;grey92&quot;
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ lineend      : NULL
##   ..$ arrow        : logi FALSE
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_line&quot; &quot;element&quot;
##  $ panel.grid.major          : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ panel.grid.minor          : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ panel.grid.major.x        : NULL
##  $ panel.grid.major.y        : NULL
##  $ panel.grid.minor.x        : NULL
##  $ panel.grid.minor.y        : NULL
##  $ panel.ontop               : logi FALSE
##  $ plot.background           :List of 5
##   ..$ fill         : NULL
##   ..$ colour       : chr &quot;white&quot;
##   ..$ size         : NULL
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ plot.title                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 1.2
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 5.5points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.title.position       : chr &quot;panel&quot;
##  $ plot.subtitle             :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 0points 0points 5.5points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.caption              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : num 1
##   ..$ vjust        : num 1
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 5.5points 0points 0points 0points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.caption.position     : chr &quot;panel&quot;
##  $ plot.tag                  :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : &#39;rel&#39; num 1.2
##   ..$ hjust        : num 0.5
##   ..$ vjust        : num 0.5
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.tag.position         : chr &quot;topleft&quot;
##  $ plot.margin               : &#39;margin&#39; num [1:4] 5.5points 5.5points 5.5points 5.5points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ strip.background          :List of 5
##   ..$ fill         : chr &quot;white&quot;
##   ..$ colour       : chr &quot;black&quot;
##   ..$ size         : &#39;rel&#39; num 2
##   ..$ linetype     : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_rect&quot; &quot;element&quot;
##  $ strip.background.x        : NULL
##  $ strip.background.y        : NULL
##  $ strip.placement           : chr &quot;inside&quot;
##  $ strip.text                :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr &quot;grey10&quot;
##   ..$ size         : &#39;rel&#39; num 0.8
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : &#39;margin&#39; num [1:4] 4.4points 4.4points 4.4points 4.4points
##   .. ..- attr(*, &quot;unit&quot;)= int 8
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ strip.text.x              : NULL
##  $ strip.text.y              :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num -90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ strip.switch.pad.grid     : &#39;simpleUnit&#39; num 2.75points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ strip.switch.pad.wrap     : &#39;simpleUnit&#39; num 2.75points
##   ..- attr(*, &quot;unit&quot;)= int 8
##  $ strip.text.y.left         :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : num 90
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi TRUE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;theme&quot; &quot;gg&quot;
##  - attr(*, &quot;complete&quot;)= logi TRUE
##  - attr(*, &quot;validate&quot;)= logi TRUE</code></pre>
<p>By inspecting the four histograms you should notice a clear pattern. The width or range of each histogram shrinks as the sample-size increases. What is going on here? Well, we already know that we can think of these histograms as windows of chance. They tell us which <span class="math inline">\(r\)</span> values occur fairly often, which do not. When our sample-size is 10, lots of different <span class="math inline">\(r\)</span> values happen. That histogram is very spread out. However, as the sample-size increases, we see that the window of chance gets pulled in. For example, by the time we get to 1000 balls each, almost all of the Pearson <span class="math inline">\(r\)</span> values are very close to 0.</p>
<p>One take home here, is that increasing sample-size narrows the window of chance. So, for example, if you ran a study involving 1000 samples of two measures, and you found a correlation of .5, then you can clearly see in the bottom right histogram that .5 does not occur very often by chance alone. In fact, there is no bar, because it didn’t happen even once in the simulation. As a result, when you have a large sample size like n = 1000, you might be more confident that your observed correlation (say of .5) was not a spurious correlation. If chance is not producing your result, then something else is.</p>
<p>Finally, notice how your confidence about whether or not chance is mucking about with your results depends on your sample size. If you only obtained 10 samples per measurement, and found <span class="math inline">\(r = .5\)</span>, you should not be as confident that your correlation reflects a real relationship. Instead, you can see that <span class="math inline">\(r\)</span>’s of .5 happen fairly often by chance alone.</p>
<blockquote>
<p>Pro tip: when you run an experiment, under ideal circumstances, you get to decide how many samples you will collect. This means narrowing the window of chance.</p>
</blockquote>
<p>Let’s ingrain these ideas with some more animations. When our sample-size is small (referred to as “n is small”), sampling error can cause all sorts of “patterns” in the data. This makes it possible, and indeed common, for “correlations” to occur between two sets of numbers. When we increase the sample-size, sampling error is reduced, making it less possible for correlations to occur just by chance alone.</p>
</div>
<div id="animation-of-no-relationship-between-variables" class="section level3" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Animation of no relationship between variables</h3>
<p>Below we randomly sample numbers for two variables, plot them, and show the correlation using a line. There are four panels, each showing the number of observations in the samples, from 10, 50, 100, to 1000 in each sample.</p>
<p>Remember, because we are randomly sampling numbers, there should be no relationship between the X and Y variables. But, as we have been discussing, we can sometimes observe a correlation due to chance. The important thing to watch is how the line behaves across the four panels. The line twirls around in all directions when the sample size is 10. It is also moves around quite a bit when the sample size is 50 or 100. It still moves a bit when the sample size is 1000, but much less. In all cases we expect the line to be flat, but sometimes the line shows us a pseudo relationship.</p>
<div class="figure"><span id="fig:3corRandfour"></span>
<img src="figures/gifs/corUnifFourNs-1.gif" alt="Animation of how correlation behaves for completely random X and Y variables as a function of sample size. The best fit line is not very stable for small sample-sizes, but becomes more reliably flat as sample-size increases"  />
<p class="caption">
Figure 4.6: Animation of how correlation behaves for completely random X and Y variables as a function of sample size. The best fit line is not very stable for small sample-sizes, but becomes more reliably flat as sample-size increases
</p>
</div>
<p>Which line should you trust? Well, hopefully you can see that the line for 1000 samples is the most stable. It tends to be very flat every time, and it does not depend so much on the particular sample. The line with 10 observations per sample goes all over the place. The take home here, is that if someone told you that they found a correlation, you should want to know how many observations they had in their sample. If they only had 10 observations, how could you trust the claim that there was a correlation? Not now that you know samples that are that small can do all sorts of things by chance alone. If instead, you found out the sample was very large, then you might trust that finding a little bit more. For example, in the above animation you can see that when there are 1000 samples, we never see a strong or even weak correlation; the line is almost always completely flat. This is because chance almost never produces strong correlations when the sample size is very large.</p>
<p>Let’s look at an animation when there actually is a correlation between variables.</p>
</div>
<div id="animation-with-a-relationship-between-variables" class="section level3" number="4.1.4">
<h3><span class="header-section-number">4.1.4</span> Animation with a relationship between variables</h3>
<p>Sometimes there are correlations between two variables that are not caused by chance. Below, we get to watch an animation of four scatter plots. Each shows the correlation between two variables. Again, we change the sample-size in steps of 10, 50 100, and 1000. The data have been <strong>programmed to contain a real positive correlation</strong>. So, we should expect that the line will be going up from the bottom left to the top right. However, there is still variability in the data. So this time, sampling error due to chance will fuzz the correlation. We know it is there, but sometimes chance will cause the correlation to be eliminated.</p>
<p>Notice that in the top left panel (sample-size 10), the line is twirling around much more than the other panels. Every new set of samples produces different correlations. Sometimes, the line even goes flat or downward. However, as we increase sample-size, we can see that the line doesn’t change very much, it is always going up showing a positive correlation.</p>
<div class="figure"><span id="fig:3realcorFour"></span>
<img src="figures/gifs/corRealgif-1.gif" alt="How correlation behaves as a function of sample-size when there is a true correlation between X and Y variables"  />
<p class="caption">
Figure 4.7: How correlation behaves as a function of sample-size when there is a true correlation between X and Y variables
</p>
</div>
<p>The main takeaway here is that even when there is a positive correlation between two things, you might not be able to see it if your sample size is small. For example, you might get unlucky with the one sample that you measured. Your sample could show a negative correlation, even when the actual correlation is positive! Unfortunately, in the real world we usually only have the sample that we collected, so we always have to wonder if we got lucky or unlucky. If you want to remove luck, you need to collect larger samples. Then you will be much more likely to observe the real pattern, rather the a pattern that can be introduced by chance.</p>
<p>This concludes the first part of this chapter: building an intuition about inferential statistics by seeing how random chance underlies our observations. Now, we move on to the second part of this chapter: probability theory.</p>
</div>
</div>
<div id="how-are-probability-and-statistics-different" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> How are probability and statistics different?</h2>
<p>Before we start talking about probability theory in more detail, it’s helpful to spend a moment thinking about the relationship between probability and statistics. The two disciplines are closely related but they’re not identical. Probability theory is “the doctrine of chances.” It’s a branch of mathematics that tells you how often different kinds of events will happen. For example, all of these questions are things you can answer using probability theory:</p>
<ul>
<li>What are the chances of a fair coin coming up heads 10 times in a row?</li>
<li>If I roll two six sided dice, how likely is it that I’ll roll two sixes?</li>
<li>How likely is it that five cards drawn from a perfectly shuffled deck will all be hearts?</li>
<li>What are the chances that I’ll win the lottery?</li>
</ul>
<p>Notice that all of these questions have something in common. In each case the “truth of the world” is known, and my question relates to the “what kind of events” will happen. In the first question I <strong>know</strong> that the coin is fair, so there’s a 50% chance that any individual coin flip will come up heads. In the second question, I <strong>know</strong> that the chance of rolling a 6 on a single die is 1 in 6. In the third question I <strong>know</strong> that the deck is shuffled properly. And in the fourth question, I <strong>know</strong> that the lottery follows specific rules. You get the idea. The critical point is that probabilistic questions start with a known <em>model</em> of the world, and we use that model to do some calculations.</p>
<p>The underlying model can be quite simple. For instance, in the coin flipping example, we can write down the model like this:</p>
<p><span class="math inline">\(P(\mbox{heads}) = 0.5\)</span></p>
<p>which you can read as “the probability of heads is 0.5.” As we’ll see later, in the same way that percentages are numbers that range from 0% to 100%, probabilities are just numbers that range from 0 to 1. When using this probability model to answer the first question, I don’t actually know exactly what’s going to happen. Maybe I’ll get 10 heads, like the question says. But maybe I’ll get three heads. That’s the key thing: in probability theory, the <strong>model</strong> is known, but the <strong>data</strong> are not.</p>
<p>So that’s probability. What about statistics? Statistical questions work the other way around. In statistics, we do not know the truth about the world. All we have is the data, and it is from the data that we want to <strong>learn</strong> the truth about the world. Statistical questions tend to look more like these:</p>
<ul>
<li>If my friend flips a coin 10 times and gets 10 heads, are they playing a trick on me?</li>
<li>If five cards off the top of the deck are all hearts, how likely is it that the deck was shuffled?</li>
<li>If the lottery commissioner’s spouse wins the lottery, how likely is it that the lottery was rigged?</li>
</ul>
<p>This time around, the only thing we have are data. What I <strong>know</strong> is that I saw my friend flip the coin 10 times and it came up heads every time. And what I want to <em>infer</em> is whether or not I should conclude that what I just saw was actually a fair coin being flipped 10 times in a row, or whether I should suspect that my friend is playing a trick on me. The data I have looks like this:</p>
<pre><code>H H H H H H H H H H H</code></pre>
<p>and what I’m trying to do is work out which “model of the world” I should put my trust in. If the coin is fair, then the model I should adopt is one that says that the probability of heads is 0.5; that is, <span class="math inline">\(P(\mbox{heads}) = 0.5\)</span>. If the coin is not fair, then I should conclude that the probability of heads is <strong>not</strong> 0.5, which we would write as <span class="math inline">\(P(\mbox{heads}) \neq 0.5\)</span>. In other words, the statistical inference problem is to figure out which of these probability models is right. Clearly, the statistical question isn’t the same as the probability question, but they’re deeply connected to one another. Because of this, a good introduction to statistical theory will start with a discussion of what probability is and how it works.</p>
</div>
<div id="mean-prob" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> What does probability mean?</h2>
<p>Let’s start with the first of these questions. What is “probability?” It might seem surprising to you, but while statisticians and mathematicians (mostly) agree on what the <strong>rules</strong> of probability are, there’s much less of a consensus on what the word really <strong>means</strong>. It seems weird because we’re all very comfortable using words like “chance,” “likely,” “possible” and “probable,” and it doesn’t seem like it should be a very difficult question to answer. If you had to explain “probability” to a five year old, you could do a pretty good job. But if you’ve ever had that experience in real life, you might walk away from the conversation feeling like you didn’t quite get it right, and that (like many everyday concepts) it turns out that you don’t <strong>really</strong> know what it’s all about.</p>
<p>So I’ll have a go at it. Let’s suppose I want to bet on a soccer game between two teams of robots, <strong>Arduino Arsenal</strong> and <strong>CPU Milan</strong>. After thinking about it, I decide that there is an 80% probability that <strong>Arduino Arsenal</strong> wins. What do I mean by that? Here are three possibilities…</p>
<ul>
<li>They’re robot teams, so I can make them play over and over again, and if I did that, <strong>Arduino Arsenal</strong> would win 8 out of every 10 games on average.</li>
<li>For any given game, I would only agree that betting on this game is “fair” if a $1 bet on <strong>CPU Milan</strong> gives a $5 payoff (i.e. I get my $1 back plus a $4 reward for being correct), as would a $4 bet on <strong>Arduino Arsenal</strong> (i.e., my $4 bet plus a $1 reward).</li>
<li>My subjective “belief” or “confidence” in an <strong>Arduino Arsenal</strong> victory is four times as strong as my belief in a <strong>CPU Milan</strong> victory.</li>
</ul>
<p>Each of these seems sensible. However they’re not identical, and not every statistician would endorse all of them. The reason is that there are different statistical ideologies (yes, really!) and depending on which one you subscribe to, you might say that some of those statements are meaningless or irrelevant. In this section, I give a brief introduction the two main approaches that exist in the literature. These are by no means the only approaches, but they’re the two big ones.</p>
<div id="the-frequentist-view" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> The frequentist view</h3>
<p>The first of the two major approaches to probability, and the more dominant one in statistics, is referred to as the <em>frequentist view</em>, and it defines probability as a <em>long-run frequency</em>. Suppose we were to try flipping a fair coin, over and over again. By definition, this is a coin that has <span class="math inline">\(P(H) = 0.5\)</span>. What might we observe? One possibility is that the first 20 flips might look like this:</p>
<pre><code>T,H,H,H,H,T,T,H,H,H,H,T,H,H,T,T,T,T,T,H</code></pre>
<p>In this case 11 of these 20 coin flips (55%) came up heads. Now suppose that I’d been keeping a running tally of the number of heads (which I’ll call <span class="math inline">\(N_H\)</span>) that I’ve seen, across the first <span class="math inline">\(N\)</span> flips, and calculate the proportion of heads <span class="math inline">\(N_H / N\)</span> every time. Here’s what I’d get (I did literally flip coins to produce this!):</p>
<table>
<tbody>
<tr class="odd">
<td align="left">number of flips</td>
<td align="center">1</td>
<td align="center">2</td>
<td align="center">3</td>
<td align="center">4</td>
<td align="center">5</td>
<td align="center">6</td>
<td align="center">7</td>
<td align="center">8</td>
<td align="center">9</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td align="left">number of heads</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">2</td>
<td align="center">3</td>
<td align="center">4</td>
<td align="center">4</td>
<td align="center">4</td>
<td align="center">5</td>
<td align="center">6</td>
<td align="center">7</td>
</tr>
<tr class="odd">
<td align="left">proportion</td>
<td align="center">.00</td>
<td align="center">.50</td>
<td align="center">.67</td>
<td align="center">.75</td>
<td align="center">.80</td>
<td align="center">.67</td>
<td align="center">.57</td>
<td align="center">.63</td>
<td align="center">.67</td>
<td align="center">.70</td>
</tr>
</tbody>
</table>
<table>
<tbody>
<tr class="odd">
<td align="left">number of flips</td>
<td align="center">11</td>
<td align="center">12</td>
<td align="center">13</td>
<td align="center">14</td>
<td align="center">15</td>
<td align="center">16</td>
<td align="center">17</td>
<td align="center">18</td>
<td align="center">19</td>
<td align="center">20</td>
</tr>
<tr class="even">
<td align="left">number of heads</td>
<td align="center">8</td>
<td align="center">8</td>
<td align="center">9</td>
<td align="center">10</td>
<td align="center">10</td>
<td align="center">10</td>
<td align="center">10</td>
<td align="center">10</td>
<td align="center">10</td>
<td align="center">11</td>
</tr>
<tr class="odd">
<td align="left">proportion</td>
<td align="center">.73</td>
<td align="center">.67</td>
<td align="center">.69</td>
<td align="center">.71</td>
<td align="center">.67</td>
<td align="center">.63</td>
<td align="center">.59</td>
<td align="center">.56</td>
<td align="center">.53</td>
<td align="center">.55</td>
</tr>
</tbody>
</table>
<p>Notice that at the start of the sequence, the <strong>proportion</strong> of heads fluctuates wildly, starting at .00 and rising as high as .80. Later on, one gets the impression that it dampens out a bit, with more and more of the values actually being pretty close to the “right” answer of .50. This is the frequentist definition of probability in a nutshell: flip a fair coin over and over again, and as <span class="math inline">\(N\)</span> grows large (approaches infinity, denoted <span class="math inline">\(N\rightarrow \infty\)</span>), the proportion of heads will converge to 50%. There are some subtle technicalities that the mathematicians care about, but qualitatively speaking, that’s how the frequentists define probability.</p>
<p>Unfortunately, I don’t have an infinite number of coins, or the infinite patience required to flip a coin an infinite number of times. However, I do have a computer, and computers excel at mindless repetitive tasks. So I asked my computer to simulate flipping a coin 1000 times, and then drew a picture of what happens to the proportion <span class="math inline">\(N_H / N\)</span> as <span class="math inline">\(N\)</span> increases. Actually, I did it four times, just to make sure it wasn’t a fluke. The results are shown in Figure <a href="chance.html#fig:4FreqProb">4.8</a>. As you can see, the <strong>proportion of observed heads</strong> eventually stops fluctuating, and settles down; when it does, the number at which it finally settles is (close to) the “true” probability of heads.</p>
<div class="figure"><span id="fig:4FreqProb"></span>
<img src="figures/probability/frequentistProb-eps-converted-to.png" alt="An illustration of how frequentist probability works. If you flip a fair coin over and over again, the proportion of heads that you've seen eventually settles down, and converges to the true probability of 0.5. Each panel shows four different simulated experiments: in each case, we pretend we flipped a coin 1000 times, and kept track of the proportion of flips that were heads as we went along. Although none of these sequences actually ended up with an exact value of .5, if we'd extended the experiment for an infinite number of coin flips they would have." width="1164" />
<p class="caption">
Figure 4.8: An illustration of how frequentist probability works. If you flip a fair coin over and over again, the proportion of heads that you’ve seen eventually settles down, and converges to the true probability of 0.5. Each panel shows four different simulated experiments: in each case, we pretend we flipped a coin 1000 times, and kept track of the proportion of flips that were heads as we went along. Although none of these sequences actually ended up with an exact value of .5, if we’d extended the experiment for an infinite number of coin flips they would have.
</p>
</div>
<p>The frequentist definition of probability has some desirable characteristics. First, it is objective: the probability of an event is <strong>necessarily</strong> grounded in the world. The only way that probability statements can make sense is if they refer to (a sequence of) events that occur in the physical universe. Second, it is unambiguous: any two people watching the same sequence of events unfold, trying to calculate the probability of an event, must inevitably come up with the same answer.</p>
<p>However, it also has undesirable characteristics. Infinite sequences don’t exist in the physical world. For example, suppose you picked up a coin from your pocket and started to flip it. Every time it lands, it impacts on the ground. Each impact wears the coin down a bit; eventually, the coin will be destroyed. So, one might ask whether it really makes sense to pretend that an “infinite” sequence of coin flips is even a meaningful concept, or an objective one. We can’t say that an “infinite sequence” of events is a real thing in the physical universe, because the physical universe doesn’t allow infinite anything.</p>
<p>More seriously, the frequentist definition has a narrow scope. There are lots of things out there that human beings are happy to assign probability to in everyday language, but cannot (even in theory) be mapped onto a hypothetical sequence of events. For instance, if a meteorologist comes on TV and says, “the probability of rain in Rotterdam on 2 November 2048 is 60%” we humans are happy to accept this. But it’s not clear how to define this in frequentist terms. There’s only one city of Rotterdam, and only one November 2, 2048. There’s no infinite sequence of events here, just a once-off thing. Frequentist probability genuinely <strong>forbids</strong> us from making probability statements about a single event. From the frequentist perspective, it will either rain tomorrow or it will not; there is no “probability” that attaches to a single non-repeatable event. Now, it should be said that there are some very clever tricks that frequentists can use to get around this. One possibility is that what the meteorologist means is something like this: “There is a category of days for which I predict a 60% chance of rain; if we look only across those days for which I make this prediction, then on 60% of those days it will actually rain.” It’s very weird and counterintuitive to think of it this way, but you do see frequentists do this sometimes.</p>
</div>
<div id="the-bayesian-view" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> The Bayesian view</h3>
<p>The <strong>Bayesian view</strong> of probability is often called the subjectivist view, and it is a minority view among statisticians, but one that has been steadily gaining traction for the last several decades. There are many flavours of Bayesianism, making hard to say exactly what “the” Bayesian view is. The most common way of thinking about subjective probability is to define the probability of an event as the <strong>degree of belief</strong> that an intelligent and rational agent assigns to that truth of that event. From that perspective, probabilities don’t exist in the world, but rather in the thoughts and assumptions of people and other intelligent beings. However, in order for this approach to work, we need some way of operationalising the “degree of belief.” One way that you can do this is to formalise it in terms of “rational gambling,” though there are many other ways. Suppose that I believe that there’s a 60% probability of rain tomorrow. If someone offers me a bet: if it rains tomorrow, then I win $5, but if it doesn’t rain then I lose $5. Clearly, from my perspective, this is a pretty good bet. On the other hand, if I think that the probability of rain is only 40%, then it’s a bad bet to take. Thus, we can operationalise the notion of a “subjective probability” in terms of what bets I’m willing to accept.</p>
<p>What are the advantages and disadvantages to the Bayesian approach? The main advantage is that it allows you to assign probabilities to any event you want to. You don’t need to be limited to those events that are repeatable. The main disadvantage (to many people) is that we can’t be purely objective – specifying a probability requires us to specify an entity that has the relevant degree of belief. This entity might be a human, an alien, a robot, or even a statistician, but there has to be an intelligent agent out there that believes in things. To many people this is uncomfortable: it seems to make probability arbitrary. While the Bayesian approach does require that the agent in question be rational (i.e., obey the rules of probability), it does allow everyone to have their own beliefs; I can believe the coin is fair and you don’t have to, even though we’re both rational. The frequentist view doesn’t allow any two observers to attribute different probabilities to the same event: when that happens, then at least one of them must be wrong. The Bayesian view does not prevent this from occurring. Two observers with different background knowledge can legitimately hold different beliefs about the same event. In short, where the frequentist view is sometimes considered to be too narrow (forbids lots of things that that we want to assign probabilities to), the Bayesian view is sometimes thought to be too broad (allows too many differences between observers).</p>
</div>
<div id="whats-the-difference-and-who-is-right" class="section level3" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> What’s the difference? And who is right?</h3>
<p>Now that you’ve seen each of these two views independently, it’s useful to make sure you can compare the two. Go back to the hypothetical robot soccer game at the start of the section. What do you think a frequentist and a Bayesian would say about these three statements? Which statement would a frequentist say is the correct definition of probability? Which one would a Bayesian do? Would some of these statements be meaningless to a frequentist or a Bayesian? If you’ve understood the two perspectives, you should have some sense of how to answer those questions.</p>
<p>Okay, assuming you understand the difference, you might be wondering which of them is <strong>right</strong>? Honestly, I don’t know that there is a right answer. As far as I can tell there’s nothing mathematically incorrect about the way frequentists think about sequences of events, and there’s nothing mathematically incorrect about the way that Bayesians define the beliefs of a rational agent. In fact, when you dig down into the details, Bayesians and frequentists actually agree about a lot of things. Many frequentist methods lead to decisions that Bayesians agree a rational agent would make. Many Bayesian methods have very good frequentist properties.</p>
<p>For the most part, I’m a pragmatist so I’ll use any statistical method that I trust. As it turns out, that makes me prefer Bayesian methods, but I’m not fundamentally opposed to frequentist methods. Not everyone is quite so relaxed. For instance, consider Sir Ronald Fisher (<a href="chcorrelationandcaus.html#pears-r">yes, that Fisher</a>), a vehement opponent to all things Bayesian, whose paper on the mathematical foundations of statistics referred to Bayesian probability as “an impenetrable jungle [that] arrests progress towards precision of statistical concepts” <span class="citation"><a href="references.html#ref-fisher_interpretation_1922" role="doc-biblioref">Fisher</a> (<a href="references.html#ref-fisher_interpretation_1922" role="doc-biblioref">1922, 311</a>)</span>. Or the psychologist Paul Meehl, who suggests that relying on frequentist methods could turn you into “a potent but sterile intellectual rake who leaves in his merry path a long train of ravished maidens but no viable scientific offspring” <span class="citation"><a href="references.html#ref-meehl_theory_1967" role="doc-biblioref">Meehl</a> (<a href="references.html#ref-meehl_theory_1967" role="doc-biblioref">1967, 114</a>)</span>. The history of statistics, as you might gather, is not devoid of entertainment.</p>
</div>
</div>
<div id="basic-probability-theory" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Basic probability theory</h2>
<p>Ideological arguments between Bayesians and frequentists notwithstanding, it turns out that people mostly agree on the rules that probabilities should obey. There are lots of different ways of arriving at these rules. The most commonly used approach is based on the work of Andrey Kolmogorov, one of the great Soviet mathematicians of the 20th century. I won’t go into a lot of detail, but I’ll try to give you a bit of a sense of how it works. And in order to do so, I’m going to have to talk about my pants.</p>
<p>One of the disturbing truths about my life is that I only own 5 pairs of pants: three pairs of jeans, the bottom half of a suit, and a pair of tracksuit pants. Even sadder, I’ve given them names: I call them <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, <span class="math inline">\(X_3\)</span>, <span class="math inline">\(X_4\)</span> and <span class="math inline">\(X_5\)</span>. I really do: that’s why they call me Mister Imaginative. Now, on any given day, I pick out exactly one of pair of pants to wear. Not even I’m so stupid as to try to wear two pairs of pants, and thanks to years of training I never go outside without wearing pants anymore. If I were to describe this situation using the language of probability theory, I would refer to each pair of pants (i.e., each <span class="math inline">\(X\)</span>) as an <em>elementary event</em>. The key characteristic of elementary events is that every time we make an observation (e.g., every time I put on a pair of pants), then the outcome will be one and only one of these events. Like I said, these days I always wear exactly one pair of pants, so my pants satisfy this constraint. Similarly, the set of all possible events is called a <em>sample space</em>. Granted, some people would call it a “wardrobe,” but that’s because they’re refusing to think about my pants in probabilistic terms. Sad.</p>
<p>Okay, now that we have a sample space (a wardrobe), which is built from lots of possible elementary events (pants), what we want to do is assign a <em>probability</em> to one of these elementary events. For an event <span class="math inline">\(X\)</span>, the probability of that event <span class="math inline">\(P(X)\)</span> is a number that lies between 0 and 1. The bigger the value of <span class="math inline">\(P(X)\)</span>, the more likely the event is to occur. So, for example, if <span class="math inline">\(P(X) = 0\)</span>, it means the event <span class="math inline">\(X\)</span> is impossible (i.e., I never wear those pants). On the other hand, if <span class="math inline">\(P(X) = 1\)</span> it means that event <span class="math inline">\(X\)</span> is certain to occur (i.e., I always wear those pants). For probability values in the middle, it means that I sometimes wear those pants. For instance, if <span class="math inline">\(P(X) = 0.5\)</span> it means that I wear those pants half of the time.</p>
<p>At this point, we’re almost done. The last thing we need to recognise is that “something always happens.” Every time I put on pants, I really do end up wearing pants (crazy, right?). What this somewhat trite statement means, in probabilistic terms, is that the probabilities of the elementary events need to add up to 1. This is known as the <em>law of total probability</em>, not that any of us really care. More importantly, if these requirements are satisfied, then what we have is a <em>probability distribution</em>. For example, this is an example of a probability distribution</p>
<table>
<thead>
<tr class="header">
<th align="left">Which pants?</th>
<th align="center">Label</th>
<th align="center">Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Blue jeans</td>
<td align="center"><span class="math inline">\(X_1\)</span></td>
<td align="center"><span class="math inline">\(P(X_1) = .5\)</span></td>
</tr>
<tr class="even">
<td align="left">Grey jeans</td>
<td align="center"><span class="math inline">\(X_2\)</span></td>
<td align="center"><span class="math inline">\(P(X_2) = .3\)</span></td>
</tr>
<tr class="odd">
<td align="left">Black jeans</td>
<td align="center"><span class="math inline">\(X_3\)</span></td>
<td align="center"><span class="math inline">\(P(X_3) = .1\)</span></td>
</tr>
<tr class="even">
<td align="left">Black suit</td>
<td align="center"><span class="math inline">\(X_4\)</span></td>
<td align="center"><span class="math inline">\(P(X_4) = 0\)</span></td>
</tr>
<tr class="odd">
<td align="left">Blue tracksuit</td>
<td align="center"><span class="math inline">\(X_5\)</span></td>
<td align="center"><span class="math inline">\(P(X_5) = .1\)</span></td>
</tr>
</tbody>
</table>
<p>Each of the events has a probability that lies between 0 and 1, and if we add up the probability of all events, they sum to 1. Awesome. We can even draw a nice bar graph to visualise this distribution, as shown in Figure <a href="chance.html#fig:pantsprob">4.9</a>. And at this point, we’ve all achieved something. You’ve learned what a probability distribution is, and I’ve finally managed to find a way to create a graph that focuses entirely on my pants. Everyone wins!</p>
<div class="figure"><span id="fig:pantsprob"></span>
<img src="quantrma_files/figure-html/pantsprob-1.png" alt="A visual depiction of the &quot;pants&quot; probability distribution. There are five &quot;elementary events&quot;, corresponding to the five pairs of pants that I own. Each event has some probability of occurring: this probability is a number between 0 to 1. The sum of these probabilities is 1." width="672" />
<p class="caption">
Figure 4.9: A visual depiction of the “pants” probability distribution. There are five “elementary events,” corresponding to the five pairs of pants that I own. Each event has some probability of occurring: this probability is a number between 0 to 1. The sum of these probabilities is 1.
</p>
</div>
<p>The only other thing that I need to point out is that probability theory allows you to talk about <em>non elementary events</em> as well as elementary ones. The easiest way to illustrate the concept is with an example. In the pants example, it’s perfectly legitimate to refer to the probability that I wear jeans. In this scenario, the “Thomas wears jeans” event said to have happened as long as the elementary event that actually did occur is one of the appropriate ones; in this case “blue jeans,” “black jeans” or “grey jeans.” In mathematical terms, we defined the “jeans” event <span class="math inline">\(E\)</span> to correspond to the set of elementary events <span class="math inline">\((X_1, X_2, X_3)\)</span>. If any of these elementary events occurs, then <span class="math inline">\(E\)</span> is also said to have occurred. Having decided to write down the definition of the <span class="math inline">\(E\)</span> this way, it’s pretty straightforward to state what the probability <span class="math inline">\(P(E)\)</span> is: we just add everything up. In this particular case <span class="math display">\[P(E) = P(X_1) + P(X_2) + P(X_3)\]</span> and, since the probabilities of blue, grey and black jeans respectively are .5, .3 and .1, the probability that I wear jeans is equal to .9.</p>
<p>At this point you might be thinking that this is all terribly obvious and simple and you’d be right. All we’ve really done is wrap some basic mathematics around a few common sense intuitions. However, from these simple beginnings it’s possible to construct some extremely powerful mathematical tools. I’m definitely not going to go into the details in this book, but what I will do is list some of the other rules that probabilities satisfy. These rules can be derived from the simple assumptions that I’ve outlined above, but since we don’t actually use these rules for anything in this book, I won’t do so here.</p>
<table>
<thead>
<tr class="header">
<th align="left">English</th>
<th align="right">Notation</th>
<th></th>
<th align="left">Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">not <span class="math inline">\(A\)</span></td>
<td align="right"><span class="math inline">\(P(\neg A)\)</span></td>
<td><span class="math inline">\(=\)</span></td>
<td align="left"><span class="math inline">\(1-P(A)\)</span></td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span></td>
<td align="right"><span class="math inline">\(P(A \cup B)\)</span></td>
<td><span class="math inline">\(=\)</span></td>
<td align="left"><span class="math inline">\(P(A) + P(B) - P(A \cap B)\)</span></td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span></td>
<td align="right"><span class="math inline">\(P(A \cap B)\)</span></td>
<td><span class="math inline">\(=\)</span></td>
<td align="left"><span class="math inline">\(P(A|B) \cdot P(B)\)</span></td>
</tr>
</tbody>
</table>
<p>You don’t really need to know these rules in order to understand the analyses that we’ll talk about later in the book, but they are important if you want to understand probability theory a bit more deeply.</p>
</div>
<div id="prob-dist" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Probability distributions</h2>
<p>You just saw your first probability distribution in Figure <a href="chance.html#fig:pantsprob">4.9</a>. The concept of a probability distributions is hugely important for understanding inferential statistics. As you might imagine, probability distributions can vary enormously, and there’s a large range of different distributions out there. However, not all probability distributions are equally important. In fact, the vast majority of the content in this book relies on one of three distributions: the binomial distribution, the normal distribution and the <span class="math inline">\(t\)</span> distribution. Given this, what I’ll do over the next few sections is provide a brief introduction to these distributions, paying special attention to the binomial and the normal. I’ll start with the binomial distribution, since it’s the simplest of the three.</p>
<div id="binomdist" class="section level3" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> The binomial distribution</h3>
<p>The theory of probability originated in the attempt to describe how games of chance work, so it seems fitting that our discussion of the <strong>binomial distribution</strong> should involve a discussion of rolling dice and flipping coins. Let’s imagine a simple “experiment”: in my hot little hand I’m holding 20 identical six-sided dice. On one face of each die there’s a picture of a skull; the other five faces are all blank. If I proceed to roll all 20 dice, what’s the probability that I’ll get exactly 4 skulls? Assuming that the dice are fair, we know that the chance of any one die coming up skulls is 1 in 6; to say this another way, the skull probability for a single die is approximately <span class="math inline">\(.167\)</span>. This is enough information to answer our question, so let’s have a look at how it’s done.</p>
<p>As usual, we have to introduce some names and some notation. We’ll let <span class="math inline">\(N\)</span> denote the number of dice rolls in our experiment; which is often referred to as the <em>size parameter</em> of our binomial distribution. We’ll also use <span class="math inline">\(\theta\)</span> (theta) to refer to the the probability that a single die comes up skulls, a quantity that is usually called the <em>success probability</em> of the binomial. Finally, we’ll use <span class="math inline">\(X\)</span> to refer to the results of our experiment, namely the number of skulls I get when I roll the dice. Since the actual value of <span class="math inline">\(X\)</span> is due to chance, we refer to it as a <em>random variable</em>. In any case, now that we have all this terminology and notation, we can use it to state the problem a little more precisely. The quantity that we want to calculate is the probability that <span class="math inline">\(X = 4\)</span> given that we know that <span class="math inline">\(\theta = .167\)</span> and <span class="math inline">\(N=20\)</span>. The general “form” of the thing I’m interested in calculating could be written as <span class="math display">\[P(X \ | \ \theta, N)\]</span> (say: the probability of <span class="math inline">\(X\)</span> given <span class="math inline">\(\theta\)</span> and <span class="math inline">\(N\)</span>) and we’re interested in the special case where <span class="math inline">\(X=4\)</span>, <span class="math inline">\(\theta = .167\)</span> and <span class="math inline">\(N=20\)</span>. There’s only one more piece of notation I want to refer to before moving on to discuss the solution to the problem. If I want to say that <span class="math inline">\(X\)</span> is generated randomly from a binomial distribution with parameters <span class="math inline">\(\theta\)</span> and <span class="math inline">\(N\)</span>, the notation I would use is as follows: <span class="math display">\[X \sim \mbox{Binomial}(\theta, N)\]</span></p>
<p>Yeah, yeah. I know what you’re thinking: notation, notation, notation. Really, who cares? Very few readers of this book are here for the notation, so I should probably move on and talk about how to use the binomial distribution. To that end, Figure <a href="chance.html#fig:4binomial1">4.10</a> plots the binomial probabilities for all possible values of <span class="math inline">\(X\)</span> for our dice rolling experiment, from <span class="math inline">\(X=0\)</span> (no skulls) all the way up to <span class="math inline">\(X=20\)</span> (all skulls). Note that this is basically a bar chart, and is no different to the “pants probability” plot I drew in Figure <a href="chance.html#fig:pantsprob">4.9</a>. On the horizontal axis we have all the possible events, and on the vertical axis we can read off the probability of each of those events. So, the probability of rolling 4 skulls out of 20 times is about 0.20 (the actual answer is 0.2022036, as we’ll see in a moment). In other words, you’d expect that to happen about 20% of the times you repeated this experiment.</p>
<div class="figure"><span id="fig:4binomial1"></span>
<img src="figures/probability/binomSkulls20-eps-converted-to.png" alt="The binomial distribution with size parameter of N =20 and an underlying success probability of 1/6. Each vertical bar depicts the probability of one specific outcome (i.e., one possible value of X). Because this is a probability distribution, each of the probabilities must be a number between 0 and 1, and the heights of the bars must sum to 1 as well." width="1164" />
<p class="caption">
Figure 4.10: The binomial distribution with size parameter of N =20 and an underlying success probability of 1/6. Each vertical bar depicts the probability of one specific outcome (i.e., one possible value of X). Because this is a probability distribution, each of the probabilities must be a number between 0 and 1, and the heights of the bars must sum to 1 as well.
</p>
</div>
</div>
<div id="working-with-the-binomial-distribution-in-r" class="section level3" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Working with the binomial distribution in R</h3>
<p>Although some people find it handy to know the formula <a href="https://en.wikipedia.org/wiki/Binomial_distribution#Probability_mass_function">for calculating probabilities from a binomial distribution</a>, most people just want to know how to use the distributions without worrying too much about the maths. To that end, R has a function called <code>dbinom()</code> that calculates binomial probabilities for us.</p>
<p>The main arguments to the function are:</p>
<ul>
<li><code>x</code>: a number, or vector of numbers, specifying the outcomes whose probability you’re trying to calculate.</li>
<li><code>size</code>: a number telling R the size of the experiment.</li>
<li><code>prob</code>: the success probability for any one trial in the experiment.</li>
</ul>
<p>So, in order to calculate the probability of getting skulls, from an experiment of trials, in which the probability of getting a skull on any one trial is … well, the command I would use is simply this:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="chance.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>( <span class="at">x =</span> <span class="dv">4</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span> )</span></code></pre></div>
<pre><code>## [1] 0.2022036</code></pre>
<p>To give you a feel for how the binomial distribution changes when we alter the values of <span class="math inline">\(\theta\)</span> and <span class="math inline">\(N\)</span>, let’s suppose that instead of rolling dice, I’m actually flipping coins. This time around, my experiment involves flipping a fair coin repeatedly, and the outcome that I’m interested in is the number of heads that I observe. In this scenario, the success probability is now <span class="math inline">\(\theta = 1/2\)</span>. Suppose I were to flip the coin <span class="math inline">\(N=20\)</span> times. In this example, I’ve changed the success probability, but kept the size of the experiment the same. What does this do to our binomial distribution?</p>
<div class="figure"><span id="fig:4binomial2"></span>
<img src="figures/probability/Binomial2.png" alt="Two binomial distributions, involving a scenario in which I'm flipping a fair coin, so the underlying success probability is 1/2. In panel (a), we assume I'm flipping the coin N = 20 times. In panel (b) we assume that the coin is flipped N = 100 times." width="507" />
<p class="caption">
Figure 4.11: Two binomial distributions, involving a scenario in which I’m flipping a fair coin, so the underlying success probability is 1/2. In panel (a), we assume I’m flipping the coin N = 20 times. In panel (b) we assume that the coin is flipped N = 100 times.
</p>
</div>
<p>Well, as Figure <a href="chance.html#fig:4binomial2">4.11</a>a shows, the main effect of this is to shift the whole distribution, as you’d expect. Okay, what if we flipped a coin <span class="math inline">\(N=100\)</span> times? Well, in that case, we get Figure <a href="chance.html#fig:4binomial2">4.11</a>b. The distribution stays roughly in the middle, but there’s a bit more variability in the possible outcomes.</p>
<p>At this point, I should probably explain the name of the <code>dbinom</code> function. Obviously, the “binom” part comes from the fact that we’re working with the binomial distribution, but the “d” prefix is probably a bit of a mystery. In this section I’ll give a partial explanation: specifically, I’ll explain why there is a prefix. As for why it’s a “d” specifically, you’ll have to wait until the next section. What’s going on here is that R actually provides <strong>four</strong> functions in relation to the binomial distribution. These four functions are <code>dbinom</code>, <code>pbinom</code>, <code>rbinom</code> and <code>qbinom</code>, and each one calculates a different quantity of interest. Not only that, R does the same thing for <strong>every</strong> probability distribution that it implements. No matter what distribution you’re talking about, there’s a <code>d</code> function, a <code>p</code> function, <code>r</code> a function and a <code>q</code> function.</p>
<p>Let’s have a look at what all four functions do. Firstly, all four versions of the function require you to specify the <code>size</code> and <code>prob</code> arguments: no matter what you’re trying to get R to calculate, it needs to know what the parameters are. However, they differ in terms of what the other argument is, and what the output is. So let’s look at them one at a time.</p>
<ul>
<li>The <code>d</code> form we’ve already seen: you specify a particular outcome <code>x</code>, and the output is the probability of obtaining exactly that outcome. (the “d” is short for <em>density</em>, but ignore that for now).</li>
<li>The <code>p</code> form calculates the <em>cumulative probability</em>. You specify a particular quantile <code>q</code> , and it tells you the probability of obtaining an outcome <strong>smaller than or equal to</strong> <code>q</code>.</li>
<li>The <code>q</code> form calculates the <em>quantiles</em> of the distribution. You specify a probability value <code>p</code>, and it gives you the corresponding quantile/percentile. That is, the value of the variable for which there’s a probability <code>p</code> of obtaining an outcome lower than that value.</li>
<li>The <code>r</code> form is a <em>random number generator</em>: specifically, it generates <code>n</code> random outcomes from the distribution.</li>
</ul>
<blockquote>
<p>Note: Probably you already know what a quantile is (they’re more commonly called percentiles), but if not: the 10th quantile/percentile of a data set is the smallest number <span class="math inline">\(x\)</span> such that 10% of the data is less than <span class="math inline">\(x\)</span>. In fact, we’ve already come across the idea: the median of a data set is its 50th quantile / percentile!</p>
</blockquote>
<p>This is a little abstract, so let’s look at some concrete examples. Again, we’ve already covered <code>dbinom</code> so let’s focus on the other three versions. We’ll start with <code>pbinom</code>, and we’ll go back to the skull-dice example. Again, I’m rolling 20 dice, and each die has a 1 in 6 chance of coming up skulls. Suppose, however, that I want to know the probability of rolling 4 <strong>or fewer</strong> skulls. If I wanted to, I could use the <code>dbinom</code> function to calculate the exact probability of rolling 0 skulls, 1 skull, 2 skulls, 3 skulls and 4 skulls and then add these up, but there’s a faster way. Instead, I can calculate this using the <code>pbinom</code> function. Here’s the command:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="chance.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="at">q=</span> <span class="dv">4</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.7687492</code></pre>
<p>In other words, there is a 76.9% chance that I will roll 4 or fewer skulls. Or, to put it another way, R is telling us that a value of 4 is actually the 76.9th percentile of this binomial distribution.</p>
<p>Next, let’s consider the <code>qbinom</code> function. Let’s say I want to calculate the 75th percentile of the binomial distribution. If we’re sticking with our skulls example, I would use the following command to do this:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="chance.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="at">p =</span> <span class="fl">0.75</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span> )</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>Hm. There’s something odd going on here. Let’s think this through. What the <code>qbinom</code> function appears to be telling us is that the 75th percentile of the binomial distribution is 4, even though we saw from the function that 4 is <strong>actually</strong> the 76.9th percentile. And it’s definitely the <code>pbinom</code> function that is correct. I promise. The weirdness here comes from the fact that our binomial distribution doesn’t really <strong>have</strong> a 75th percentile. Not really. Why not? Well, there’s a 56.7% chance of rolling 3 or fewer skulls (you can type <code>pbinom(3, 20, 1/6)</code> to confirm this if you want), and a 76.9% chance of rolling 4 or fewer skulls. So there’s a sense in which the 75th percentile should lie “in between” 3 and 4 skulls. But that makes no sense at all! You can’t roll 20 dice and get 3.9 of them come up skulls. This issue can be handled in different ways: you could report an in between value (or <strong>interpolated</strong> value, to use the technical name) like 3.9, you could round down (to 3) or you could round up (to 4).</p>
<p>The <code>qbinom</code> function rounds upwards: if you ask for a percentile that doesn’t actually exist (like the 75th in this example), R finds the smallest value for which the the percentile rank is <strong>at least</strong> what you asked for. In this case, since the “true” 75th percentile (whatever that would mean) lies somewhere between 3 and 4 skulls, R rounds up and gives you an answer of 4. This subtlety is tedious, I admit, but thankfully it’s only an issue for discrete distributions like the binomial. The other distributions that I’ll talk about (normal and <span class="math inline">\(t\)</span>) are continuous, and so R can always return an exact quantile whenever you ask for it.</p>
<p>Finally, we have the random number generator. To use the <code>rbinom</code> function, you specify how many times R should “simulate” the experiment using the <code>n</code> argument, and it will generate random outcomes from the binomial distribution. So, for instance, suppose I were to repeat my die rolling experiment 100 times. I could get R to simulate the results of these experiments by using the following command:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="chance.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="at">n =</span> <span class="dv">100</span>, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span> )</span></code></pre></div>
<pre><code>##   [1] 3 3 6 3 2 5 2 3 3 2 4 2 2 2 3 6 2 4 6 2 2 3 7 6 2 5 2 1 1 2 6 6 3 1 2 4 4
##  [38] 1 2 2 1 3 5 5 5 2 2 1 3 1 4 3 3 3 3 5 4 4 2 3 2 4 4 4 6 4 3 1 3 2 2 1 4 3
##  [75] 3 4 2 2 2 3 3 1 3 4 5 4 3 1 3 1 6 5 4 4 4 5 1 4 4 7</code></pre>
<blockquote>
<p>Note: Since computers are deterministic machines, they can’t actually produce truly random behaviour. Instead, what they do is take advantage of various mathematical functions that share a lot of similarities with true randomness. What this means is that any random numbers generated on a computer are pseudorandom, and the quality of those numbers depends on the specific method used. By default R uses the “Mersenne twister” method. In any case, you can find out more by typing ?Random, but as usual the R help files are fairly dense.</p>
</blockquote>
<p>As you can see, these numbers are pretty much what you’d expect given the distribution shown in Figure <a href="chance.html#fig:4binomial1">4.10</a>. Most of the time I roll somewhere between 1 to 5 skulls. There are a lot of subtleties associated with random number generation using a computer, but for the purposes of this book we don’t need to worry too much about them.</p>
</div>
<div id="norm-dist" class="section level3" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> The normal distribution</h3>
<p>While the binomial distribution is conceptually the simplest distribution to understand, it’s not the most important one. That particular honour goes to the <em>normal distribution</em>, which is also referred to as “the bell curve” or a “Gaussian distribution.”</p>
<div class="figure"><span id="fig:4normal"></span>
<img src="figures/probability/standardNormal-eps-converted-to.png" alt="The normal distribution with mean = 0 and standard deviation = 1. The x-axis corresponds to the value of some variable, and the y-axis tells us something about how likely we are to observe that value. However, notice that the y-axis is labelled Probability Density and not Probability. There is a subtle and somewhat frustrating characteristic of continuous distributions that makes the y axis behave a bit oddly: the height of the curve here isn't actually the probability of observing a particular x value. On the other hand, it is true that the heights of the curve tells you which x values are more likely (the higher ones!)." width="1164" />
<p class="caption">
Figure 4.12: The normal distribution with mean = 0 and standard deviation = 1. The x-axis corresponds to the value of some variable, and the y-axis tells us something about how likely we are to observe that value. However, notice that the y-axis is labelled Probability Density and not Probability. There is a subtle and somewhat frustrating characteristic of continuous distributions that makes the y axis behave a bit oddly: the height of the curve here isn’t actually the probability of observing a particular x value. On the other hand, it is true that the heights of the curve tells you which x values are more likely (the higher ones!).
</p>
</div>
<p>A normal distribution is described using two parameters, the mean of the distribution <span class="math inline">\(\mu\)</span> and the standard deviation of the distribution <span class="math inline">\(\sigma\)</span>. The notation that we sometimes use to say that a variable <span class="math inline">\(X\)</span> is normally distributed is as follows: <span class="math display">\[X \sim \mbox{Normal}(\mu,\sigma)\]</span> Of course, that’s just notation. It doesn’t tell us anything interesting about the normal distribution itself. The mathematical formula for the normal distribution is:</p>
<div class="figure"><span id="fig:4normalformula"></span>
<img src="figures/probability/Normal_formula.png" alt="Formula for the normal distribution" width="268" />
<p class="caption">
Figure 4.13: Formula for the normal distribution
</p>
</div>
<p>The formula is important enough that everyone who learns statistics should at least look at it, but since this is an introductory text I don’t want to focus on it to much. Instead, we look at how R can be used to work with normal distributions. The R functions for the normal distribution are <em>dnorm()</em>, <em>pnorm()</em>, <em>qnorm()</em> and <em>rnorm()</em>. However, they behave in pretty much exactly the same way as the corresponding functions for the binomial distribution, so there’s not a lot that you need to know. The only thing that I should point out is that the argument names for the parameters are <em>mean</em> and <em>sd</em>. In pretty much every other respect, there’s nothing else to add.</p>
<p>Instead of focusing on the maths, let’s try to get a sense for what it means for a variable to be normally distributed. To that end, have a look at Figure <a href="chance.html#fig:4normal">4.12</a>, which plots a normal distribution with mean <span class="math inline">\(\mu = 0\)</span> and standard deviation <span class="math inline">\(\sigma = 1\)</span>. You can see where the name “bell curve” comes from: it looks a bit like a bell. Notice that, unlike the plots that I drew to illustrate the binomial distribution, the picture of the normal distribution in Figure <a href="chance.html#fig:4normal">4.12</a> shows a smooth curve instead of “histogram-like” bars. This isn’t an arbitrary choice: the normal distribution is continuous, whereas the binomial is discrete. For instance, in the die rolling example from the last section, it was possible to get 3 skulls or 4 skulls, but impossible to get 3.9 skulls.</p>
<p>With this in mind, let’s see if we can get an intuition for how the normal distribution works. Firstly, let’s have a look at what happens when we play around with the parameters of the distribution. One parameter we can change is the mean. This will shift the distribution to the right or left. The animation below shows a normal distribution with mean = 0, moving up and down from mean = 0 to mean = 5. Note, when you change the mean the whole shape of the distribution does not change, it just shifts from left to right. In the animation the normal distribution bounces up and down a little, but that’s just a quirk of the animation (plus it looks fun that way).</p>
<div class="figure"><span id="fig:4normalMeanShift"></span>
<img src="figures/gifs/normalMovingMean-1.gif" alt="A normal distribution with a moving mean"  />
<p class="caption">
Figure 4.14: A normal distribution with a moving mean
</p>
</div>
<p>In contrast, if we increase the standard deviation while keeping the mean constant, the peak of the distribution stays in the same place, but the distribution gets wider. The next animation shows what happens when you start with a small standard deviation (sd=0.5), and move to larger and larger standard deviation (up to sd =5). As you can see, the distribution spreads out and becomes wider as the standard deviation increases.</p>
<div class="figure"><span id="fig:4normalSDShift"></span>
<img src="figures/gifs/normalMovingSD-1.gif" alt="A normal distribution with a shifting sd"  />
<p class="caption">
Figure 4.15: A normal distribution with a shifting sd
</p>
</div>
<p>Notice, though, that when we widen the distribution, the height of the peak shrinks. This has to happen: in the same way that the heights of the bars that we used to draw a discrete binomial distribution have to <em>sum</em> to 1, the total <em>area under the curve</em> for the normal distribution must equal 1. Before moving on, I want to point out one important characteristic of the normal distribution. Irrespective of what the actual mean and standard deviation are, approximately 68% of the area falls within 1 standard deviation of the mean (68.3% to be exact). Similarly, approximately 95% of the distribution falls within 2 standard deviations of the mean (95.4% to be exact), and 99.7% of the distribution is within 3 standard deviations. This idea is illustrated in the figure below.</p>
<div class="figure"><span id="fig:sdnorm1a"></span>
<img src="quantrma_files/figure-html/sdnorm1a-1.png" alt="The area under the curve tells you the probability that an observation falls within a particular range. The solid lines plot normal distributions with mean $\mu=0$ and standard deviation $\sigma=1$. The shaded areas illustrate &quot;areas under the curve&quot; for several cases. In the upper left panel we can see there is a 68.3% chance that an observation will fall within one standard deviation of the mean. Next to it we see that there is a 95.4% chance that an observation will fall within two standard deviations of the mean. On the bottom row two more examples of the &quot;area under the curve idea&quot; are given; there is a 15.9% chance that an observation is one standard deviation below the mean or smaller and a 34.1% chance that the observation is greater than one standard deviation below the mean but still below the mean. Notice that if you add these two numbers together you get $15.9 + 34.1 = 50$. For normally distributed data, there is a 50% chance that an observation falls below the mean. And of course that also implies that there is a 50% chance that it falls above the mean." width="100%" />
<p class="caption">
Figure 4.16: The area under the curve tells you the probability that an observation falls within a particular range. The solid lines plot normal distributions with mean <span class="math inline">\(\mu=0\)</span> and standard deviation <span class="math inline">\(\sigma=1\)</span>. The shaded areas illustrate “areas under the curve” for several cases. In the upper left panel we can see there is a 68.3% chance that an observation will fall within one standard deviation of the mean. Next to it we see that there is a 95.4% chance that an observation will fall within two standard deviations of the mean. On the bottom row two more examples of the “area under the curve idea” are given; there is a 15.9% chance that an observation is one standard deviation below the mean or smaller and a 34.1% chance that the observation is greater than one standard deviation below the mean but still below the mean. Notice that if you add these two numbers together you get <span class="math inline">\(15.9 + 34.1 = 50\)</span>. For normally distributed data, there is a 50% chance that an observation falls below the mean. And of course that also implies that there is a 50% chance that it falls above the mean.
</p>
</div>
</div>
<div id="probability-density" class="section level3" number="4.5.4">
<h3><span class="header-section-number">4.5.4</span> Probability density</h3>
<p>There’s something I’ve been trying to hide throughout my discussion of the normal distribution, something that some introductory textbooks omit completely. They might be right to do so: this “thing” that I’m hiding is weird and counterintuitive even by the admittedly distorted standards that apply in statistics. Fortunately, it’s not something that you need to understand at a deep level in order to do basic statistics: rather, it’s something that starts to become important later on when you move beyond the basics. So, if it doesn’t make complete sense, don’t worry: try to make sure that you follow the gist of it.</p>
<p>Throughout my discussion of the normal distribution, there’s been one or two things that don’t quite make sense. Perhaps you noticed that the <span class="math inline">\(y\)</span>-axis in these figures is labelled “Probability Density” rather than density. Maybe you noticed that I used <span class="math inline">\(p(X)\)</span> instead of <span class="math inline">\(P(X)\)</span> when giving the formula for the normal distribution. Maybe you’re wondering why R uses the “d” prefix for functions like <em>dnorm()</em>. And maybe, just maybe, you’ve been playing around with the <em>dnorm()</em> function, and you accidentally typed in a command like this:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="chance.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>( <span class="at">x =</span> <span class="dv">1</span>, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="fl">0.1</span> )</span></code></pre></div>
<pre><code>## [1] 3.989423</code></pre>
<p>And if you’ve done the last part, you’re probably very confused. I’ve asked R to calculate the probability that <em>x = 1</em>, for a normally distributed variable with <em>mean = 1</em> and standard deviation <em>sd = 0.1</em>; and it tells me that the probability is 3.99. But, as we discussed earlier, probabilities <em>can’t</em> be larger than 1. So either I’ve made a mistake, or that’s not a probability.</p>
<p>As it turns out, the second answer is correct. What we’ve calculated here isn’t actually a probability: it’s something else. To understand what that something is, you have to spend a little time thinking about what it really <em>means</em> to say that <span class="math inline">\(X\)</span> is a continuous variable. Let’s say we’re talking about the temperature outside. The thermometer tells me it’s 23 degrees, but I know that’s not really true. It’s not <em>exactly</em> 23 degrees. Maybe it’s 23.1 degrees, I think to myself. But I know that that’s not really true either, because it might actually be 23.09 degrees. But, I know that… well, you get the idea. The tricky thing with genuinely continuous quantities is that you never really know exactly what they are.</p>
<p>Now think about what this implies when we talk about probabilities. Suppose that tomorrow’s maximum temperature is sampled from a normal distribution with mean 23 and standard deviation 1. What’s the probability that the temperature will be <em>exactly</em> 23 degrees? The answer is “zero,” or possibly, “a number so close to zero that it might as well be zero.” Why is this?</p>
<p>It’s like trying to throw a dart at an infinitely small dart board: no matter how good your aim, you’ll never hit it. In real life you’ll never get a value of exactly 23. It’ll always be something like 23.1 or 22.99998 or something. In other words, it’s completely meaningless to talk about the probability that the temperature is exactly 23 degrees. However, in everyday language, if I told you that it was 23 degrees outside and it turned out to be 22.9998 degrees, you probably wouldn’t call me a liar. Because in everyday language, “23 degrees” usually means something like “somewhere between 22.5 and 23.5 degrees.” And while it doesn’t feel very meaningful to ask about the probability that the temperature is exactly 23 degrees, it does seem sensible to ask about the probability that the temperature lies between 22.5 and 23.5, or between 20 and 30, or any other range of temperatures.</p>
<p>The point of this discussion is to make clear that, when we’re talking about continuous distributions, it’s not meaningful to talk about the probability of a specific value. However, what we <em>can</em> talk about is the <strong>probability that the value lies within a particular range of values</strong>. To find out the probability associated with a particular range, what you need to do is calculate the “area under the curve.”</p>
<p>Okay, so that explains part of the story. I’ve explained a little bit about how continuous probability distributions should be interpreted (i.e., area under the curve is the key thing), but I haven’t actually explained what the <em>dnorm()</em> function actually calculates. Equivalently, what does the formula for <span class="math inline">\(p(x)\)</span> that I described earlier actually mean? Obviously, <span class="math inline">\(p(x)\)</span> doesn’t describe a probability, but what is it? The name for this quantity <span class="math inline">\(p(x)\)</span> is a <em>probability density</em>, and in terms of the plots we’ve been drawing, it corresponds to the <em>height</em> of the curve. The densities themselves aren’t meaningful in and of themselves: but they’re “rigged” to ensure that the <em>area</em> under the curve is always interpretable as genuine probabilities. To be honest, that’s about as much as you really need to know for now.</p>
</div>
<div id="other-dist" class="section level3" number="4.5.5">
<h3><span class="header-section-number">4.5.5</span> Other useful distributions</h3>
<p>The normal distribution is the distribution that statistics makes most use of (for reasons to be discussed shortly), and the binomial distribution is a very useful one for lots of purposes. But the world of statistics is filled with probability distributions (like the the <span class="math inline">\(\chi^2\)</span> distribution or the <span class="math inline">\(F\)</span> distribution), some of which we’ll run into in passing. In particular, the <span class="math inline">\(t\)</span> distribution will appear later in this book. I won’t give formulas for the <span class="math inline">\(t\)</span> distribution, or talk about it in too much detail, but I will show you a picture:</p>
<div class="figure"><span id="fig:tdist"></span>
<img src="quantrma_files/figure-html/tdist-1.png" alt="A $t$ distribution with 3 degrees of freedom (solid line)." width="672" />
<p class="caption">
Figure 4.17: A <span class="math inline">\(t\)</span> distribution with 3 degrees of freedom (solid line).
</p>
</div>
<p>A <span class="math inline">\(t\)</span> distribution looks similar to a normal distribution, but it’s not quite the same. For comparison purposes, I’ve plotted a standard normal distribution as the dashed line. Notice that the "tails" of the <span class="math inline">\(t\)</span> distribution are "heavier" (i.e., extend further outwards) than the tails of the normal distribution? That’s the important difference between the two.</p>
</div>
</div>
<div id="zscore" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> z-scores</h2>
<p>We are now in a position to combine some of things we’ve been talking about in this chapter, and introduce you to a new tool: <strong>z-scores</strong>.</p>
<p>It turns out we won’t use z-scores very much in this course. However, you can’t take a class on statistics and not learn about z-scores. The idea behind a z-score is to express your raw data in terms of its standard deviation under the assumption that your data is normally distributed. In a <a href="chance.html#norm-dist">previous section</a> I told you that, regardless of the actual mean and standard deviation of normally distributed data, approximately 68% of the area under a normal distribution falls within 1 standard deviation of the mean and approximately 95% within 2 standard deviations of the mean.</p>
<p>Why is this knowledge useful? Let’s apply it to a concrete example: suppose you scored a 75% on a test. Just receiving a 75% wouldn’t tell you how you did compared to the rest of the class. However, if we assume the grades in your class are normally distributed and I told you that you scored 2 standard deviations above the mean, you’d have a pretty good idea how your score compares to the rest of the class. Most grades, assuming they are distributed normally, fall within 2 standard deviations of the mean (95.4% to be exact), so if you scored 2 standard deviations from the mean, you’ve done better than most students in your class (better than 97.7% of your class to be exact)<a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a>.</p>
<p>To calculate a z-score, all you have to do is figure out how many standard deviations from the mean an observation is. Let’s say the mean score of your class is 65, and the standard deviation is 5. A friend scores a 68. How many standard deviations from the mean is her score?</p>
<p>First compute the difference between her score and the mean:</p>
<p><span class="math inline">\(68 - 65 = 3\)</span></p>
<p>How many standard deviations does 3 represent if 1 standard deviation is 5? Clearly 3 is smaller than 5, so it’s going to be less than 1. To figure it out, just divide 3 by the standard deviation.</p>
<p><span class="math inline">\(z = \frac{3}{5} = 0.60\)</span></p>
<p>Here’s the general formula:</p>
<p><span class="math inline">\(z = \frac{x-\mu}{\sigma}\)</span>, or in English: <span class="math inline">\(z = \frac{\text{raw score} - \text{mean}}{\text{standard deviation}}\)</span></p>
<p>So, for example if we had the following 5 scores from a normal distribution with <span class="math inline">\(\mu = 65\)</span>, and <span class="math inline">\(\sigma = 5\)</span>:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="chance.html#cb26-1" aria-hidden="true" tabindex="-1"></a>scores <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="dv">5</span>,<span class="dv">65</span>,<span class="dv">5</span>),<span class="at">digits=</span><span class="dv">1</span>)</span>
<span id="cb26-2"><a href="chance.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scores)</span></code></pre></div>
<pre><code>## [1] 60.8 71.7 58.4 56.7 62.0</code></pre>
<p>The z-scores would be:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chance.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>((scores<span class="dv">-65</span>)<span class="sc">/</span><span class="dv">5</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] -0.84  1.34 -1.32 -1.66 -0.60</code></pre>
<p>Once you have the z-scores, you could use them as another way to describe your data. For example, now just by looking at a z-score you know if it is likely or unlikely to occur, because you know how the area under the normal curve looks (Figure <a href="chance.html#fig:sdnorm1a">4.16</a>): z-scores between -1 and 1 happen pretty often, scores greater than 1 or -1 still happen fairly often, but not as often. And, scores bigger than 2 or -2 don’t happen very often. This is a convenient thing to do if you want to look at your numbers and get a general sense of how often they happen. We will learn <a href="week-5-estimation-and-sampling-theory.html#clt">next week</a> that many measures can be assumed normally distributed.</p>
<p>You might wonder why we bothered telling you about z-scores, when we won’t use them very much during this course. First, it’s worth knowing they are a thing. Second, they become more important as your statistical prowess becomes more advanced. Third, some statistical concepts, like correlation, can be re-written in terms of z-scores, and this illuminates aspects of those statistics. Finally, they are super useful when you are dealing with a normal distribution that has a known mean and standard deviation.</p>
</div>
<div id="thats-it-for-this-week-3" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> That’s it for this week</h2>
<p>We started this chapter by looking at “the window of chance” and developing an intuition for inferential statistics. Then, we talked about what probability means, and why statisticians can’t agree on what it means. We talked about the rules that probabilities have to obey. And we introduced the idea of a probability distribution, and spent a good chunk talking about some of the more important probability distributions that statisticians work with.</p>
<p>As you’d expect, this coverage is by no means exhaustive. Probability theory is a large branch of mathematics in its own right, entirely separate from its application to statistics and data analysis. As such, there are thousands of books written on the subject and universities generally offer multiple classes devoted entirely to probability theory. Even the “simpler” task of documenting standard probability distributions is a big topic. Fortunately for you, very little of this is necessary. You’re unlikely to need to know dozens of statistical distributions when you go out and do real world data analysis, and you definitely won’t need them for this book, but it never hurts to know that there’s other possibilities out there.</p>
<p>Picking up on that last point, there’s a sense in which this whole chapter is something of a digression. Many undergraduate psychology classes on statistics skim over this content very quickly, and even the more advanced classes will often “forget” to revisit the basic foundations of the field. Most academic psychologists would not know the difference between probability and density, and until recently very few would have been aware of the difference between Bayesian and frequentist probability. However, I think it’s important to understand these things before moving onto the applications. For example, there are a lot of rules about what you’re “allowed” to say when doing statistical inference, and many of these can seem arbitrary and weird. However, they start to make sense if you understand that there is this Bayesian/frequentist distinction. Similarly, in a later chapter, we’re going to talk about something called the <span class="math inline">\(t\)</span>-test, and if you really want to have a grasp of the mechanics of the <span class="math inline">\(t\)</span>-test it really helps to have a sense of what a <span class="math inline">\(t\)</span>-distribution actually looks like.</p>
<p>As a reminder, there are additional practice materials for this week on <a href="https://cloud.sowiso.nl">SOWISO</a>. The materials on SOWISO have a slightly different take on probability theory and show you how to do many of the calculations we did in R by hand.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="13">
<li id="fn13"><p>Mix of Matthew Crump &amp; Danielle Navarro<a href="chance.html#fnref13" class="footnote-back">↩︎</a></p></li>
<li id="fn14"><p>We did something <a href="chcorrelationandcaus.html#corrform">similar last week</a>, but I didn’t show the code.<a href="chance.html#fnref14" class="footnote-back">↩︎</a></p></li>
<li id="fn15"><p>See <a href="https://www.tylervigen.com/spurious-correlations">this website</a> by Tyler Vigen for some interesting spurious correlations. You can even use his website to <a href="https://tylervigen.com/discover">discover a spurious correlation</a> of your own!<a href="chance.html#fnref15" class="footnote-back">↩︎</a></p></li>
<li id="fn16"><p>You can look up the proportions of a normal distribution above/below a given z-score in a <a href="https://www.ztable.net">z-table</a>. Alternatively, you can use the <code>pnorm()</code> function, e.g.: <code>pnorm(2)</code><a href="chance.html#fnref16" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chcorrelationandcaus.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-5-estimation-and-sampling-theory.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
