<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title> 3 Week 3: Correlation and Causation7 | Quantitative Research Methods &amp; Analysis</title>
  <meta name="description" content="An introductory textbook for quantitative research methods and data analysis at EUC. This text was adapted from “Answering questions with data” by Matthew J.C. Crump (https://crumplab.github.io/statistics/)" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content=" 3 Week 3: Correlation and Causation7 | Quantitative Research Methods &amp; Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An introductory textbook for quantitative research methods and data analysis at EUC. This text was adapted from “Answering questions with data” by Matthew J.C. Crump (https://crumplab.github.io/statistics/)" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content=" 3 Week 3: Correlation and Causation7 | Quantitative Research Methods &amp; Analysis" />
  
  <meta name="twitter:description" content="An introductory textbook for quantitative research methods and data analysis at EUC. This text was adapted from “Answering questions with data” by Matthew J.C. Crump (https://crumplab.github.io/statistics/)" />
  

<meta name="author" content="Original Author: Matthew J. C. Crump" />
<meta name="author" content="Chapters 2 and 4 adapted from Danielle Navarro" />
<meta name="author" content="Adapted for EUC by Thomas Hulst and Thanos Kostopoulos" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-2-describing-data-adapted2.html"/>
<link rel="next" href="chance.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">QuantRMA</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#important-notes"><i class="fa fa-check"></i>Important notes</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#attributions"><i class="fa fa-check"></i>Attributions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#cc-by-sa-4.0-license"><i class="fa fa-check"></i>CC BY-SA 4.0 license</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html"><i class="fa fa-check"></i><b>1</b> Week 1: Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#the-curse-of-belief-bias"><i class="fa fa-check"></i><b>1.1</b> The curse of belief bias</a></li>
<li class="chapter" data-level="1.2" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#the-cautionary-tale-of-simpsons-paradox"><i class="fa fa-check"></i><b>1.2</b> The cautionary tale of Simpson’s paradox</a></li>
<li class="chapter" data-level="1.3" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#statistics-in-psychology-psych"><i class="fa fa-check"></i><b>1.3</b> Statistics in psychology</a></li>
<li class="chapter" data-level="1.4" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#statistics-in-everyday-life"><i class="fa fa-check"></i><b>1.4</b> Statistics in everyday life</a></li>
<li class="chapter" data-level="1.5" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#theres-more-to-research-methods-than-statistics"><i class="fa fa-check"></i><b>1.5</b> There’s more to research methods than statistics</a></li>
<li class="chapter" data-level="1.6" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#a-brief-introduction-to-research-methods"><i class="fa fa-check"></i><b>1.6</b> A brief introduction to research methods</a></li>
<li class="chapter" data-level="1.7" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#thoughts-measurement"><i class="fa fa-check"></i><b>1.7</b> Some thoughts about measurement</a></li>
<li class="chapter" data-level="1.8" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#operationalize"><i class="fa fa-check"></i><b>1.8</b> Operationalization: defining your measurement</a></li>
<li class="chapter" data-level="1.9" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#reliab-valid-measurement"><i class="fa fa-check"></i><b>1.9</b> Assessing the reliability and validity of a measurement</a></li>
<li class="chapter" data-level="1.10" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#forms-of-measurement-error"><i class="fa fa-check"></i><b>1.10</b> Forms of measurement error</a></li>
<li class="chapter" data-level="1.11" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#variables"><i class="fa fa-check"></i><b>1.11</b> The role of variables: predictors and outcomes</a></li>
<li class="chapter" data-level="1.12" data-path="week-1-introductionadapted1.html"><a href="week-1-introductionadapted1.html#thats-it-for-this-week"><i class="fa fa-check"></i><b>1.12</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html"><i class="fa fa-check"></i><b>2</b> Week 2: Describing Data</a><ul>
<li class="chapter" data-level="2.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#scales-of-measurement"><i class="fa fa-check"></i><b>2.1</b> Scales of measurement</a><ul>
<li class="chapter" data-level="2.1.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#nominal-scale"><i class="fa fa-check"></i><b>2.1.1</b> Nominal scale</a></li>
<li class="chapter" data-level="2.1.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#ordinal-scale"><i class="fa fa-check"></i><b>2.1.2</b> Ordinal scale</a></li>
<li class="chapter" data-level="2.1.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#interval-scale"><i class="fa fa-check"></i><b>2.1.3</b> Interval scale</a></li>
<li class="chapter" data-level="2.1.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#ratio-scale"><i class="fa fa-check"></i><b>2.1.4</b> Ratio scale</a></li>
<li class="chapter" data-level="2.1.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#continuous-versus-discrete-variables"><i class="fa fa-check"></i><b>2.1.5</b> Continuous versus discrete variables</a></li>
<li class="chapter" data-level="2.1.6" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#some-complexities"><i class="fa fa-check"></i><b>2.1.6</b> Some complexities</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#this-is-what-too-many-numbers-looks-like"><i class="fa fa-check"></i><b>2.2</b> This is what too many numbers looks like</a></li>
<li class="chapter" data-level="2.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#describing-data-using-graphs"><i class="fa fa-check"></i><b>2.3</b> Describing data using graphs</a><ul>
<li class="chapter" data-level="2.3.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#scatterplot"><i class="fa fa-check"></i><b>2.3.1</b> Scatterplot</a></li>
<li class="chapter" data-level="2.3.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#histogram"><i class="fa fa-check"></i><b>2.3.2</b> Histogram</a></li>
<li class="chapter" data-level="2.3.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#other-graphs"><i class="fa fa-check"></i><b>2.3.3</b> Other graphs</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#describing-data-using-numbers"><i class="fa fa-check"></i><b>2.4</b> Describing data using numbers</a></li>
<li class="chapter" data-level="2.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#measures-of-central-tendency-sameness"><i class="fa fa-check"></i><b>2.5</b> Measures of central tendency (sameness)</a><ul>
<li class="chapter" data-level="2.5.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#mode"><i class="fa fa-check"></i><b>2.5.1</b> Mode</a></li>
<li class="chapter" data-level="2.5.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#median"><i class="fa fa-check"></i><b>2.5.2</b> Median</a></li>
<li class="chapter" data-level="2.5.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#mean"><i class="fa fa-check"></i><b>2.5.3</b> Mean</a></li>
<li class="chapter" data-level="2.5.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#what-does-the-mean-mean"><i class="fa fa-check"></i><b>2.5.4</b> What does the mean mean?</a></li>
<li class="chapter" data-level="2.5.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#all-together-now"><i class="fa fa-check"></i><b>2.5.5</b> All together now</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#measures-of-variation-differentness"><i class="fa fa-check"></i><b>2.6</b> Measures of variation (differentness)</a><ul>
<li class="chapter" data-level="2.6.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#the-range"><i class="fa fa-check"></i><b>2.6.1</b> The range</a></li>
<li class="chapter" data-level="2.6.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#difference-scores"><i class="fa fa-check"></i><b>2.6.2</b> Difference scores</a></li>
<li class="chapter" data-level="2.6.3" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#var-form"><i class="fa fa-check"></i><b>2.6.3</b> The variance</a></li>
<li class="chapter" data-level="2.6.4" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#the-standard-deviation"><i class="fa fa-check"></i><b>2.6.4</b> The standard deviation</a></li>
<li class="chapter" data-level="2.6.5" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#closing-thoughts-on-measures-of-variation"><i class="fa fa-check"></i><b>2.6.5</b> Closing thoughts on measures of variation</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#remember-to-look-at-your-data"><i class="fa fa-check"></i><b>2.7</b> Remember to look at your data</a><ul>
<li class="chapter" data-level="2.7.1" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#anscombes-quartet"><i class="fa fa-check"></i><b>2.7.1</b> Anscombe’s Quartet</a></li>
<li class="chapter" data-level="2.7.2" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#datasaurus-dozen"><i class="fa fa-check"></i><b>2.7.2</b> Datasaurus Dozen</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="week-2-describing-data-adapted2.html"><a href="week-2-describing-data-adapted2.html#thats-it-for-this-week-1"><i class="fa fa-check"></i><b>2.8</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html"><i class="fa fa-check"></i><b>3</b> Week 3: Correlation and Causation</a><ul>
<li class="chapter" data-level="3.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#if-something-caused-something-else-to-change-what-would-that-look-like"><i class="fa fa-check"></i><b>3.1</b> If something caused something else to change, what would that look like?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#charlie-and-the-chocolate-factory"><i class="fa fa-check"></i><b>3.1.1</b> Charlie and the chocolate factory</a></li>
<li class="chapter" data-level="3.1.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#positive-negative-or-no-correlation"><i class="fa fa-check"></i><b>3.1.2</b> Positive, negative or no correlation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#pears-r"><i class="fa fa-check"></i><b>3.2</b> Pearson’s <span class="math inline">\(r\)</span></a><ul>
<li class="chapter" data-level="3.2.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#the-idea-of-covariance"><i class="fa fa-check"></i><b>3.2.1</b> The idea of covariance</a></li>
<li class="chapter" data-level="3.2.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#a-measure-of-covariance"><i class="fa fa-check"></i><b>3.2.2</b> A measure of covariance</a></li>
<li class="chapter" data-level="3.2.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#covariance-formalized"><i class="fa fa-check"></i><b>3.2.3</b> Covariance formalized</a></li>
<li class="chapter" data-level="3.2.4" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#corrform"><i class="fa fa-check"></i><b>3.2.4</b> <span class="math inline">\(r\)</span> we there yet?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#examples-of-r-with-data"><i class="fa fa-check"></i><b>3.3</b> Examples of <span class="math inline">\(r\)</span> with data</a></li>
<li class="chapter" data-level="3.4" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#interpreting-correlations"><i class="fa fa-check"></i><b>3.4</b> Interpreting correlations</a><ul>
<li class="chapter" data-level="3.4.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#caus-without-corr"><i class="fa fa-check"></i><b>3.4.1</b> Causation without correlation</a></li>
<li class="chapter" data-level="3.4.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#third-var"><i class="fa fa-check"></i><b>3.4.2</b> Third variables</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#relationships-between-variables"><i class="fa fa-check"></i><b>3.5</b> Relationships between variables</a></li>
<li class="chapter" data-level="3.6" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#establishing-causal-relationships"><i class="fa fa-check"></i><b>3.6</b> Establishing causal relationships</a><ul>
<li class="chapter" data-level="3.6.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#a-frame-of-reference"><i class="fa fa-check"></i><b>3.6.1</b> A frame of reference</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#meaningful-comparisons"><i class="fa fa-check"></i><b>3.7</b> Meaningful comparisons</a><ul>
<li class="chapter" data-level="3.7.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#random"><i class="fa fa-check"></i><b>3.7.1</b> Randomization</a></li>
<li class="chapter" data-level="3.7.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#matching"><i class="fa fa-check"></i><b>3.7.2</b> Matching</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#taxonomy-of-research-design"><i class="fa fa-check"></i><b>3.8</b> Taxonomy of research design</a></li>
<li class="chapter" data-level="3.9" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#range-of-research-design"><i class="fa fa-check"></i><b>3.9</b> Range of research design</a><ul>
<li class="chapter" data-level="3.9.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#experimental-designs"><i class="fa fa-check"></i><b>3.9.1</b> Experimental designs</a></li>
<li class="chapter" data-level="3.9.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#longitudinal-designs"><i class="fa fa-check"></i><b>3.9.2</b> Longitudinal designs</a></li>
<li class="chapter" data-level="3.9.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#cross-sectional-designs"><i class="fa fa-check"></i><b>3.9.3</b> Cross-sectional designs</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#the-validity-of-your-study"><i class="fa fa-check"></i><b>3.10</b> The validity of your study</a><ul>
<li class="chapter" data-level="3.10.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#internal-validity"><i class="fa fa-check"></i><b>3.10.1</b> Internal validity</a></li>
<li class="chapter" data-level="3.10.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#external-validity"><i class="fa fa-check"></i><b>3.10.2</b> External validity</a></li>
<li class="chapter" data-level="3.10.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#construct-validity"><i class="fa fa-check"></i><b>3.10.3</b> Construct validity</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#threats-to-experimental-validity"><i class="fa fa-check"></i><b>3.11</b> Threats to experimental validity</a><ul>
<li class="chapter" data-level="3.11.1" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#history-effects"><i class="fa fa-check"></i><b>3.11.1</b> History effects</a></li>
<li class="chapter" data-level="3.11.2" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#maturation-effects"><i class="fa fa-check"></i><b>3.11.2</b> Maturation effects</a></li>
<li class="chapter" data-level="3.11.3" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#repeated-testing-effects"><i class="fa fa-check"></i><b>3.11.3</b> Repeated testing effects</a></li>
<li class="chapter" data-level="3.11.4" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#selection-bias"><i class="fa fa-check"></i><b>3.11.4</b> Selection bias</a></li>
<li class="chapter" data-level="3.11.5" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#diffatt"><i class="fa fa-check"></i><b>3.11.5</b> Differential attrition</a></li>
<li class="chapter" data-level="3.11.6" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#non-response-bias"><i class="fa fa-check"></i><b>3.11.6</b> Non-response bias</a></li>
<li class="chapter" data-level="3.11.7" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#regression-to-the-mean"><i class="fa fa-check"></i><b>3.11.7</b> Regression to the mean</a></li>
<li class="chapter" data-level="3.11.8" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#experimenter-bias"><i class="fa fa-check"></i><b>3.11.8</b> Experimenter bias</a></li>
<li class="chapter" data-level="3.11.9" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#demand-effects-and-reactivity"><i class="fa fa-check"></i><b>3.11.9</b> Demand effects and reactivity</a></li>
<li class="chapter" data-level="3.11.10" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#placebo-effects"><i class="fa fa-check"></i><b>3.11.10</b> Placebo effects</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="chcorrelationandcaus.html"><a href="chcorrelationandcaus.html#thats-it-for-this-week-2"><i class="fa fa-check"></i><b>3.12</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chance.html"><a href="chance.html"><i class="fa fa-check"></i><b>4</b> Week 4: Chance and Probability Theory</a><ul>
<li class="chapter" data-level="4.1" data-path="chance.html"><a href="chance.html#correlation-and-random-chance"><i class="fa fa-check"></i><b>4.1</b> Correlation and random chance</a><ul>
<li class="chapter" data-level="4.1.1" data-path="chance.html"><a href="chance.html#monte-carlo-simulation-of-random-correlations"><i class="fa fa-check"></i><b>4.1.1</b> Monte-carlo simulation of random correlations</a></li>
<li class="chapter" data-level="4.1.2" data-path="chance.html"><a href="chance.html#increasing-sample-size-decreases-the-opportunity-for-spurious-correlations"><i class="fa fa-check"></i><b>4.1.2</b> Increasing sample-size decreases the opportunity for spurious correlations</a></li>
<li class="chapter" data-level="4.1.3" data-path="chance.html"><a href="chance.html#animation-of-no-relationship-between-variables"><i class="fa fa-check"></i><b>4.1.3</b> Animation of no relationship between variables</a></li>
<li class="chapter" data-level="4.1.4" data-path="chance.html"><a href="chance.html#animation-with-a-relationship-between-variables"><i class="fa fa-check"></i><b>4.1.4</b> Animation with a relationship between variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="chance.html"><a href="chance.html#how-are-probability-and-statistics-different"><i class="fa fa-check"></i><b>4.2</b> How are probability and statistics different?</a></li>
<li class="chapter" data-level="4.3" data-path="chance.html"><a href="chance.html#mean-prob"><i class="fa fa-check"></i><b>4.3</b> What does probability mean?</a><ul>
<li class="chapter" data-level="4.3.1" data-path="chance.html"><a href="chance.html#the-frequentist-view"><i class="fa fa-check"></i><b>4.3.1</b> The frequentist view</a></li>
<li class="chapter" data-level="4.3.2" data-path="chance.html"><a href="chance.html#the-bayesian-view"><i class="fa fa-check"></i><b>4.3.2</b> The Bayesian view</a></li>
<li class="chapter" data-level="4.3.3" data-path="chance.html"><a href="chance.html#whats-the-difference-and-who-is-right"><i class="fa fa-check"></i><b>4.3.3</b> What’s the difference? And who is right?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chance.html"><a href="chance.html#basic-probability-theory"><i class="fa fa-check"></i><b>4.4</b> Basic probability theory</a></li>
<li class="chapter" data-level="4.5" data-path="chance.html"><a href="chance.html#prob-dist"><i class="fa fa-check"></i><b>4.5</b> Probability distributions</a><ul>
<li class="chapter" data-level="4.5.1" data-path="chance.html"><a href="chance.html#the-binomial-distribution"><i class="fa fa-check"></i><b>4.5.1</b> The binomial distribution</a></li>
<li class="chapter" data-level="4.5.2" data-path="chance.html"><a href="chance.html#working-with-the-binomial-distribution-in-r"><i class="fa fa-check"></i><b>4.5.2</b> Working with the binomial distribution in R</a></li>
<li class="chapter" data-level="4.5.3" data-path="chance.html"><a href="chance.html#norm-dist"><i class="fa fa-check"></i><b>4.5.3</b> The normal distribution</a></li>
<li class="chapter" data-level="4.5.4" data-path="chance.html"><a href="chance.html#probability-density"><i class="fa fa-check"></i><b>4.5.4</b> Probability density</a></li>
<li class="chapter" data-level="4.5.5" data-path="chance.html"><a href="chance.html#other-dist"><i class="fa fa-check"></i><b>4.5.5</b> Other useful distributions</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="chance.html"><a href="chance.html#z-scores"><i class="fa fa-check"></i><b>4.6</b> z-scores</a></li>
<li class="chapter" data-level="4.7" data-path="chance.html"><a href="chance.html#thats-it-for-this-week-3"><i class="fa fa-check"></i><b>4.7</b> That’s it for this week</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html"><i class="fa fa-check"></i><b>5</b> Sampling Theory and Estimation</a><ul>
<li class="chapter" data-level="5.1" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#def-pop"><i class="fa fa-check"></i><b>5.1</b> Defining a population</a><ul>
<li class="chapter" data-level="5.1.1" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#simple-random-samples"><i class="fa fa-check"></i><b>5.1.1</b> Simple random samples</a></li>
<li class="chapter" data-level="5.1.2" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#most-samples-are-not-simple-random-samples"><i class="fa fa-check"></i><b>5.1.2</b> Most samples are not simple random samples</a></li>
<li class="chapter" data-level="5.1.3" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><i class="fa fa-check"></i><b>5.1.3</b> How much does it matter if you don’t have a simple random sample?</a></li>
<li class="chapter" data-level="5.1.4" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#population-parameters-and-sample-statistics"><i class="fa fa-check"></i><b>5.1.4</b> Population parameters and sample statistics</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>5.2</b> The law of large numbers</a></li>
<li class="chapter" data-level="5.3" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#sampling-distributions"><i class="fa fa-check"></i><b>5.3</b> Sampling distributions</a><ul>
<li class="chapter" data-level="5.3.1" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#samplingdists"><i class="fa fa-check"></i><b>5.3.1</b> Sampling distribution of the sample mean</a></li>
<li class="chapter" data-level="5.3.2" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#sampling-distributions-exist-for-any-sample-statistic"><i class="fa fa-check"></i><b>5.3.2</b> Sampling distributions exist for any sample statistic</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#clt"><i class="fa fa-check"></i><b>5.4</b> The central limit theorem</a></li>
<li class="chapter" data-level="5.5" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#pointestimates"><i class="fa fa-check"></i><b>5.5</b> Estimating population parameters</a><ul>
<li class="chapter" data-level="5.5.1" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#estimating-the-population-mean"><i class="fa fa-check"></i><b>5.5.1</b> Estimating the population mean</a></li>
<li class="chapter" data-level="5.5.2" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#estimating-the-population-standard-deviation"><i class="fa fa-check"></i><b>5.5.2</b> Estimating the population standard deviation</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#ci"><i class="fa fa-check"></i><b>5.6</b> Estimating a confidence interval</a><ul>
<li class="chapter" data-level="5.6.1" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#a-slight-mistake-in-the-formula"><i class="fa fa-check"></i><b>5.6.1</b> A slight mistake in the formula</a></li>
<li class="chapter" data-level="5.6.2" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>5.6.2</b> Interpreting a confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="sampling-theory-and-estimation.html"><a href="sampling-theory-and-estimation.html#thats-it-for-this-week-4"><i class="fa fa-check"></i><b>5.7</b> That’s it for this week!</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>6</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative Research Methods &amp; Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chcorrelationandcaus" class="section level1">
<h1><span class="header-section-number"> 3</span> Week 3: Correlation and Causation<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a></h1>
<blockquote>
<p>Correlation does not equal causation
—Every Statistics and Research Methods Instructor Ever</p>
</blockquote>
<p>In the last chapter we had some data. It was too much too look at and it didn’t make sense. So, we talked about how to look at the data using graphs and we talked about how to summarize lots of numbers using their central tendencies (sameness) and variability (differentness). If you are looking for a big theme to think about while you take this course, the theme is: how do we ask and answer questions using data? For every section in this book, you should be connecting your inner monologue to this question, and asking yourself: how does what I am learning help me answer questions about data? We know it is easy to forget this stuff when we dive into the details, but we will try to throw you a rope to help you out along the way…</p>
<p>We started last week with some fake data on human happiness, remember? We imagined that we asked a bunch of people to tell us how happy they were, then we looked at the numbers they gave us. Let’s continue with this imaginary thought experiment.</p>
<p>If you ask people to use a number to describe how happy they are, you get a bunch of numbers. What kind of questions can you ask about those numbers? Well, you can look at the numbers and estimate their general properties as we did last week. There are different people, and different people are different amounts of happy. You’ve probably met some of those of really happy people, and really unhappy people, and you yourself probably have some amount of happiness. Before moving on, you should be skeptical of what the numbers might mean. For example, if you force people to give a number between 0-100 to rate their happiness, does this number truly reflect how happy that person is? Can a person know how happy they are? Does the question format bias how they give their answer? Is happiness even a real thing? These are all good questions about the <strong>validity</strong> of the construct (happiness itself) and the <strong>measure</strong> (numbers) you are using to quantify it. For now, though, we will side-step those very important questions, and assume that, happiness is a thing, and our measure of happiness measures something about how happy people are.</p>
<p>OK, after we have measured some happiness, I bet you can think of some interesting questions. For example: what causes happiness to go up or down? If you knew the causes of happiness you could increase your own happiness; or, help people who are unhappy; or, better appreciate why Eeyore from Winnie the Pooh is unhappy; or, present valid scientific arguments that argue against incorrect claims about what causes happiness. A causal theory and understanding of happiness could be used for all of those things, so how can we get there?</p>
<div id="if-something-caused-something-else-to-change-what-would-that-look-like" class="section level2">
<h2><span class="header-section-number">3.1</span> If something caused something else to change, what would that look like?</h2>
<p>Before we go around determining the causes of happiness, we should prepare ourselves with some analytical tools so that we could identify what causation looks like. If we don’t prepare ourselves for what we might find, then we won’t know how to interpret our own data. Instead, we need to anticipate what the data could look like. Specifically, we need to know what data would look like when one thing does not cause another thing, and what data would look like when one thing does cause another thing. This chapter does some of this preparation. Fair warning: we will find out some tricky things. For example, we can find patterns that look like one thing is causing another, even when that one thing DOES NOT CAUSE the other thing. Hang in there.</p>
<div id="charlie-and-the-chocolate-factory" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Charlie and the chocolate factory</h3>
<p>Let’s imagine that a person’s supply of chocolate has a causal influence on their level of happiness. Let’s further imagine that, like Charlie, the more chocolate you have the more happy you will be, and the less chocolate you have, the less happy you will be. Finally, because we suspect happiness is caused by lots of other things in a person’s life, we anticipate that the relationship between chocolate supply and happiness won’t be perfect. What do these assumptions mean for how the data should look?</p>
<p>Our first step is to collect some imaginary data from 100 people. We walk around and ask the first 100 people we meet to answer two questions:</p>
<ol style="list-style-type: decimal">
<li>how much chocolate do you have, and</li>
<li>how happy are you.</li>
</ol>
<p>For convenience, both the scales will go from 0 to 100. For the chocolate scale, 0 means no chocolate, 100 means lifetime supply of chocolate. Any other number is somewhere in between. For the happiness scale, 0 means no happiness, 100 means all of the happiness, and in between means some amount in between.</p>
<p>Below is how the data was generated in R and in the table you can find the sample data from the first 10 imaginary subjects.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="chcorrelationandcaus.html#cb5-1"></a><span class="co"># create a vector with 100 subjects</span></span>
<span id="cb5-2"><a href="chcorrelationandcaus.html#cb5-2"></a>subject &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">100</span></span>
<span id="cb5-3"><a href="chcorrelationandcaus.html#cb5-3"></a></span>
<span id="cb5-4"><a href="chcorrelationandcaus.html#cb5-4"></a><span class="co"># use a uniform distribution to generate pretend happiness and chocolate</span></span>
<span id="cb5-5"><a href="chcorrelationandcaus.html#cb5-5"></a><span class="co"># variables</span></span>
<span id="cb5-6"><a href="chcorrelationandcaus.html#cb5-6"></a>chocolate &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="kw">runif</span>(<span class="dv">100</span>, <span class="fl">0.5</span>, <span class="dv">1</span>))</span>
<span id="cb5-7"><a href="chcorrelationandcaus.html#cb5-7"></a>happiness &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="kw">runif</span>(<span class="dv">100</span>, <span class="fl">0.5</span>, <span class="dv">1</span>))</span>
<span id="cb5-8"><a href="chcorrelationandcaus.html#cb5-8"></a></span>
<span id="cb5-9"><a href="chcorrelationandcaus.html#cb5-9"></a><span class="co"># put all variables in a dataframe</span></span>
<span id="cb5-10"><a href="chcorrelationandcaus.html#cb5-10"></a>df_charlie &lt;-<span class="st"> </span><span class="kw">data.frame</span>(subject, chocolate, happiness)</span>
<span id="cb5-11"><a href="chcorrelationandcaus.html#cb5-11"></a></span>
<span id="cb5-12"><a href="chcorrelationandcaus.html#cb5-12"></a><span class="co"># show only the first 10 rows of the main dataframe</span></span>
<span id="cb5-13"><a href="chcorrelationandcaus.html#cb5-13"></a>df_charlie_short &lt;-<span class="st"> </span>df_charlie[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">subject</th>
<th align="right">chocolate</th>
<th align="right">happiness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">1</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">2</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">3</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">4</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">5</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">4</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">6</td>
<td align="right">5</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">5</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">10</td>
<td align="right">6</td>
</tr>
</tbody>
</table>
<p>We asked each subject two questions so there are two scores for each subject, one for their chocolate supply, and one for their level of happiness. You might already notice some relationships between amount of chocolate and level of happiness in the table. To make those relationships even more clear, let’s plot all of the data in a graph.</p>
<p>When you have two variables worth of data, you can turn the data into a scatterplot where you get to choose which variable goes on which axis. Let’s put chocolate supply on the x-axis, and happiness level on the y-axis.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="chcorrelationandcaus.html#cb6-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="chcorrelationandcaus.html#cb6-2"></a><span class="kw">ggplot</span>(df_charlie,<span class="kw">aes</span>(<span class="dt">x=</span>chocolate,<span class="dt">y=</span>happiness))<span class="op">+</span></span>
<span id="cb6-3"><a href="chcorrelationandcaus.html#cb6-3"></a><span class="st">  </span><span class="kw">geom_point</span>()<span class="op">+</span></span>
<span id="cb6-4"><a href="chcorrelationandcaus.html#cb6-4"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span id="fig:3scatter1"></span>
<img src="quantrma_files/figure-html/3scatter1-1.png" alt="Imaginary data showing a positive relationship between amount of chocolate and amount happiness" width="672" />
<p class="caption">
Figure 3.1: Imaginary data showing a positive relationship between amount of chocolate and amount happiness
</p>
</div>
<p>What do the dots mean? Each dot has two coordinates, an x-coordinate for chocolate, and a y-coordinate for happiness. The first dot, all the way on the bottom left is the first subject in the table, who had close to 0 chocolate and close to zero happiness. You can look at any dot and draw a straight line down to the x-axis: that will tell you how much chocolate that subject has. When you draw a straight line left to the y-axis for the same dot it will tell you how much happiness that particular subject has.</p>
<p>Now that we are looking at the scatterplot, we can clearly see that the dots show a relationship between chocolate supply and happiness. Happiness is lower for people with smaller supplies of chocolate, and higher for people with larger supplies of chocolate. It looks like the more chocolate you have the happier you will be, and vice-versa. This kind of relationship is called a positive relationship or <strong>positive correlation</strong>.</p>
</div>
<div id="positive-negative-or-no-correlation" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Positive, negative or no correlation</h3>
<p>Seeing as we are in the business of imagining data, let’s imagine some more. We’ve already seen what data looks like if larger chocolate supplies increase happiness. What do you imagine the scatterplot would look like if the relationship was reversed, and larger chocolate supplies decreased happiness? Or, what do you imagine the scatter plot would look like if there was no relationship, and the amount of chocolate that you have doesn’t do anything to your happiness? We invite your imagination to look at these graphs:</p>
<div class="figure"><span id="fig:3posnegrand"></span>
<img src="quantrma_files/figure-html/3posnegrand-1.png" alt="Three scatterplots showing negative, positive, and zero correlation" width="672" />
<p class="caption">
Figure 3.2: Three scatterplots showing negative, positive, and zero correlation
</p>
</div>
<p>The first panel shows a <strong>negative correlation</strong>. Happiness goes down as chocolate supply increases. Negative correlation occurs when one thing goes up and the other thing goes down; or, when more of X is less of Y, and vice-versa. The second panel shows a <strong>positive correlation</strong>. Happiness goes up as chocolate as chocolate supply increases. Positive correlation occurs when both things go up together, and go down together: more of X is more of Y, and vice-versa. The third panel shows <strong>no correlation</strong>. Here, there doesn’t appear to be any obvious relationship between chocolate supply and happiness. The dots are scattered all over the place, the truest of the scatterplots<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a>. Zero correlation occurs when one thing is not related in any way to another things: changes in X do not relate to any changes in Y, and vice-versa.</p>
</div>
</div>
<div id="pears-r" class="section level2">
<h2><span class="header-section-number">3.2</span> Pearson’s <span class="math inline">\(r\)</span></h2>
<p>If Beyoncé was a statistician, she might look at these scatterplots and want to “put a number on it”. We think this is a good idea too. We’ve already learned how to create descriptive statistics for a single measure, like chocolate, or happiness (i.e., means, variances, etc.). A descriptive statistic that summarizes the relationship between two measures, all in one number, was invented by Karl Pearson<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a>. Everyone now calls it: “Pearson’s <span class="math inline">\(r\)</span>”.</p>
<blockquote>
<p>Karl Pearson was a big-wig editor at Biometrika in the 1930s and all around horrible person. He took a hating to another big-wig statistician, Sir Ronald Fisher (who we learn about later, but was also generally a horrible person), and they had some fights about statistics… Seen as the founding fathers of modern statistics, both Pearson and Fisher held deeply racist views and actively contributed to the field of eugenics. You can read more about the troubled history of modern statistics in <a href="https://statmodeling.stat.columbia.edu/2020/08/01/ra-fisher-and-the-science-of-hatred/">many</a>, <a href="https://www.bayesianspectacles.org/karl-pearsons-worst-quotation/">many</a> different <a href="https://njoselson.github.io/Fisher-Pearson/">places</a>. For now, we will focus about how different statistics work and how to use statistics (for good, hopefully), but it’s important to keep this troubled history in mind.</p>
</blockquote>
<p>How does Pearson’s <span class="math inline">\(r\)</span> work? Let’s look again at the first 10 subjects in our fake experiment:</p>
<table>
<thead>
<tr class="header">
<th align="left">subject</th>
<th align="left">chocolate</th>
<th align="left">happiness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">1</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">2</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">3</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">4</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">5</td>
<td align="left">4</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="left">4</td>
<td align="left">7</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left">6</td>
<td align="left">5</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="left">5</td>
<td align="left">7</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">10</td>
<td align="left">6</td>
</tr>
<tr class="odd">
<td align="left">Sums</td>
<td align="left">41</td>
<td align="left">42</td>
</tr>
<tr class="even">
<td align="left">Means</td>
<td align="left">4.1</td>
<td align="left">4.2</td>
</tr>
</tbody>
</table>
<p>What could we do to these numbers to produce a single summary value that represents the relationship between the chocolate supply and happiness?</p>
<div id="the-idea-of-covariance" class="section level3">
<h3><span class="header-section-number">3.2.1</span> The idea of covariance</h3>
<p>“Oh please no, don’t use the word variance again”. Yes, we’re doing it, we’re going to use the word variance again, and again, and again, until it starts making sense. Remember: variance tells us something about the differentness of a measure. In this example, we can see that there is variance in chocolate supply across the 10 subjects and that there is variance in happiness across the 10 subjects. In the scatterplot we saw that as happiness increases, chocolate supply increases (a positive relationship).</p>
<p>What does this have to do with variance? Well, it means there is a relationship between the variance in chocolate supply, and the variance in happiness levels. In other words: the two measures vary together. When we have two measures that vary together, they are like a happy couple who share their variance. This is what covariance refers to: the idea that the pattern of varying numbers in one measure is shared by the pattern of varying numbers in another measure.</p>
<p><strong>Covariance</strong> is <strong>very, very, very, very</strong> important. We suspect that the word covariance is initially confusing, especially if you are not yet fully comfortable with the meaning of variance for a single measure. Nevertheless, we must proceed and use the idea of covariance over and over again to firmly implant it into your statistical mind (we already said, but redundancy works, it’s a thing).</p>
<blockquote>
<p>Note: A <a href="https://en.wikipedia.org/wiki/Three-legged_race">three-legged race</a> can be seen as a metaphor for covariance. Two people tie one leg to each other, then try to walk. It works when they co-vary their legs together (positive relationship). They can also co-vary in an unhelpful way, when one person tries to move forward exactly when the other person tries to move backward. This is still covariance (negative relationship). Funny random walking happens when there is no covariance. This means one person does whatever they want, and so does the other person. There is a lot of variance, but the variance is shared randomly, so it’s just a bunch of legs moving around accomplishing nothing.</p>
</blockquote>
<blockquote>
<p>Note #2: Succesfully playing <a href="https://en.wikipedia.org/wiki/Pat-a-cake,_pat-a-cake,_baker%27s_man#Game">pattycake</a> occurs when two people coordinate their actions so they have postively shared covariance.</p>
</blockquote>
</div>
<div id="a-measure-of-covariance" class="section level3">
<h3><span class="header-section-number">3.2.2</span> A measure of covariance</h3>
<p>“OK, so you are saying that covariance is just another word for the association or relationship between two measures. I suppose we could use some way to measure that.”</p>
<p>Back to our table…notice anything new?</p>
<table>
<thead>
<tr class="header">
<th align="left">subject</th>
<th align="left">chocolate</th>
<th align="left">happiness</th>
<th align="left">chocolate_X_happiness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">1</td>
<td align="left">2</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">2</td>
<td align="left">3</td>
<td align="left">6</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="left">6</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">4</td>
<td align="left">5</td>
<td align="left">20</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">5</td>
<td align="left">4</td>
<td align="left">20</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="left">4</td>
<td align="left">7</td>
<td align="left">28</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left">6</td>
<td align="left">5</td>
<td align="left">30</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="left">5</td>
<td align="left">7</td>
<td align="left">35</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">10</td>
<td align="left">6</td>
<td align="left">60</td>
</tr>
<tr class="odd">
<td align="left">Sums</td>
<td align="left">41</td>
<td align="left">42</td>
<td align="left">208</td>
</tr>
<tr class="even">
<td align="left">Means</td>
<td align="left">4.1</td>
<td align="left">4.2</td>
<td align="left">20.8</td>
</tr>
</tbody>
</table>
<p>We’ve added a new column called “chocolate_X_happiness”, which stands for chocolate scores multiplied by happiness scores. Each row in the new column is the product, or multiplication, of the chocolate and happiness score for that row. Why would we want to do this?</p>
<p>Last chapter we took you back to elementary school and had you think about division. Now it’s time to do the same thing with multiplication. One number times another, means taking the first number, and adding it as many times as the second says to do,</p>
<p><span class="math inline">\(2*2= 2+2=4\)</span></p>
<p><span class="math inline">\(2*6= 2+2+2+2+2+2 = 12\)</span>, or <span class="math inline">\(6+6=12\)</span>, same thing.</p>
<p>You know all that. All we have to think about next are the consequences of multiplying sets of numbers together. For example, what happens when you multiply two small numbers together, compared to multiplying two big numbers together? The first product should be smaller than the second product right? How about things like multiplying a small number by a big number? Those products should be in between, right?</p>
<p>The next step is to think about how the products of two measures sum together, depending on how they line up. Let’s look at another table:</p>
<table>
<thead>
<tr class="header">
<th align="left">scores</th>
<th align="left">X</th>
<th align="left">Y</th>
<th align="left">A</th>
<th align="left">B</th>
<th align="left">XY</th>
<th align="left">AB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">10</td>
<td align="left">1</td>
<td align="left">10</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">2</td>
<td align="left">2</td>
<td align="left">2</td>
<td align="left">9</td>
<td align="left">4</td>
<td align="left">18</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">3</td>
<td align="left">3</td>
<td align="left">3</td>
<td align="left">8</td>
<td align="left">9</td>
<td align="left">24</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">4</td>
<td align="left">4</td>
<td align="left">4</td>
<td align="left">7</td>
<td align="left">16</td>
<td align="left">28</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">5</td>
<td align="left">5</td>
<td align="left">5</td>
<td align="left">6</td>
<td align="left">25</td>
<td align="left">30</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">6</td>
<td align="left">6</td>
<td align="left">6</td>
<td align="left">5</td>
<td align="left">36</td>
<td align="left">30</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="left">7</td>
<td align="left">7</td>
<td align="left">7</td>
<td align="left">4</td>
<td align="left">49</td>
<td align="left">28</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left">8</td>
<td align="left">8</td>
<td align="left">8</td>
<td align="left">3</td>
<td align="left">64</td>
<td align="left">24</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="left">9</td>
<td align="left">9</td>
<td align="left">9</td>
<td align="left">2</td>
<td align="left">81</td>
<td align="left">18</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">10</td>
<td align="left">10</td>
<td align="left">10</td>
<td align="left">1</td>
<td align="left">100</td>
<td align="left">10</td>
</tr>
<tr class="odd">
<td align="left">Sums</td>
<td align="left">55</td>
<td align="left">55</td>
<td align="left">55</td>
<td align="left">55</td>
<td align="left">385</td>
<td align="left">220</td>
</tr>
<tr class="even">
<td align="left">Means</td>
<td align="left">5.5</td>
<td align="left">5.5</td>
<td align="left">5.5</td>
<td align="left">5.5</td>
<td align="left">38.5</td>
<td align="left">22</td>
</tr>
</tbody>
</table>
<p>Look at the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> column. The scores for <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> perfectly co-vary. When <span class="math inline">\(X\)</span> is 1, <span class="math inline">\(Y\)</span> is 1; when <span class="math inline">\(X\)</span> is 2, <span class="math inline">\(Y\)</span> is 2, etc. They are perfectly aligned. The scores for <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> also perfectly co-vary, just in the opposite manner. When <span class="math inline">\(A\)</span> is 1, <span class="math inline">\(B\)</span> is 10; when <span class="math inline">\(A\)</span> is 2, <span class="math inline">\(B\)</span> is 9, etc. <span class="math inline">\(B\)</span> is a reversed copy of <span class="math inline">\(A\)</span>.</p>
<p>Now, look at the column <span class="math inline">\(XY\)</span>. These are the products we get when we multiply the values of <span class="math inline">\(X\)</span> across with the values of Y. Also, look at the column <span class="math inline">\(AB\)</span>. These are the products we get when we multiply the values of <span class="math inline">\(A\)</span> across with the values of <span class="math inline">\(B\)</span>. So far so good.</p>
<p>Next, look at the <code>Sums</code> for the <span class="math inline">\(XY\)</span> and <span class="math inline">\(AB\)</span> columns. They are not the same. The sum of the <span class="math inline">\(XY\)</span> products is 385, and the sum of the <span class="math inline">\(AB\)</span> products is 220. For this specific set of data, the numbers 385 and 220 are very important. They represent the biggest possible sum of products (385), and the smallest possible sum of products (220). There is no way of re-ordering the numbers 1 to 10 for <span class="math inline">\(X\)</span>, and the numbers 1 to 10 for <span class="math inline">\(Y\)</span>, that would ever produce larger or smaller numbers. Check this out:</p>
<p><img src="quantrma_files/figure-html/3simsum-1.png" width="672" /></p>
<p>The above graph shows 1000 computer simulations. I convinced my computer to randomly order the numbers 1 to 10 for <span class="math inline">\(X\)</span>, and randomly order the numbers 1 to 10 for <span class="math inline">\(Y\)</span>.
Then, I multiplied <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, and added the products together. I did this 1000 times. The dots show the sum of the products for each simulation. The two red lines show the maximum possible sum (385), and the minimum possible sum (220), for this set of numbers. Notice, how all of the dots are in between the maximum and minimum possible values.</p>
<p>“Who cares?” Well, for these numbers, we have found a way to summarize the covariance between two measures. We know that when the sum of the products is 385, we have found a perfect, positive relationship. We also know that when the sum of the products is 220, we have found a perfect negative relationship. What about the numbers in between? What could we conclude about the relationship if we found the sum of the products to be 350? Well, it’s likely going to be positive, because it’s close to 385, which is perfectly positive. If the sum of the products was 240, the relationship is likely going to be negative, because it’s close to the perfectly negative 220. What about no relationship? Well, that’s going to be in the middle between 220 and 385.</p>
<p>We have just come up with a data-specific summary measure for the relationship between the numbers 1 to 10 in <span class="math inline">\(X\)</span>, and the numbers 1 to 10 in <span class="math inline">\(Y\)</span>: it’s the sum of the products. We know the maximum (385) and minimum values (220), so we can now interpret any product sum for this kind of data with respect to that scale.</p>
<blockquote>
<p>Note: when the relationship between two measures increases in the positive direction, the sum of their products increases to its maximum possible value. This is because the bigger numbers in <span class="math inline">\(X\)</span> will tend to line up with the bigger numbers in <span class="math inline">\(Y\)</span>, creating the biggest possible sum of products. When the relationship between two measures increases in the negative direction, the sum of their products decreases to its minimum possible value. This is because the bigger numbers in <span class="math inline">\(X\)</span> will tend to line up with the smaller numbers in <span class="math inline">\(Y\)</span>, creating the smallest possible sum of products. When there is no correlation, the big numbers in X will be randomly lined up with the big and small numbers in <span class="math inline">\(Y\)</span>, making the sum of the products somewhere in the middle.</p>
</blockquote>
</div>
<div id="covariance-formalized" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Covariance formalized</h3>
<p>We took some time to see what happens when you multiply sets of numbers together. We found that <span class="math inline">\(\text{big*big = bigger}\)</span> and <span class="math inline">\(\text{small*small=still small}\)</span>, and <span class="math inline">\(\text{big*small=in the middle}\)</span>. The purpose of this was to give you some conceptual idea of how the covariance between two measures is reflected in the sum of their products. We did something very straightforward. We just multiplied <span class="math inline">\(X\)</span> with <span class="math inline">\(Y\)</span>, and looked at how the product sums get big and small, as <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> co-vary in different ways.</p>
<p>Now, we can get a little bit more formal. In statistics, <strong>covariance</strong> is not just the straight multiplication of values in <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. Instead, it’s the multiplication of the deviations in <span class="math inline">\(X\)</span> from the mean of <span class="math inline">\(X\)</span>, and the deviation in <span class="math inline">\(Y\)</span> from the mean of <span class="math inline">\(Y\)</span>. Remember those difference scores from the mean we talked about last chapter? They’re coming back to haunt you know, but in a good way, like Casper the friendly ghost.</p>
<p>Let’s see what this look like in a table:</p>
<table>
<thead>
<tr class="header">
<th align="left">subject</th>
<th align="left">chocolate</th>
<th align="left">happiness</th>
<th align="left">c_d</th>
<th align="left">h_d</th>
<th align="left">cd_X_hd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">-3.1</td>
<td align="left">-3.2</td>
<td align="left">9.92</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">1</td>
<td align="left">2</td>
<td align="left">-3.1</td>
<td align="left">-2.2</td>
<td align="left">6.82</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">2</td>
<td align="left">3</td>
<td align="left">-2.1</td>
<td align="left">-1.2</td>
<td align="left">2.52</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="left">-1.1</td>
<td align="left">-2.2</td>
<td align="left">2.42</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">4</td>
<td align="left">5</td>
<td align="left">-0.1</td>
<td align="left">0.8</td>
<td align="left">-0.08</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">5</td>
<td align="left">4</td>
<td align="left">0.9</td>
<td align="left">-0.2</td>
<td align="left">-0.18</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="left">4</td>
<td align="left">7</td>
<td align="left">-0.1</td>
<td align="left">2.8</td>
<td align="left">-0.28</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left">6</td>
<td align="left">5</td>
<td align="left">1.9</td>
<td align="left">0.8</td>
<td align="left">1.52</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="left">5</td>
<td align="left">7</td>
<td align="left">0.9</td>
<td align="left">2.8</td>
<td align="left">2.52</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">10</td>
<td align="left">6</td>
<td align="left">5.9</td>
<td align="left">1.8</td>
<td align="left">10.62</td>
</tr>
<tr class="odd">
<td align="left">Sums</td>
<td align="left">41</td>
<td align="left">42</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">36</td>
</tr>
<tr class="even">
<td align="left">Means</td>
<td align="left">4.1</td>
<td align="left">4.2</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">3.58</td>
</tr>
</tbody>
</table>
<p>We have computed the deviations from the mean for the chocolate scores (column <code>c_d</code>), and the deviations from the mean for the happiness scores (column <code>h_d</code>). Then, we multiplied them together (last column). Finally, you can see the mean of the products listed in the bottom right corner of the table, <strong>the covariance</strong>.</p>
<p>The formula for the covariance is:</p>
<p><span class="math inline">\(cov(X,Y) = \frac{\sum_{i}^{n}(x_{i}-\bar{X})(y_{i}-\bar{Y})}{N}\)</span></p>
<p>These are simply the steps we just took, but in the form of a formula.</p>
<p>OK, so now we have a formal single number to calculate the relationship between two variables. This is great, it’s what we’ve been looking for. However, there is still a problem. Remember when we learned how to compute just the plain old <strong>variance</strong>. We looked at that number, and we didn’t know what to make of it. It was squared, it wasn’t in the same scale as the original data. So, we square rooted the <strong>variance</strong> to produce the <strong>standard deviation</strong>, which gave us a more interpretable number in the range of our data. The <strong>covariance</strong> has a similar problem. When you calculate the covariance as we just did, we don’t know immediately know its scale. Is a 3 big? is a 6 big? is a 100 big? How big or small is this thing?</p>
<p>From our prelude discussion on the idea of covariance, we learned the sum of products between two measures ranges between a maximum and minimum value. The same is true of the covariance. For a given set of data, there is a maximum possible positive value for the covariance (which occurs when there is perfect positive relationship). And, there is a minimum possible negative value for the covariance (which occurs when there is a perfect negative relationship). When there is zero co-variation: zeroes. So, at the very least, when we look at a co-variation statistic, we can see what direction it points, positive or negative. But, we don’t know how big or small it is compared to the maximum or minimum possible value, so we don’t know the relative size, which means we can’t say how strong the relationship is. What to do?</p>
</div>
<div id="corrform" class="section level3">
<h3><span class="header-section-number">3.2.4</span> <span class="math inline">\(r\)</span> we there yet?</h3>
<p>Yes, we are here now. Wouldn’t it be nice if we could force our measure of co-variation to be between -1 and +1?</p>
<p>-1 would be the minimum possible value for a perfect negative association. +1 would be the maximum possible value for a perfect positive association. 0 would mean no association. Everything in between 0 and -1 would be increasingly large negative associations. Everything between 0 and +1 would be increasingly large positive associations. It would be a fantastic, sensible, easy to interpret system. If only we could force the co-variation number to be between -1 and 1. Fortunately, Pearson’s <span class="math inline">\(r\)</span> does precisely this wonderful thing.</p>
<p>Let’s take a look at a formula:</p>
<p><span class="math inline">\(r = \frac{cov(X,Y)}{\sigma_{X}\sigma_{Y}} = \frac{cov(X,Y)}{SD_{X}SD_{Y}}\)</span></p>
<p>We see the symbol <span class="math inline">\(\sigma\)</span> here, that’s more Greek for you. <span class="math inline">\(\sigma\)</span> is often used as a symbol for the standard deviation (SD). If we read out the formula in English, we see that <span class="math inline">\(r\)</span> is the covariance of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, divided by the product of the standard deviation of <span class="math inline">\(X\)</span> and the standard deviation of <span class="math inline">\(Y\)</span>. Dividing the covariance by the product of the standard deviations has the effect of <strong>normalizing</strong> the covariance into the range -1 to 1.</p>
<p>For now, we will call this mathematical magic<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a>. It works, but we don’t have space to tell you why it works right now.</p>
<blockquote>
<p>Note: it’s worth saying that there are loads of different formulas for computing Pearson’s <span class="math inline">\(r\)</span>. You can find them by Googling them. We will probably include more of them here, when we get around to it. However, they all give you the same answer. And, they are all not as pretty as each other. Some of them might even look scary. In other statistics textbook you will often find formulas that are easier to use for calculation purposes. For example, if you only had a pen and paper, you might use one or another formula because it helps you compute the answer faster by hand. To be honest, we are not very interested in teaching you how to plug numbers into formulas. Nowadays you have a computer that you should use for this kind of stuff. So, we are more interested in teaching you what the calculations mean, rather than how to do them. Of course, every week we are showing you how to do the calculations in the labs using computers.</p>
</blockquote>
<p>Does Pearson’s <span class="math inline">\(r\)</span> really stay between -1 and 1 no matter what? It’s true, take a look at the following simulation. Here I randomly ordered the numbers 1 to 10 for an <span class="math inline">\(X\)</span> measure, and did the same for a <span class="math inline">\(Y\)</span> measure. Then, I computed Pearson’s <span class="math inline">\(r\)</span>, and repeated this process 1000 times. As you can see all of the dots are between -1 and 1. Neat huh.</p>
<div class="figure"><span id="fig:3onethousandr"></span>
<img src="quantrma_files/figure-html/3onethousandr-1.png" alt="A simulation of 1000 correlations. Each dot represents the $r$-value for the correlation between an $X$ and $Y$ variable that each contain the numbers 1 to 10 in random orders." width="672" />
<p class="caption">
Figure 3.3: A simulation of 1000 correlations. Each dot represents the <span class="math inline">\(r\)</span>-value for the correlation between an <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variable that each contain the numbers 1 to 10 in random orders.
</p>
</div>
</div>
</div>
<div id="examples-of-r-with-data" class="section level2">
<h2><span class="header-section-number">3.3</span> Examples of <span class="math inline">\(r\)</span> with data</h2>
<p>During the labs you will be shown how to compute correlations in real datasets using software. To give you a brief preview, let’s look at some data from the <a href="http://worldhappiness.report">world happiness report</a> (2018).</p>
<p>This report measured various attitudes across people from different countries over the time period 2006-2017. For example, one question asked about how much freedom people thought they had to make life choices. Another question asked how confident people were in their national government. Here is a scatterplot showing the relationship between these two measures and how to generate that plot in R. Each dot represents a different country in 2017.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="chcorrelationandcaus.html#cb7-1"></a><span class="kw">library</span>(data.table)</span>
<span id="cb7-2"><a href="chcorrelationandcaus.html#cb7-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb7-3"><a href="chcorrelationandcaus.html#cb7-3"></a></span>
<span id="cb7-4"><a href="chcorrelationandcaus.html#cb7-4"></a><span class="co"># import the data</span></span>
<span id="cb7-5"><a href="chcorrelationandcaus.html#cb7-5"></a>whr_data &lt;-<span class="st"> </span><span class="kw">fread</span>(<span class="st">&#39;https://raw.githubusercontent.com/thomashulst/quantrma/master/data/WHR2018.csv&#39;</span>)</span>
<span id="cb7-6"><a href="chcorrelationandcaus.html#cb7-6"></a></span>
<span id="cb7-7"><a href="chcorrelationandcaus.html#cb7-7"></a><span class="co"># select the relevant variables and filter missing data (NA)</span></span>
<span id="cb7-8"><a href="chcorrelationandcaus.html#cb7-8"></a>smaller_df &lt;-<span class="st"> </span>whr_data <span class="op">%&gt;%</span></span>
<span id="cb7-9"><a href="chcorrelationandcaus.html#cb7-9"></a><span class="st">              </span><span class="kw">select</span>(country,</span>
<span id="cb7-10"><a href="chcorrelationandcaus.html#cb7-10"></a>                      <span class="st">`</span><span class="dt">Freedom to make life choices</span><span class="st">`</span>,</span>
<span id="cb7-11"><a href="chcorrelationandcaus.html#cb7-11"></a>                      <span class="st">`</span><span class="dt">Confidence in national government</span><span class="st">`</span>,</span>
<span id="cb7-12"><a href="chcorrelationandcaus.html#cb7-12"></a>                      <span class="st">`</span><span class="dt">year</span><span class="st">`</span>) <span class="op">%&gt;%</span></span>
<span id="cb7-13"><a href="chcorrelationandcaus.html#cb7-13"></a><span class="st">              </span><span class="kw">filter</span>(<span class="st">`</span><span class="dt">year</span><span class="st">`</span> <span class="op">==</span><span class="st"> </span><span class="dv">2017</span>) <span class="op">%&gt;%</span></span>
<span id="cb7-14"><a href="chcorrelationandcaus.html#cb7-14"></a><span class="st">              </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(<span class="st">`</span><span class="dt">Freedom to make life choices</span><span class="st">`</span>),</span>
<span id="cb7-15"><a href="chcorrelationandcaus.html#cb7-15"></a>                      <span class="op">!</span><span class="kw">is.na</span>(<span class="st">`</span><span class="dt">Confidence in national government</span><span class="st">`</span>))</span>
<span id="cb7-16"><a href="chcorrelationandcaus.html#cb7-16"></a></span>
<span id="cb7-17"><a href="chcorrelationandcaus.html#cb7-17"></a><span class="co"># plot the data with best fit line</span></span>
<span id="cb7-18"><a href="chcorrelationandcaus.html#cb7-18"></a><span class="kw">ggplot</span>(smaller_df, <span class="kw">aes</span>(<span class="dt">x=</span><span class="st">`</span><span class="dt">Freedom to make life choices</span><span class="st">`</span>,</span>
<span id="cb7-19"><a href="chcorrelationandcaus.html#cb7-19"></a>                     <span class="dt">y=</span><span class="st">`</span><span class="dt">Confidence in national government</span><span class="st">`</span>))<span class="op">+</span></span>
<span id="cb7-20"><a href="chcorrelationandcaus.html#cb7-20"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha=</span>.<span class="dv">5</span>)<span class="op">+</span></span>
<span id="cb7-21"><a href="chcorrelationandcaus.html#cb7-21"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span>lm, <span class="dt">se=</span><span class="ot">FALSE</span>)<span class="op">+</span></span>
<span id="cb7-22"><a href="chcorrelationandcaus.html#cb7-22"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<div class="figure"><span id="fig:3hsrdata"></span>
<img src="quantrma_files/figure-html/3hsrdata-1.png" alt="Relationship between freedom to make life choices and confidence in national government. Data for the year 2017 from the world happiness report for 2018." width="672" />
<p class="caption">
Figure 3.4: Relationship between freedom to make life choices and confidence in national government. Data for the year 2017 from the world happiness report for 2018.
</p>
</div>
<p>We put a blue line on the scatterplot to visualize the positive relationship. It appears that as “freedom to make life choices goes up”, so to does confidence in national government. It’s a positive correlation.</p>
<p>The actual correlation, as measured by Pearson’s <span class="math inline">\(r\)</span> is:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="chcorrelationandcaus.html#cb8-1"></a><span class="co"># calculate correlation</span></span>
<span id="cb8-2"><a href="chcorrelationandcaus.html#cb8-2"></a><span class="kw">cor</span>(smaller_df<span class="op">$</span><span class="st">`</span><span class="dt">Freedom to make life choices</span><span class="st">`</span>,</span>
<span id="cb8-3"><a href="chcorrelationandcaus.html#cb8-3"></a>    smaller_df<span class="op">$</span><span class="st">`</span><span class="dt">Confidence in national government</span><span class="st">`</span>)</span></code></pre></div>
<pre><code>## [1] 0.4419082</code></pre>
<p>You will do a lot more of this kind of thing during the lab. Looking at the graph you might start to wonder: Does freedom to make life choices cause changes how confident people are in their national government? Our does it work the other way? Does being confident in your national government give you a greater sense of freedom to make life choices? Or, is this just a random relationship that doesn’t mean anything? All good questions. These data do not provide the answers, they just suggest a possible relationship.</p>
</div>
<div id="interpreting-correlations" class="section level2">
<h2><span class="header-section-number">3.4</span> Interpreting correlations</h2>
<p>What does the presence or the absence of a correlation between two measures mean? How should correlations be interpreted? What kind of inferences can be drawn from correlations? These are all very good questions. A first piece of advice is to use caution when interpreting correlations.</p>
<p>Perhaps you have heard that correlation does not equal causation. There are lots of reasons why not. However, before listing some of the reasons, let’s start with a case where we would expect a causal connection between two measurements. Consider buying a <a href="https://en.wikipedia.org/wiki/Dracaena_trifasciata">snake plant</a> for your home. Snake plants are supposed to be easy to take care of because you can mostly ignore them.</p>
<p>Like most plants, snake plants need some water to stay alive. However, they also need just the right amount of water. Imagine an experiment where 1000 snake plants were grown in a house. Each snake plant is given a different amount of water per day, from zero teaspoons of water per day to 1000 teaspoons of water per day. We will assume that water is part of the causal process that allows snake plants to grow. The amount of water given to each snake plant per day is our first measure. Imagine further that every week the experimenter measures snake plant growth, which will be the second measurement. Now, can you imagine for yourself what a scatter plot of weekly snake plant growth by tablespoons of water would look like?</p>
<div id="caus-without-corr" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Causation without correlation</h3>
<p>The first plant given no water at all would have a very hard time and eventually die. It should have the least amount of weekly growth. How about the plants given only a few teaspoons of water per day. This could be just enough water to keep the plants alive, so they will grow a little bit but not a lot. If you are imagining a scatter plot, with each dot being a snake plant, then you should imagine some dots starting in the bottom left hand corner (no water &amp; no plant growth), moving up and to the right (a bit of water, and a bit of growth). As we look at snake plants getting more and more water, we should see more and more plant growth, right? But only up to a point… There’s a likely positive correlation with increasing plant growth as amount of water per day increases. But, what happens when you give snake plants too much water? From personal experience, they tend to die. So, at some point, the dots in the scatter plot will start moving back down again. Snake plants that get way too much water will not grow very well.</p>
<p>The imaginary scatter plot you should be envisioning could have an upside U shape. Going from left to right, the dot’s go up, they reach a maximum, then they go down again reaching a minimum. Computing Pearson’s <span class="math inline">\(r\)</span> for data like this gives you <span class="math inline">\(r\)</span> values close to zero, while the scatter plot could look something like this:</p>
<div class="figure"><span id="fig:3snakeplant"></span>
<img src="quantrma_files/figure-html/3snakeplant-1.png" alt="Illustration of a possible relationship between amount of water and snake plant growth. Growth goes up with water, but eventually goes back down as too much water makes snake plants die." width="672" />
<p class="caption">
Figure 3.5: Illustration of a possible relationship between amount of water and snake plant growth. Growth goes up with water, but eventually goes back down as too much water makes snake plants die.
</p>
</div>
<p>Granted this looks more like an inverted V, than an inverted U, but you get the picture right? There is clearly a relationship between watering and snake plant growth. But, the relationship isn’t in one direction. As a result, when we compute the correlation in terms of Pearson’s r, we get a value very close to 0, suggesting no relationship.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="chcorrelationandcaus.html#cb10-1"></a><span class="kw">cor</span>(growth,water)</span></code></pre></div>
<pre><code>## [1] -0.003107585</code></pre>
<p>What this really means is there is no linear relationship that can be described by a single straight line. When we need lines or curves going in more than one direction, we have a nonlinear relationship.</p>
<p>This example illustrates some conundrums in interpreting correlations. We already know that water is needed for plants to grow, so we are rightly expecting there to be a relationship between our measure of amount of water and plant growth. If we look at the first half of the data we see a positive correlation, if we look at the last half of the data we see a negative correlation, and if we look at all of the data we see no correlation. Yikes. So, even when there is a causal connection between two measures, we won’t necessarily obtain clear evidence of the connection just by computing a correlation coefficient.</p>
<blockquote>
<p>Note: This is one reason why plotting your data is so important. If you see an upside U shape pattern, then a correlation is probably not the best way of analyzing your data.</p>
</blockquote>
</div>
<div id="third-var" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Third variables</h3>
<p>Anybody can correlate any two things that can be quantified and measured. For example, we could find a hundred people, ask them all sorts of questions like:</p>
<ol style="list-style-type: decimal">
<li>how happy are you</li>
<li>how old are you</li>
<li>how tall are you</li>
<li>how much money do you make per year</li>
<li>how long are your eyelashes</li>
<li>how many books have you read in your life</li>
<li>how loud is your inner voice</li>
</ol>
<p>Let’s say we found a positive correlation between yearly salary and happiness.</p>
<blockquote>
<p>Note: we could have just as easily computed the same correlation between happiness and yearly salary.</p>
</blockquote>
<p>If we found a correlation, would you be willing to infer that yearly salary causes happiness? Perhaps it does play a part. But, something like happiness probably has a lot of contributing causes. Money could directly cause some people to be happy. But, more likely, money buys people access to all sorts of things, and some of those things might contribute happiness. These “other” things are called <strong>third</strong> variables. For example, perhaps people living in nicer places in more expensive houses are more happy than people in worse places in cheaper houses. In this scenario, money isn’t causing happiness, it’s the places and houses that money buys. But, even is this were true, people can still be more or less happy in lots of different situations.</p>
<p>A more absurd example comes from the (seemingly) very strong correlation between ice cream sales and shark attacks:</p>
<div class="figure"><span id="fig:3ice-shark"></span>
<img src="quantrma_files/figure-html/3ice-shark-1.png" alt="A relationship between ice cream sales and shark attacks? Data obtained [here](https://bookdown.org/animestina/R_Manchester/#data-sets)." width="672" />
<p class="caption">
Figure 3.6: A relationship between ice cream sales and shark attacks? Data obtained <a href="https://bookdown.org/animestina/R_Manchester/#data-sets">here</a>.
</p>
</div>
<p>If you were to calculate the correlation between ice cream sales and shark attacks you would find a value close to 1. In fact, that’s what I did and I found a correlation of 0.79, indicating a very strong positive relationship between the two variables. Are sharks allergic to ice cream and taking out their frustration on random swimmers-by? Should we ban ice cream in beach towns for public safety reasons? What is going on? Here, as well, the relationship is better explained by a third variable that wasn’t measured: during hot weather people are more likely to buy ice cream and also more likely to go swimming, increasing the overall likelihood of being attacked by a shark.</p>
<p>The lesson here is that a correlation can occur between two measures because of a third variable that is not directly measured. So, just because we find a correlation, does not mean we can conclude anything about a causal connection between two measurements.</p>
</div>
</div>
<div id="relationships-between-variables" class="section level2">
<h2><span class="header-section-number">3.5</span> Relationships between variables</h2>
<p>These ideas lie at the core of empirical research. To enhance our understanding, we will develop an analytical framework which will help us see the various ways three variables might be related to each other.</p>
<p>Causal relationships can occur either directly or indirectly. As the names suggest, a direct causal relationship refers to the un-intervening impact of one variable on another, whereas an indirect causal relationship refers to the intervening impact of one variable on another. For example, the direct causal relationship between salary and happiness can be understood as the intrinsic value of money in one’s level of happiness. In contrast, if it turns out that a salary increase makes people happier because they can consume more, the causal relationship is indirect, since consumption lies in-between <a href="week-1-introductionadapted1.html#variables">the independent and dependent variable</a>. In other words, consumption is an intervening variable. The figures below visualize this idea:</p>
<div class="figure"><span id="fig:3intervening"></span>
<img src="figures/3intervening.png" alt="Direct and indirect relationships between salary and happiness." width="75%" />
<p class="caption">
Figure 3.7: Direct and indirect relationships between salary and happiness.
</p>
</div>
<p>However, things might not be as simple as the figures above suggest. In fact, researchers are usually confronted with a multitude of associations operating at the same time. Think of the example above. What would be the most accurate representation of the association between salary and happiness? Could a direct and indirect effect operate simultaneously? Most likely yes! Could there be several indirect effects operating simultaneously? Again, most likely yes!</p>
<div class="figure"><span id="fig:3directandindirect"></span>
<img src="figures/3directandindirect.png" alt="Simultaneous direct and multiple indirect effects between salary and happiness." width="75%" />
<p class="caption">
Figure 3.8: Simultaneous direct and multiple indirect effects between salary and happiness.
</p>
</div>
<p>Direct and indirect relationships only partially describe what is going on behind the scenes when researchers evaluate hypotheses. In some of your previous courses, you might have encountered the term <strong>alternative explanations</strong>. An alternative explanation is an explanation not accounted for by the researcher (hence alternative) and can bias the conclusions of the study. We will use the term <strong>confounder</strong> to refer to variables that generate alternative explanations.</p>
<p>To better understand the function of confounders and how they differ from intervening variables, we will visualize a simple analytical framework that will allow us to understand the various ways three (or more) variables might be related to each other. We start with the example above and then generalize. What could potentially bias our efforts to estimate the causal relationship between salary and happiness? In other words, what could be a confounder? Let’s think about one’s level of education. If you attend college, you will likely end up with a higher salary. At the same time, the experience of attending college can help you develop certain personality traits, such as resilience and confidence, which in turn might affect happiness. Let’s visualize what we just said:</p>
<div class="figure"><span id="fig:3confounder"></span>
<img src="figures/3confounder.png" alt="College education as a confounder of salary and happiness." width="75%" />
<p class="caption">
Figure 3.9: College education as a confounder of salary and happiness.
</p>
</div>
<p>Notice the difference between the role of college education in this example and the role of consumption in the example prior (Figure <a href="chcorrelationandcaus.html#fig:3intervening">3.7</a>). We should always pay attention to how a third variable <span class="math inline">\(Z\)</span> might relate to the independent variable <span class="math inline">\(X\)</span> (salary) and the dependent variable <span class="math inline">\(Y\)</span> (happiness): if <span class="math inline">\(X\)</span> affects <span class="math inline">\(Z\)</span> which in turn affects <span class="math inline">\(Y\)</span>, <span class="math inline">\(Z\)</span> is an intervening variable and the whole path can be described as an indirect causal relationship. If <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are affected by <span class="math inline">\(Z\)</span>, <span class="math inline">\(Z\)</span> is a confounder and the path can be described as a spurious relationship. Why spurious? Because, if the researcher does not consider whether an individual has attended college education or not, they will mistakenly interpret the observed correlation between salary and happiness as evidence suggesting a causal relationship between the two, where in fact both are driven by something else. Let’s put everything we have discussed so far in an example together. The following diagram represents a direct and indirect causal relationship with a spurious component.</p>
<div class="figure"><span id="fig:3together"></span>
<img src="figures/3together.png" alt="Simultaneous direct and multiple indirect effects between salary and happiness with college education as a confounder." width="75%" />
<p class="caption">
Figure 3.10: Simultaneous direct and multiple indirect effects between salary and happiness with college education as a confounder.
</p>
</div>
<p>As you may have guessed, the more variables we end up including in our conceptual representation of our research, the more complex our diagrams will be. However, the following key ideas remain the same as the researcher should always try to specify:</p>
<ol style="list-style-type: decimal">
<li>whether relationships between variables are presumed to be causal or spurious;</li>
<li>whether causal relationships are expected to be direct or indirect;</li>
<li>the mechanisms (i.e. intervening variables) underlying any indirect causal relationship.</li>
</ol>
<p>Any relationship between two variables will consist of two components: a causal component (the one we try to uncover) and a spurious component (the one we try to eliminate). The value of this exercise rests on our ability to articulate our research question and the most plausible line of explanation: the more accurate our understanding of empirical reality, the more likely it will be to get closer to the true causal relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
</div>
<div id="establishing-causal-relationships" class="section level2">
<h2><span class="header-section-number">3.6</span> Establishing causal relationships</h2>
<p>We will further explore how to establish causal relationships using research design techniques with a motivating example from economics. Economists have long theorized about the importance of human capital on productivity. The widely held belief is that investments in human capital result in productivity growth <span class="citation">(Becker <a href="#ref-becker2009human" role="doc-biblioref">2009</a>)</span>. Suppose we would like to establish this relationship with an empirical study using quantitative methods. Where do we start?</p>
<p>Let’s first unpack the theory posed by economists: “investments in human capital result in productivity growth”. What is meant by human capital? Human capital are basically all personality traits and individual characteristics embodied in the ability to perform labor that produces economic value. For example: your habits, knowledge, social skills, analytical skills, creativity and many more individual characteristics. Then, what is meant by productivity? Productivity reflects the amount of output one unit of input can produce. Since we are talking about humans, productivity can be thought of as labor productivity, or the output of one hour of work.</p>
<p>So far, so good. Since we want to conduct an empirical study on the relationship between human capital and productivity, we need to <a href="week-1-introductionadapted1.html#operationalize">operationalize</a> these concepts to enable measurement of them. Suppose we operationalize human capital with education and productivity with hourly wage. Now, we could investigate an observation like: college graduates enjoy high hourly wages. Can we use this observation to claim a causal relationship between having a college degree (human capital) and hourly wages (productivity)? Clearly not, the observation itself provides no evidence in support of the claim. As long as we do not have a comparative framework in place, we are not able to eliminate alternative explanations of the apparent relationship between having a college degree and earning a high hourly wage.</p>
<div id="a-frame-of-reference" class="section level3">
<h3><span class="header-section-number">3.6.1</span> A frame of reference</h3>
<p>It becomes clear that unless we look at hourly wages of both college and non-college graduates we are not able to say anything about the association between the two: it is the difference in the hourly wages between the two groups that provides evidence regarding the alleged effect of college education on hourly wages.</p>
<p>But we can probably do better than comparing just the two groups. Perhaps, the <em>type</em> of education might portray our effect of interest more accurately. For instance, we could compare hourly wages across college graduates of economics, political science, law, life science and non-college graduates. Our research design will look as follows:</p>
<table>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(X\)</span></th>
<th align="left"><span class="math inline">\(Y\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Economics</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="even">
<td align="left">Political science</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="odd">
<td align="left">Law</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="even">
<td align="left">Life science</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="odd">
<td align="left">Non-college</td>
<td align="left">Hourly wage</td>
</tr>
</tbody>
</table>
<p>We can take this further by looking at productivity growth for different college and non-college graduates. If we understand productivity growth as the rate at which productivity grows over time, or in our example the rate at which hourly wages increase over time, we could track the rate at which hourly wages increase for economics, political science, law, and life science college graduates and compare them with non-college graduates:</p>
<table>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(X\)</span></th>
<th align="left"><span class="math inline">\(Y_1\)</span></th>
<th align="left"><span class="math inline">\(Y_2\)</span></th>
<th align="left"><span class="math inline">\(Y_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Economics</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="even">
<td align="left">Political science</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="odd">
<td align="left">Law</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="even">
<td align="left">Life science</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="odd">
<td align="left">Non-college</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
<td align="left">Hourly wage</td>
</tr>
</tbody>
</table>
<p>Note that time might as well appear in our research design in a slightly different flavor. What if we look at how much the hourly wage of non-college graduates changed after attending college education? In other words, we can compare the hourly wages of the <em>same individuals</em> before and after attending college.</p>
<p>At this point we need to introduce some additional terminology. Let us name the measurement of hourly wages before college education as <strong>pre-test</strong>, the measurement of hourly wages after college education as <strong>post-test</strong> and the act of attending college education as the <strong>intervention</strong>. Our research design will look as follows:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="left">Pre-test (<span class="math inline">\(Y_1\)</span>)</th>
<th align="left">Intervention (<span class="math inline">\(X\)</span>)</th>
<th align="left">Post-test (<span class="math inline">\(Y_2\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group of individuals</td>
<td align="left">Hourly wage</td>
<td align="left">College education</td>
<td align="left">Hourly wage</td>
</tr>
</tbody>
</table>
<p>Of course, we could do the same thing and also keeping track of the type of education. The research design will look as follows:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="left">Pre-test (<span class="math inline">\(Y_1\)</span>)</th>
<th align="left">Intervention (<span class="math inline">\(X\)</span>)</th>
<th align="left">Post-test (<span class="math inline">\(Y_2\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Economics</td>
<td align="left">Hourly wage</td>
<td align="left">College education</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="even">
<td>Political science</td>
<td align="left">Hourly wage</td>
<td align="left">College education</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="odd">
<td>Law</td>
<td align="left">Hourly wage</td>
<td align="left">College education</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="even">
<td>Life science</td>
<td align="left">Hourly wage</td>
<td align="left">College education</td>
<td align="left">Hourly wage</td>
</tr>
<tr class="odd">
<td>Non-college</td>
<td align="left">Hourly wage</td>
<td align="left">College education</td>
<td align="left">Hourly wage</td>
</tr>
</tbody>
</table>
<p>It is of course possible to expand on this and make even larger and more complicated research designs that will allow you to uncover a more detailed effect. Nevertheless, it will always be the case that you have to compare some groups with some other groups. This raises our next important question: under what conditions are comparisons meaningful?</p>
</div>
</div>
<div id="meaningful-comparisons" class="section level2">
<h2><span class="header-section-number">3.7</span> Meaningful comparisons</h2>
<p>Making meaningful comparisons is central to any research design. We must ensure that any comparison allows us to estimate the true causal effect of the relationship that we are interested in. We already know the general condition that would allow for this: alternative explanations must be eliminated.</p>
<p>Alternative explanations are grounded on confounders which are variables affecting both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> (Figure <a href="chcorrelationandcaus.html#fig:3confounder">3.9</a>). In our example: a confounder could have both an impact on an individual’s choice to attend college education (or the type of college education) <strong>and</strong> on the hourly wage. Perhaps, intrinsic motivation for success in life is a driving force behind the decision to enroll in college <strong>and</strong> one’s performance in the labor market (thereby one’s hourly wage). What about family background? It is plausible that well educated parents can support their children financially and through networking opportunities, thereby affecting both enrollment in college education <strong>and</strong> compensation in the labor market. We will discuss two strategies for maximizing the comparability of groups below and they both rely on the same key principle: making sure confounders are not systematically different across groups.</p>
<div id="random" class="section level3">
<h3><span class="header-section-number">3.7.1</span> Randomization</h3>
<p>The simplest and most effective way to ensure the comparability of the groups is to randomly allocate people to different groups. Random assignment of individuals to different groups means that differences with respect to individual background characteristics are random and not systematic. Therefore, if groups are large enough, they should be comparable on both known and unknown factors. For instance, in the binary classification of college and non-college education, random assignment would produce two groups with very similar intrinsic motivation, family background, innate ability and any other factor that might be related to our study. But… can we do such a thing in this particular example? Is random assignment to different educational groups possible? No, it is not! Education is a <strong>choice variable</strong>, thereby it almost by definition correlates with individual characteristics which are by themselves important in the labor market. In fact, it is precisely for this reason that it has proven to be notoriously difficult to estimate the true causal effect of education on hourly wages <span class="citation">(Fuente <a href="#ref-de2011human" role="doc-biblioref">2011</a>; Kampelmann et al. <a href="#ref-kampelmann2018does" role="doc-biblioref">2018</a>)</span>. Economists have spent years developing advanced econometric techniques allowing them to overcome the fact that people are not randomly allocated in different educational groups.</p>
<p>Before we discuss research design techniques for making meaningful comparisons when randomization is not possible, let us first look at an example where randomization is possible. Pharmaceutical companies need to test their products before administering them to the population. They also want to measure the effectiveness and side effects of various types of treatments. In this particular case it is easy, at least from a practical point of view, to randomly allocate people in various groups. The researcher is in full control and can actively manipulate the levels of the independent variable. For example, we could administer treatment A to group A, treatment B to group B and nothing to group C and random allocation will ensure that groups A, B and C are similar in terms of background characteristics that might have an impact on the effectiveness of the treatment. Therefore, through random allocation, we make sure that group differences in the dependent variable <span class="math inline">\(Y\)</span> can be attributed to the treatment and not confounders.</p>
</div>
<div id="matching" class="section level3">
<h3><span class="header-section-number">3.7.2</span> Matching</h3>
<p>How can we meaningfully compare groups when allocation is a matter of individual choice? Through a procedure that by convention is called matching, researchers can deliberately match the characteristics of individuals in one group with those of individuals in another group. For example, we would like to compare hourly wages of college and non-college graduates with similar intrinsic motivation and family backgrounds, if we believe that these two factors are important determinants of hourly wages. Perhaps you can already see why this procedure is inferior to randomization. Even though we might be able to accurately operationalize family background through parents’ income and educational level, it is hard to measure intrinsic motivation. In addition, matching can only eliminate alternative explanations rooted in the confounders that are known to us, but it leaves the door open to confounders not known to us.</p>
</div>
</div>
<div id="taxonomy-of-research-design" class="section level2">
<h2><span class="header-section-number">3.8</span> Taxonomy of research design</h2>
<p>The discussion so far has identified six core elements of research design. In fact, any research design, no matter how simple or complex, will always be some mix of these elements. So, let us summarize what we have seen so far by listing the six dimensions of research design:</p>
<ol style="list-style-type: decimal">
<li><em>The number of groups in the design</em>: designs vary from those with only 2 groups, to those with more. In principle, there is no upper limit to the number of groups a design might contain. However, one should not be willing to increase the level of complexity at the expense of interpretability: the simpler the design, the clearer the interpretation of the results.</li>
<li><em>The number of pre-test measurement phases</em>: designs vary from those with no pre-test (i.e. when measurements are obtained only once) to those with a series of pre-tests aiming to establish pre-existing differences between the groups that are being compared against each other.</li>
<li><em>The number of post-tests measurements</em>: designs need to have at least one post-test (i.e. when measurements are obtained only once) to those with a series of post-tests aiming to distinguish between short- and long-term effects.</li>
<li><em>The method of allocation to groups</em>: designs might employ randomization or matching.</li>
<li><em>The nature of the intervention</em>: in research design language, the terms intervention and independent variable refer to the same thing: the variable that is presumed to be causing changes in the outcome (dependent) variable<a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a>. Interventions can be either active or passive. A pharmaceutical company interested in the effectiveness of a newly developed drug employs an <strong>active intervention</strong>, since they can decide who gets what variation of treatment and randomly allocate people to different groups. A <strong>passive (or naturally occurring) intervention</strong> is when the researcher does not actively control the intervention. For example: the retirement of an individual when we want to study the effect of retirement on depression, or when a local government issues a new policy reform and we want to study its effect on employment rates. Finally, levels of the independent variable can also be (relatively) <strong>fixed attributes</strong>, such as income, education, age or sex.</li>
<li><em>The number of interventions</em>: designs with an intervention can have either one or more interventions. Multiple interventions can be used to elicit the cumulative effect of various treatments.</li>
</ol>
</div>
<div id="range-of-research-design" class="section level2">
<h2><span class="header-section-number">3.9</span> Range of research design</h2>
<p>Now that we have summarized the six building blocks of research design, it is time to explore the combinations of the possibilities created by combining these building blocks. We will focus on three of the most fundamental types of research design: experimental, longitudinal and cross-sectional designs. They are the foundation of more elaborate and complex research designs. They also help us understand the importance and relevance of the six core principles identified before<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a>.</p>
<div id="experimental-designs" class="section level3">
<h3><span class="header-section-number">3.9.1</span> Experimental designs</h3>
<p>The classic version of the experimental design satisfies the following:</p>
<ol style="list-style-type: decimal">
<li>One pre-test measurement of the outcome variable.</li>
<li>Two groups: one group is exposed to the intervention (usually called the experimental group) and one that is not exposed to the intervention (usually called the control group). E.g. the group receiving a new drug is the experimental group.</li>
<li>Random allocation to groups before the pre-test: this implies that only active interventions can be tested through an experimental design.</li>
<li>One intervention (test/treatment).</li>
<li>One post-test measure of the outcome variable.</li>
</ol>
<p>The key feature of experimental research is that the researcher controls all aspects of the study, especially what participants experience during the study. In particular, the researcher manipulates or varies something (<span class="math inline">\(X\)</span>), and then allows the outcome variable (<span class="math inline">\(Y\)</span>) to vary naturally. The idea here is to deliberately vary the something in the world to see if it has any causal effects on the outcome. Moreover, in order to ensure that there’s no chance that something other than the manipulated variable is causing the outcome, everything else is kept constant or in some other way “balanced” to ensure no effect on the results. In practice, it’s almost impossible to think of everything that might have an influence on the outcome of an experiment, much less keep it constant. As we have seen already, the standard solution to this is <a href="chcorrelationandcaus.html#random">randomization</a>: that is, we randomly assign people to different groups, and then give each group a different treatment (i.e., assign them different values of the independent variables). Randomization minimizes, but does not eliminate, the possibility of systematic differences between treatment groups.</p>
<p>Let’s consider a very simple, completely unrealistic and grossly unethical example. Suppose you wanted to find out if smoking causes lung cancer. One way to do this would be to find people who smoke and people who don’t smoke and look to see if smokers have a higher rate of lung cancer. This is not a proper experiment, since the researcher doesn’t have a lot of control over who is and isn’t a smoker. And this really matters: for instance, it might be that people who choose to smoke cigarettes also tend to have poor diets, or maybe they tend to work in asbestos mines, or whatever. The point here is that the groups (smokers and non-smokers) actually differ on lots of things, not just smoking. So, it might be that the higher incidence of lung cancer among smokers is caused by something else, not by smoking per se. In research design terms, these other things (e.g. diet) are confounders.</p>
<p>In the meantime, let’s now consider what a proper experiment might look like. Recall that our concern was that smokers and non-smokers might differ in lots of ways. The solution, as long as you have no ethics, is to control who smokes and who doesn’t. Specifically, if we randomly divide participants into two groups, and force half of them to become smokers, it’s very unlikely that the groups will differ in any respect other than the fact that half of them smoke. That way, if our smoking group gets cancer at a higher rate than the non-smoking group, we can feel pretty confident that (a) smoking does cause cancer and (b) we’re murderers.</p>
<table>
<colgroup>
<col width="9%" />
<col width="10%" />
<col width="14%" />
<col width="24%" />
<col width="15%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Allocation</th>
<th align="left">Group</th>
<th align="left">Pre-test</th>
<th align="left">Intervention (<span class="math inline">\(X\)</span>)</th>
<th align="left">Post-test</th>
<th align="left">Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Random</td>
<td align="left">Experimental</td>
<td align="left"><span class="math inline">\(Y\text{e}_1\)</span></td>
<td align="left">“Treatment” (smoking)</td>
<td align="left"><span class="math inline">\(Y\text{e}_2\)</span></td>
<td align="left">E = <span class="math inline">\(Y\text{e}_2 - Y\text{e}_1\)</span></td>
</tr>
<tr class="even">
<td align="left">Random</td>
<td align="left">Control</td>
<td align="left"><span class="math inline">\(Y\text{c}_1\)</span></td>
<td align="left">“No treatment” (not smoking)</td>
<td align="left"><span class="math inline">\(Y\text{c}_2\)</span></td>
<td align="left">C = <span class="math inline">\(Y\text{c}_2 - Y\text{c}_1\)</span></td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">T = E - C</td>
</tr>
</tbody>
</table>
<p>Data obtained from this experimental design can be analyzed by taking the difference between post-test and pre-test measure in both the experimental and control group. Then, we subtract the rate of change in the control group (C) from the rate of change in the experimental group (E) to calculate the total effect of the intervention (T). If the change in the experimental group is greater than the change in the control group the researcher can attribute this to the impact of the “treatment”, to the extent that randomization was successful and alternative explanations were successfully eliminated.</p>
</div>
<div id="longitudinal-designs" class="section level3">
<h3><span class="header-section-number">3.9.2</span> Longitudinal designs</h3>
<p>The most basic form of the longitudinal design looks as follows:</p>
<ol style="list-style-type: decimal">
<li>One group</li>
<li>One pre-test measurement of the outcome variable</li>
<li>One intervention where everyone receives the treatment (hence one group only)</li>
<li>One post-test measurement of the outcome variable (though normally you see more than one)</li>
</ol>
<table>
<thead>
<tr class="header">
<th align="left">Allocation</th>
<th align="left">Pre-test</th>
<th align="left">Intervention (<span class="math inline">\(X\)</span>)</th>
<th align="left">Post-test</th>
<th align="left">Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Random</td>
<td align="left"><span class="math inline">\(Y\text{pre}\)</span></td>
<td align="left">“Treatment”</td>
<td align="left"><span class="math inline">\(Y\text{post}\)</span></td>
<td align="left"><span class="math inline">\(Y\text{post} - Y\text{pre}\)</span></td>
</tr>
</tbody>
</table>
<p>This design is similar to the classic experimental design without a control group. Data obtained from such a design is analyzed by looking at the difference between post-test and pre-test measurements. The implicit assumption here is that any difference between <span class="math inline">\(Y\text{post}\)</span> and <span class="math inline">\(Y\text{pre}\)</span> is attributed to the treatment. However, the absence of a randomized control group makes it difficult to rule out the possibility that a similar difference would have been observed in the absence of a treatment.</p>
</div>
<div id="cross-sectional-designs" class="section level3">
<h3><span class="header-section-number">3.9.3</span> Cross-sectional designs</h3>
<p>The most basic form of the cross-sectional design satisfies the following:</p>
<ol style="list-style-type: decimal">
<li>There is no intervention, in the sense that variation in the independent variable relies on existing differences between groups.</li>
<li>There is at least one independent variable with at least two categories</li>
<li>The outcome variable is measured only once</li>
<li>There is no random allocation to groups</li>
</ol>
<table>
<thead>
<tr class="header">
<th align="left">Allocation</th>
<th align="left">Group</th>
<th align="left">Pre-test</th>
<th align="left">Intervention (<span class="math inline">\(X\)</span>)</th>
<th align="left">Post-test</th>
<th align="left">Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Non-random</td>
<td align="left">Experimental</td>
<td align="left">none</td>
<td align="left">“Treatment”</td>
<td align="left"><span class="math inline">\(Ye_{post}\)</span></td>
<td align="left">E = <span class="math inline">\(Ye_{post}\)</span></td>
</tr>
<tr class="even">
<td align="left">Non-random</td>
<td align="left">Control</td>
<td align="left">none</td>
<td align="left">“No treatment”</td>
<td align="left"><span class="math inline">\(Yc_{post}\)</span></td>
<td align="left">C = <span class="math inline">\(Yc_{post}\)</span></td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">T = E - C</td>
</tr>
</tbody>
</table>
<p>This research design resembles a classic experimental design without a pre-test, and individuals are not randomly allocated to groups. Data are collected at one point in time only and analyzed by measuring to what extent variation in the independent variable matches the variation in the outcome variable. The absence of random allocation poses certain limitations to our efforts to interpret this association as evidence of causality. To overcome this difficulty, researchers employ a technique called <strong>statistical controls</strong> whereby associations between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are measured by keeping the values of some other relevant factor constant, eliminating it as a source of alternative explanations. Statistical controls, thus, work in a way similar to matching, but are implemented after data have been collected as long as we have access to the necessary information.</p>
<p>The most common example of a cross-sectional design is data obtained through surveys where, for example, individual preferences on certain topics are measured at one point in time. There are many such databases publicly available on the internet and you can easily download the data they provide. The European Social Survey or the General Social Survey in the US are examples of cross-sectional designs. These surveys measure individual preferences on a wide range of sociopolitical values. So, one might be able to estimate the association between gender and political preferences. Since these surveys include questions on education, income and occupation the researcher is also able to statistically control for such factors in their efforts to get closer to the true causal effect of interest.</p>
</div>
</div>
<div id="the-validity-of-your-study" class="section level2">
<h2><span class="header-section-number">3.10</span> The validity of your study</h2>
<p>More than any other thing, a scientist wants their research to be “valid”. We explored validity before, when it referred to the <a href="week-1-introductionadapted1.html#reliab-valid-measurement"><strong>validity of our measurement</strong></a>. Here, we discuss <strong>the validity of a study</strong> or <strong>experimental validity</strong>. The conceptual idea behind experimental validity is very simple: can you trust the results of your study? If not, the study is invalid. However, while it’s easy to state, in practice it’s much harder to check. And in all honesty, there’s no precise, clearly agreed upon notion of what experimental validity actually is. In fact, there’s lots of different kinds of validity, each of which raises it’s own issues, and not all forms of validity are relevant to all studies.</p>
<p>I’m going to talk about three different types:</p>
<ul>
<li>Internal validity</li>
<li>External validity</li>
<li>Construct validity</li>
</ul>
<p>Internal and external validity are really important, since they tie directly to the fundamental question of whether your study really works. Construct validity asks whether you’re measuring what you think you are.</p>
<div id="internal-validity" class="section level3">
<h3><span class="header-section-number">3.10.1</span> Internal validity</h3>
<p><strong>Internal validity</strong> refers to the extent to which you are able draw the correct conclusions about the causal relationships between variables. It’s called “internal” because it refers to the relationships between things “inside” the study. Let’s illustrate the concept with a simple example. Suppose you’re interested in finding out whether a university education makes you write better. To do so, you get a group of first year students, ask them to write a 1000 word essay, and count the number of spelling and grammatical errors they make. Then you find some third-year students, who obviously have had more of a university education than the first-years, and repeat the exercise. And let’s suppose it turns out that the third-year students produce fewer errors. And so you conclude that a university education improves writing skills. Right? Except… the big problem that you have with this experiment is that the third-year students are older, and they’ve had more experience with writing things. So it’s hard to know for sure what the causal relationship is: do older people write better? Or people who have had more writing experience? Or people who have had more education? Which of the above is the true cause of the superior performance of the third-years? Age? Experience? Education? You can’t tell. This is an example of a failure of internal validity, because your study doesn’t properly tease apart the causal relationships between the different variables.</p>
</div>
<div id="external-validity" class="section level3">
<h3><span class="header-section-number">3.10.2</span> External validity</h3>
<p><strong>External validity</strong> relates to the <strong>generalizability</strong> of your findings. That is, to what extent do you expect to see the same pattern of results in “real life” as you saw in your study. To put it a bit more precisely, any study that you do in psychology will involve a fairly specific set of questions or tasks, will occur in a specific environment, and will involve participants that are drawn from a particular subgroup. So, if it turns out that the results don’t actually generalize to people and situations beyond the ones that you studied, then what you’ve got is a lack of external validity.</p>
<p>The classic example of this issue is the fact that a very large proportion of studies in psychology will use undergraduate psychology students as the participants. Obviously, however, the researchers don’t care only about psychology students; they care about people in general. Given that, a study that uses only psych students as participants always carries a risk of lacking external validity. That is, if there’s something “special” about psychology students that makes them different to the general populace in some <em>relevant</em> respect, then we may start worrying about a lack of external validity.</p>
<p>That said, it is absolutely critical to realize that a study that uses only psychology students does not necessarily have a problem with external validity. I’ll talk about this again later, but it’s such a common mistake that I’m going to mention it here. The external validity is threatened by the choice of population if (a) the population from which you sample your participants is very narrow (e.g., psych students), and (b) the narrow population that you sampled from is systematically different from the general population, <em>in some respect that is relevant to the psychological phenomenon that you intend to study</em>. The italicized part is the bit that lots of people forget: it is true that psychology undergraduates differ from the general population in lots of ways, and so a study that uses only psych students <em>may</em> have problems with external validity. However, if those differences aren’t very relevant to the phenomenon that you’re studying, then there’s nothing to worry about. To make this a bit more concrete, here’s two extreme examples:</p>
<ul>
<li>You want to measure “attitudes of the general public towards psychotherapy”, but all of your participants are psychology students. This study would almost certainly have a problem with external validity.</li>
<li>You want to measure the effectiveness of a visual illusion, and your participants are all psychology students. This study is very unlikely to have a problem with external validity.</li>
</ul>
<p>Having just spent the last couple of paragraphs focusing on the choice of participants (since that’s the big issue that everyone tends to worry most about), it’s worth remembering that external validity is a broader concept. The following are also examples of things that might pose a threat to external validity, depending on what kind of study you’re doing:</p>
<ul>
<li>People might answer a “psychology questionnaire” in a manner that doesn’t reflect what they would do in real life.</li>
<li>Your lab experiment on (say) “human learning” has a different structure to the learning problems people face in real life.</li>
</ul>
</div>
<div id="construct-validity" class="section level3">
<h3><span class="header-section-number">3.10.3</span> Construct validity</h3>
<p><strong>Construct validity</strong> is basically a question of whether you’re measuring what you want to be measuring. A measurement has good construct validity if it is actually measuring the correct theoretical construct, and bad construct validity if it doesn’t. To give very simple (if ridiculous) example, suppose I’m trying to investigate the rates with which university students cheat on their exams. And the way I attempt to measure it is by asking the cheating students to stand up in the lecture theatre so that I can count them. When I do this with a class of 300 students, 0 people claim to be cheaters. So I therefore conclude that the proportion of cheaters in my class is 0%. Clearly this is a bit ridiculous. But the point here is not that this is a very deep methodological example, but rather to explain what construct validity is. The problem with my measure is that while I’m trying to measure “the proportion of people who cheat” what I’m actually measuring is “the proportion of people stupid enough to own up to cheating, or bloody minded enough to pretend that they do”. Obviously, these aren’t the same thing! So my study has gone wrong, because my measurement has very poor construct validity.</p>
</div>
</div>
<div id="threats-to-experimental-validity" class="section level2">
<h2><span class="header-section-number">3.11</span> Threats to experimental validity</h2>
<p>If we look at the issue of validity in the most general fashion, the two biggest worries that we have are <em>confounds</em> and <em>artifacts</em>. We have already discussed confounds but let us summarize what we have seen by examining their relationship with artifacts. These two terms are defined in the following way:</p>
<ul>
<li><strong>Confound</strong>: A confound is an additional, often unmeasured variable that turns out to be related to both the predictors and the outcomes. The existence of confounds threatens the internal validity of the study because you can’t tell whether the predictor causes the outcome, or if the confounding variable causes it, etc.</li>
<li><strong>Artifact</strong>: A result is said to be “artifactual” if it only holds in the special situation that you happened to test in your study. The possibility that your result is an artifact describes a threat to your external validity, because it raises the possibility that you can’t generalize your results to the actual population that you care about.</li>
</ul>
<p>As a general rule confounds are a bigger concern for non-experimental studies, precisely because they’re not proper experiments: by definition, you’re leaving lots of things uncontrolled, so there’s a lot of scope for confounds working their way into your study. Experimental research tends to be much less vulnerable to confounds: the more control you have over what happens during the study, the more you can prevent confounds from appearing.</p>
<p>However, there’s always swings and roundabouts, and when we start thinking about artifacts rather than confounds, the shoe is very firmly on the other foot. For the most part, artifactual results tend to be a concern for experimental studies than for non-experimental studies. To see this, it helps to realize that the reason that a lot of studies are non-experimental is precisely because what the researcher is trying to do is examine human behaviour in a more naturalistic context. By working in a more real-world context, you lose experimental control (making yourself vulnerable to confounds) but because you tend to be studying human psychology “in the wild” you reduce the chances of getting an artifactual result. Or, to put it another way, when you take psychology out of the wild and bring it into the lab (which we usually have to do to gain our experimental control), you always run the risk of accidentally studying something different than you wanted to study: which is more or less the definition of an artifact. So, normally there is a tradeoff between internal and external validity: maximizing one comes at the expense of the other.</p>
<p>Be warned though: the above is a rough guide only. It’s absolutely possible to have confounds in an experiment, and to get artifactual results with non-experimental studies. This can happen for all sorts of reasons, not least of which is researcher error. In practice, it’s really hard to think everything through ahead of time, and even very good researchers make mistakes. But other times it’s unavoidable, simply because the researcher has ethics (e.g., see <a href="chcorrelationandcaus.html#diffatt">differential attrition</a> below).</p>
<p>Okay. There’s a sense in which almost any threat to validity can be characterized as a confound or an artifact: they’re pretty vague concepts. So let’s have a look at some of the most common examples…</p>
<div id="history-effects" class="section level3">
<h3><span class="header-section-number">3.11.1</span> History effects</h3>
<p><em>History effects</em> refer to the possibility that specific events may occur during the study itself that might influence the outcomes. For instance, something might happen in between a pre-test and a post-test. Or, in between testing participant 23 and participant 24. Alternatively, it might be that you’re looking at an older study, which was perfectly valid for its time, but the world has changed enough since then that the conclusions are no longer trustworthy. Examples of things that would count as history effects:</p>
<ul>
<li>You’re interested in how people think about risk and uncertainty. You started your data collection in December 2010. But finding participants and collecting data takes time, so you’re still finding new people in February 2011. Unfortunately for you (and even more unfortunately for others), the Queensland (Australia) floods occurred in January 2011, causing billions of dollars of damage and killing many people. Not surprisingly, the people tested in February 2011 express quite different beliefs about handling risk than the people tested in December 2010. Which (if any) of these reflects the “true” beliefs of participants? I think the answer is probably both: the Queensland floods genuinely changed the beliefs of the Australian public, though possibly only temporarily. The key thing here is that the “history” of the people tested in February is quite different to people tested in December.</li>
<li>You’re testing the psychological effects of a new anti-anxiety drug. So what you do is measure anxiety before administering the drug (e.g., by self-report, and taking physiological measures, let’s say), then you administer the drug, and then you take the same measures afterwards. In the middle, however, because your labs are in Los Angeles, there’s an earthquake, which increases the anxiety of the participants.</li>
</ul>
</div>
<div id="maturation-effects" class="section level3">
<h3><span class="header-section-number">3.11.2</span> Maturation effects</h3>
<p>As with history effects, <strong>maturational effects</strong> are fundamentally about change over time. However, maturation effects aren’t in response to specific events. Rather, they relate to how people change on their own over time: we get older, we get tired, we get bored, etc. Some examples of maturation effects:</p>
<ul>
<li>When doing developmental psychology research, you need to be aware that children grow up quite rapidly. So, suppose that you want to find out whether some educational trick helps with vocabulary size among 3 year olds. One thing that you need to be aware of is that the vocabulary size of children that age is growing at an incredible rate (multiple words per day), all on its own. If you design your study without taking this maturational effect into account, then you won’t be able to tell if your educational trick works.</li>
<li>When running a very long experiment in the lab (say, something that goes for 3 hours), it’s very likely that people will begin to get bored and tired, and that this maturational effect will cause performance to decline, regardless of anything else going on in the experiment.</li>
</ul>
</div>
<div id="repeated-testing-effects" class="section level3">
<h3><span class="header-section-number">3.11.3</span> Repeated testing effects</h3>
<p>An important type of history effect is the effect of <strong>repeated testing</strong>. Suppose I want to take two measurements of some psychological construct (e.g., anxiety). One thing I might be worried about is if the first measurement has an effect on the second measurement. In other words, this is a history effect in which the “event” that influences the second measurement is the first measurement itself! This is not at all uncommon. Examples of this include:</p>
<ul>
<li><em>Learning and practice</em>: e.g., “intelligence” at time 2 might appear to go up relative to time 1 because participants learned the general rules of how to solve “intelligence-test-style” questions during the first testing session.</li>
<li><em>Familiarity with the testing situation</em>: e.g., if people are nervous at time 1, this might make performance go down; after sitting through the first testing situation, they might calm down a lot precisely because they’ve seen what the testing looks like.</li>
<li><em>Auxiliary changes caused by testing</em>: e.g., if a questionnaire assessing mood is boring, then mood at measurement at time 2 is more likely to become “bored”, precisely because of the boring measurement made at time 1.</li>
</ul>
</div>
<div id="selection-bias" class="section level3">
<h3><span class="header-section-number">3.11.4</span> Selection bias</h3>
<p><strong>Selection bias</strong> is a pretty broad term. Suppose that you’re running an experiment with two groups of participants, where each group gets a different “treatment”, and you want to see if the different treatments lead to different outcomes. However, suppose that, despite your best efforts, you’ve ended up with a gender imbalance across groups (say, group A has 80% females and group B has 50% females). It might sound like this could never happen, but trust me, it can. This is an example of a selection bias, in which the people “selected into” the two groups have different characteristics. If any of those characteristics turns out to be relevant (say, your treatment works better on females than males) then you’re in a lot of trouble.</p>
<p>Another good example of selection bias is the one we discussed earlier on education and hourly wages. Education is a choice variable since people allocate themselves in different educational groups: the alternative explanation originates to the extent to which factors driving people’s educational choices correlate with their competitiveness in the labor market.</p>
</div>
<div id="diffatt" class="section level3">
<h3><span class="header-section-number">3.11.5</span> Differential attrition</h3>
<p>One quite subtle danger to be aware of is called <strong>differential attrition</strong>, which is a kind of selection bias that is caused by the study itself. Suppose that, for the first time ever in the history of psychology, I manage to find the perfectly balanced and representative sample of people. I start running “Thomas’s incredibly long and tedious experiment” on my perfect sample, but then, because my study is incredibly long and tedious, lots of people start dropping out. I can’t stop this: participants absolutely have the right to stop doing any experiment, any time, for whatever reason they feel like, and as researchers we are morally (and professionally) obliged to remind people that they do have this right. So, suppose that “Thomas’s incredibly long and tedious experiment” has a very high drop out rate. What do you suppose the odds are that this drop out is random? Answer: zero. Almost certainly, the people who remain are more conscientious, more tolerant of boredom etc than those that leave. To the extent that (say) conscientiousness is relevant to the psychological phenomenon that I care about, this attrition can decrease the validity of my results.</p>
<p>When thinking about the effects of differential attrition, it is sometimes helpful to distinguish between two different types. The first is <strong>homogeneous attrition</strong>, in which the attrition effect is the same for all groups, treatments or conditions. In the example I gave above, the differential attrition would be homogeneous if (and only if) the easily bored participants are dropping out of all of the conditions in my experiment at about the same rate. In general, the main effect of homogeneous attrition is likely to be that it makes your sample unrepresentative. As such, the biggest worry that you’ll have is that the generalisability of the results decreases: in other words, you lose external validity.</p>
<p>The second type of differential attrition is <strong>heterogeneous attrition</strong>, in which the attrition effect is different for different groups. This is a much bigger problem: not only do you have to worry about your external validity, you also have to worry about your internal validity too. To see why this is the case, let’s consider a very dumb study in which I want to see if insulting people makes them act in a more obedient way. Why anyone would actually want to study that I don’t know, but let’s suppose I really, deeply cared about this. So, I design my experiment with two conditions. In the “treatment” condition, the experimenter insults the participant and then gives them a questionnaire designed to measure obedience. In the “control” condition, the experimenter engages in a bit of pointless chitchat and then gives them the questionnaire. Leaving aside the questionable scientific merits and dubious ethics of such a study, let’s have a think about what might go wrong here. As a general rule, when someone insults me to my face, I tend to get much less co-operative. So, there’s a pretty good chance that a lot more people are going to drop out of the treatment condition than the control condition. And this drop out isn’t going to be random. The people most likely to drop out would probably be the people who don’t care all that much about the importance of obediently sitting through the experiment. Since the most bloody minded and disobedient people all left the treatment group but not the control group, we’ve introduced a confound: the people who actually took the questionnaire in the treatment group were <em>already</em> more likely to be dutiful and obedient than the people in the control group. In short, in this study insulting people doesn’t make them more obedient: it makes the more disobedient people leave the experiment! The internal validity of this experiment is completely shot.</p>
</div>
<div id="non-response-bias" class="section level3">
<h3><span class="header-section-number">3.11.6</span> Non-response bias</h3>
<p><strong>Non-response bias</strong> is closely related to selection bias and to differential attrition. The simplest version of the problem goes like this. You mail out a survey to 1000 people, and only 300 of them reply. The 300 people who replied are almost certainly not a random subsample. People who respond to surveys are systematically different to people who don’t. This introduces a problem when trying to generalize from those 300 people who replied, to the population at large; since you now have a very non-random sample. The issue of non-response bias is more general than this, though. Among the (say) 300 people that did respond to the survey, you might find that not everyone answers every question. If (say) 80 people chose not to answer one of your questions, does this introduce problems? As always, the answer is maybe. If the question that wasn’t answered was on the last page of the questionnaire, and those 80 surveys were returned with the last page missing, there’s a good chance that the missing data isn’t a big deal: probably the pages just fell off. However, if the question that 80 people didn’t answer was the most confrontational or invasive personal question in the questionnaire, then almost certainly you’ve got a problem. In essence, what you’re dealing with here is what’s called the problem of <strong>missing data</strong>. If the data that is missing was “lost” randomly, then it’s not a big problem. If it’s missing systematically, then it can be a big problem.</p>
</div>
<div id="regression-to-the-mean" class="section level3">
<h3><span class="header-section-number">3.11.7</span> Regression to the mean</h3>
<p><strong>Regression to the mean</strong> is a curious variation on selection bias. It refers to any situation where you select data based on an extreme value on some measure. Because the measure has natural variation, it almost certainly means that when you take a subsequent measurement, that later measurement will be less extreme than the first one, purely by chance.</p>
<p>Here’s an example. Suppose I’m interested in whether a psychology education has an adverse effect on very smart kids. To do this, I find the 20 psych I students with the best high school grades and look at how well they’re doing at university. It turns out that they’re doing a lot better than average, but they’re not topping the class at university, even though they did top their classes at high school. What’s going on? The natural first thought is that this must mean that the psychology classes must be having an adverse effect on those students. However, while that might very well be the explanation, it’s more likely that what you’re seeing is an example of “regression to the mean”. To see how it works, let’s take a moment to think about what is required to get the best mark in a class, regardless of whether that class be at high school or at university. When you’ve got a big class, there are going to be lots of very smart people enrolled. To get the best mark you have to be very smart, work very hard, and be a bit lucky. The exam has to ask just the right questions for your idiosyncratic skills, and you have to not make any dumb mistakes (we all do that sometimes) when answering them. And that’s the thing: intelligence and hard work are transferrable from one class to the next. Luck isn’t. The people who got lucky in high school won’t be the same as the people who get lucky at university. That’s the very definition of “luck”. The consequence of this is that, when you select people at the very extreme values of one measurement (the top 20 students), you’re selecting for hard work, skill and luck. But because the luck doesn’t transfer to the second measurement (only the skill and work), these people will all be expected to drop a little bit when you measure them a second time (at university). So their scores fall back a little bit, back towards everyone else. This is regression to the mean.</p>
<p>Regression to the mean is surprisingly common. For instance, if two very tall people have kids, their children will tend to be taller than average, but not as tall as the parents. The reverse happens with very short parents: two very short parents will tend to have short children, but nevertheless those kids will tend to be taller than the parents. It can also be extremely subtle. For instance, there have been studies done that suggested that people learn better from negative feedback than from positive feedback. However, the way that people tried to show this was to give people positive reinforcement whenever they did good, and negative reinforcement when they did bad. And what you see is that after the positive reinforcement, people tended to do worse; but after the negative reinforcement they tended to do better. But! Notice that there’s a selection bias here: when people do very well, you’re selecting for “high” values, and so you should expect (because of regression to the mean) that performance on the next trial should be worse, regardless of whether reinforcement is given. Similarly, after a bad trial, people will tend to improve all on their own. The apparent superiority of negative feedback is an artifact caused by regression to the mean <span class="citation">(Kahneman and Tversky <a href="#ref-Kahneman1973" role="doc-biblioref">1973</a>)</span>.</p>
</div>
<div id="experimenter-bias" class="section level3">
<h3><span class="header-section-number">3.11.8</span> Experimenter bias</h3>
<p>Experimenter bias can come in multiple forms. The basic idea is that the experimenter, despite the best of intentions, can accidentally end up influencing the results of the experiment by subtly communicating the “right answer” or the “desired behaviour” to the participants. Typically, this occurs because the experimenter has special knowledge that the participant does not – either the right answer to the questions being asked, or knowledge of the expected pattern of performance for the condition that the participant is in, and so on. The classic example of this happening is the case study of “Clever Hans”, which dates back to 1907 <span class="citation">(Pfungst <a href="#ref-Pfungst1911" role="doc-biblioref">1911</a>; Hothersall <a href="#ref-Hothersall2004" role="doc-biblioref">2004</a>)</span>. Clever Hans was a horse that apparently was able to read and count, and perform other human like feats of intelligence. After Clever Hans became famous, psychologists started examining his behaviour more closely. It turned out that – not surprisingly – Hans didn’t know how to do maths. Rather, Hans was responding to the human observers around him. Because they did know how to count, and the horse had learned to change its behaviour when people changed theirs.</p>
<p>The general solution to the problem of experimenter bias is to engage in double blind studies, where neither the experimenter nor the participant knows which condition the participant is in, or knows what the desired behaviour is. This provides a very good solution to the problem, but it’s important to recognize that it’s not quite ideal, and hard to pull off perfectly. For instance, the obvious way that I could try to construct a double blind study is to have one of my Ph.D. students (one who doesn’t know anything about the experiment) run the study. That feels like it should be enough. The only person (me) who knows all the details (e.g., correct answers to the questions, assignments of participants to conditions) has no interaction with the participants, and the person who does all the talking to people (the Ph.D. student) doesn’t know anything. Except, that last part is very unlikely to be true. In order for the Ph.D. student to run the study effectively, they need to have been briefed by me, the researcher. And, as it happens, the Ph.D. student also knows me, and knows a bit about my general beliefs about people and psychology (e.g., I tend to think humans are much smarter than psychologists give them credit for). As a result of all this, it’s almost impossible for the experimenter to avoid knowing a little bit about what expectations I have. And even a little bit of knowledge can have an effect: suppose the experimenter accidentally conveys the fact that the participants are expected to do well in this task. Well, there’s a thing called the “Pygmalion effect”: if you expect great things of people, they’ll rise to the occasion; but if you expect them to fail, they’ll do that too. In other words, the expectations become a self-fulfilling prophecy.</p>
</div>
<div id="demand-effects-and-reactivity" class="section level3">
<h3><span class="header-section-number">3.11.9</span> Demand effects and reactivity</h3>
<p>When talking about experimenter bias, the worry is that the experimenter’s knowledge or desires for the experiment are communicated to the participants, and that these affect people’s behaviour <span class="citation">(Rosenthal <a href="#ref-Rosenthal1966" role="doc-biblioref">1966</a>)</span>. However, even if you manage to stop this from happening, it’s almost impossible to stop people from knowing that they’re part of a psychological study. And the mere fact of knowing that someone is watching/studying you can have a pretty big effect on behaviour. This is generally referred to as <strong>reactivity</strong> or <strong>demand effects</strong>. The basic idea is captured by the Hawthorne effect: people alter their performance because of the attention that the study focuses on them. The effect takes its name from a the “Hawthorne Works” factory outside of Chicago <span class="citation">(Adair <a href="#ref-Adair1984" role="doc-biblioref">1984</a>)</span>. A study done in the 1920s looking at the effects of lighting on worker productivity at the factory turned out to be an effect of the fact that the workers knew they were being studied, rather than the lighting.</p>
<p>To get a bit more specific about some of the ways in which the mere fact of being in a study can change how people behave, it helps to think like a social psychologist and look at some of the roles that people might adopt during an experiment, but might not adopt if the corresponding events were occurring in the real world:</p>
<ul>
<li>The <em>good participant</em> tries to be too helpful to the researcher: he or she seeks to figure out the experimenter’s hypotheses and confirm them.</li>
<li>The <em>negative participant</em> does the exact opposite of the good participant: he or she seeks to break or destroy the study or the hypothesis in some way.</li>
<li>The <em>faithful participant</em> is unnaturally obedient: he or she seeks to follow instructions perfectly, regardless of what might have happened in a more realistic setting.</li>
<li>The <em>apprehensive participant</em> gets nervous about being tested or studied, so much so that his or her behaviour becomes highly unnatural, or overly socially desirable.</li>
</ul>
</div>
<div id="placebo-effects" class="section level3">
<h3><span class="header-section-number">3.11.10</span> Placebo effects</h3>
<p>The <strong>placebo effect</strong> is a specific type of demand effect that we worry a lot about. It refers to the situation where the mere fact of being treated causes an improvement in outcomes. The classic example comes from clinical trials: if you give people a completely chemically inert drug and tell them that it’s a cure for a disease, they will tend to get better faster than people who aren’t treated at all. In other words, it is people’s belief that they are being treated that causes the improved outcomes, not the drug.</p>
</div>
</div>
<div id="thats-it-for-this-week-2" class="section level2">
<h2><span class="header-section-number">3.12</span> That’s it for this week</h2>
<p>Whew. That’s it for the readings of the third week. It is perfectly normal if you feel that all this information is overwhelming and perhaps to some extent redundant. However, discussing all these threats allows us to explore different flavors of the same key principles, hoping that the examples of different manifestations will make it easier for you to identify various threats in yours’ or others’ studies. Practice materials for this week can be found on <a href="https://cloud.sowiso.nl">SOWISO</a>. The practice materials are not mandatory, but give you the opportunity to refine your critical skills by reading some mini case-studies and trying to identify, if any, relevant threats to internal validity.</p>

</div>
</div>
<h3> References</h3>
<div id="refs" class="references">
<div id="ref-Adair1984">
<p>Adair, G. 1984. “The Hawthorne Effect: A Reconsideration of the Methodological Artifact.” <em>Journal of Applied Psychology</em> 69: 334–45.</p>
</div>
<div id="ref-becker2009human">
<p>Becker, Gary S. 2009. <em>Human Capital: A Theoretical and Empirical Analysis, with Special Reference to Education</em>. University of Chicago press.</p>
</div>
<div id="ref-de2011human">
<p>Fuente, Angel de la. 2011. “Human Capital and Productivity.”</p>
</div>
<div id="ref-Hothersall2004">
<p>Hothersall, D. 2004. <em>History of Psychology</em>. McGraw-Hill.</p>
</div>
<div id="ref-Kahneman1973">
<p>Kahneman, D., and A. Tversky. 1973. “On the Psychology of Prediction.” <em>Psychological Review</em> 80: 237–51.</p>
</div>
<div id="ref-kampelmann2018does">
<p>Kampelmann, Stephan, François Rycx, Yves Saks, and Ilan Tojerow. 2018. “Does Education Raise Productivity and Wages Equally? The Moderating Role of Age and Gender.” <em>IZA Journal of Labor Economics</em> 7 (1): 1.</p>
</div>
<div id="ref-Pfungst1911">
<p>Pfungst, O. 1911. <em>Clever Hans (the Horse of Mr. Von Osten): A Contribution to Experimental Animal and Human Psychology</em>. Translated by C. L. Rahn. New York: Henry Holt.</p>
</div>
<div id="ref-Rosenthal1966">
<p>Rosenthal, R. 1966. <em>Experimenter Effects in Behavioral Research</em>. New York: Appleton.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="7">
<li id="fn7"><p>Chapter by Matthew Crump<a href="chcorrelationandcaus.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>We are wading into the idea that measures of two things can be related, or correlated with one another. It is possible for the relationships to be more complicated than just going up, or going down. For example, we could have a relationship that where the dots go up for the first half of X, and then go down for the second half.<a href="chcorrelationandcaus.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>The stories about the invention of various statistics are very interesting, you can read more about them in the book, “The Lady Tasting Tea” <span class="citation">(Salsburg <a href="#ref-salsburg2001lady" role="doc-biblioref">2001</a>)</span><a href="chcorrelationandcaus.html#fnref9" class="footnote-back">↩︎</a></p></li>
<li id="fn10"><p>But, we will fill this part in as soon as we can… Brief explanation here is that dividing each measure by its standard deviation ensures that the values in each measure are in the same range as one another.<a href="chcorrelationandcaus.html#fnref10" class="footnote-back">↩︎</a></p></li>
<li id="fn11"><p>The term intervention is often used to refer to <strong>categorical</strong> independent variables.<a href="chcorrelationandcaus.html#fnref11" class="footnote-back">↩︎</a></p></li>
<li id="fn12"><p>During the next ACC skills course (the basestone project) we will explore these designs in more detail.<a href="chcorrelationandcaus.html#fnref12" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-2-describing-data-adapted2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chance.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
